INSERT INTO games (title, type, image_url, game_url, description, difficulty, xp_reward, config, is_active, status) VALUES
('Gun Fest Blast', 'embed', 'https://img.gamemonetize.com/m8vuboqgy1k52vmrgqb2icwqi87h9zdq/512x384.jpg', 'https://html5.gamemonetize.co/m8vuboqgy1k52vmrgqb2icwqi87h9zdq/', 'Do you like gun games! Complete challenging levels and join the fun in this extreme shooter game. Sniper, Deagle, and four different weapons are in the gun fest game. Gun Fest players must increase their weapon count by going through the correct math operations on the parkour with their chosen weapons.

Instruções: Do you like gun games Complete challenging levels and join the fun in this extreme shooter game Sniper Deagle and four different weapons are in the gun fest game Gun Fest players must increase their weapon count by going through the correct math oper', 'Médio', 100, '{"width": 1080, "height": 1920}', false, 'available'),
('sonic jigsaw 2023', 'embed', 'https://img.gamemonetize.com/tvgly45zh0fyxzfz77mlz7zznrnoxxrn/512x384.jpg', 'https://html5.gamemonetize.co/tvgly45zh0fyxzfz77mlz7zznrnoxxrn/', 'Funny Hedgehog sonic from the famous game and cartoon very much missed you. We offer you 12 puzzles about Sonic and his friends. To open the next one, you must complete the current one. The game has three levels of difficulty, suitable for both small and serious players.

Instruções: Funny Hedgehog sonic from the famous game and cartoon very much missed you We offer you 12 puzzles about Sonic and his friends To open the next one you must complete the current one The game has three levels of difficulty suitable for both small and ', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Minecraft Puzzle 2023', 'embed', 'https://img.gamemonetize.com/16rh3cxyzfr6ezpukftkj3sfnw0q5une/512x384.jpg', 'https://html5.gamemonetize.co/16rh3cxyzfr6ezpukftkj3sfnw0q5une/', 'Minecraft Puzzle Time is fun puzzle game suitable for all ages. The aim of the game is simple, just put all small puzzle pieces on the original spot to get a whole image. Have fun playing.

Instruções: Minecraft Puzzle Time is fun puzzle game suitable for all ages The aim of the game is simple just put all small puzzle pieces on the original spot to get a whole image Have fun playing ', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('fashion new haire style ', 'embed', 'https://img.gamemonetize.com/ei89t30m0gf9q9adanxgajj4ido2iswj/512x384.jpg', 'https://html5.gamemonetize.co/ei89t30m0gf9q9adanxgajj4ido2iswj/', 'This girl''s game is ready for fashion! Are you? Hair Salon. Check. Awesome hairstyles? Check. Great fashion? Check. Let''s play! It''s time to be the boss and run your own fashionable hair empire. You have your very own hair salon in this girls game where you get to be the boss. Design cute hairstyles and match them up with the best fashion trends. Spa treatments and colorful makeup makeovers are the perfect additions to add to your fashionable hair salon. All the celebrities are going to want to come to your salon to get a makeovers because of

Instruções: This girl s game is ready for fashion Are you Hair Salon Check Awesome hairstyles Check Great fashion Check Let s play It s time to be the boss and run your own fashionable hair empire You have your very own hair salon in this girls game wher', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Spinner Battle', 'embed', 'https://img.gamemonetize.com/izct09j7o33ngu0eovsbwh4z7kbjqzj4/512x384.jpg', 'https://html5.gamemonetize.co/izct09j7o33ngu0eovsbwh4z7kbjqzj4/', 'Drag the spinner to knock all the other spinners out of the stadium. You have to destroy all your opponents and live to the end. The last spinner wins the match.

Instruções: Mouse', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Grave Driving Unblocked', 'embed', 'https://img.gamemonetize.com/jm9qpgsto5r0px1d4b7afbkya10uzmui/512x384.jpg', 'https://html5.gamemonetize.co/jm9qpgsto5r0px1d4b7afbkya10uzmui/', 'Zombies are everywhere. Unfortunately, you don’t have any weapon. But you do have a car! Now show those zombies who is the boss! Will you beat all levels and become the drift killer?

Instruções: w a s d or arrows and space', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('2048 extended', 'embed', 'https://img.gamemonetize.com/agg62zy9ldm85xkxzm9nr0kyfj6tdxum/512x384.jpg', 'https://html5.gamemonetize.co/agg62zy9ldm85xkxzm9nr0kyfj6tdxum/', '2048 is a beautiful and addictive sliding block numbers puzzle game. Merg numbers, create 2048 tile, win the game, and make a high score. play endless 2048 Puzzle and have fun.

Instruções: fingers keyboard mouse', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Koby Jump .IO', 'embed', 'https://img.gamemonetize.com/tpf2xnonujgbpfyeqts6vw6jfa1fd95r/512x384.jpg', 'https://html5.gamemonetize.co/tpf2xnonujgbpfyeqts6vw6jfa1fd95r/', 'Koby Jump Escape is a great HTML5 platform game. Help Koby to escape from prison. On every level you need to pickup the 3 money bags to unlock the door. This prison have 13 levels. Good luck!

Instruções: mouse or fingers', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Cops Escape', 'embed', 'https://img.gamemonetize.com/3lqld3tqb2q4gis2lse15gm4dyh377ra/512x384.jpg', 'https://html5.gamemonetize.co/3lqld3tqb2q4gis2lse15gm4dyh377ra/', 'When you play as a fugitive, run around the map, dodging cops and other annoying obstacles. Climb buildings and avoid traps to outwit law enforcement and get to the finish line.

Instruções: Mouse', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Avaliando Comerciais', 'embed', 'https://img.gamemonetize.com/cimfc02zyjuol9s6rd000st6gczz204j/512x384.jpg', 'https://html5.gamemonetize.co/cimfc02zyjuol9s6rd000st6gczz204j/', 'Este aplicativo gratuito é feito para você analisar os comerciais, dizendo sim ou não, perfeito para passar o tempo em frente a tela vendo diversas coisas diferente.

Instruções: Mouse ou Toque faz todas as fun es', 'Médio', 100, '{"width": 2000, "height": 960}', false, 'available'),
('HexTank.io', 'embed', 'https://img.gamemonetize.com/8ugcliynfk8xz49yci7jotwysw24r8ik/512x384.jpg', 'https://html5.gamemonetize.co/8ugcliynfk8xz49yci7jotwysw24r8ik/', 'HexTank.io is a play-to-earn Web3 instant game built on the Nimiq blockchain. The action takes place in a PVP sci-fi battle arena. You are in charge of a HexTank. Your job is to eliminate all other players and climb to the top of the score leaderboard. HexTank.io is available on all major browsers, including desktop and mobile versions.

Instruções: DESKTOP KEYBOARD WASD or ARROW KEYS for movement SPACE for shooting GAMEPAD JOYSTICK THUMB STICKS for movement L1 L2 R1 R2 for shooting MOBILE TOUCH CONTROLS ARROWS for movement RED CIRCLE for sh', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Fall Beans 2023', 'embed', 'https://img.gamemonetize.com/1kls4p627b12fuyy8e0m3m73mkcrr4j2/512x384.jpg', 'https://html5.gamemonetize.co/1kls4p627b12fuyy8e0m3m73mkcrr4j2/', 'Fun and colorful races on different race areas await you in the Fall Beans game. The aim of the game is to advance in each race without being eliminated. gamesnout.com, friv.ee, girlgames.ee

Instruções: Use arrow keys to move and space key to jump on desktop ', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Hammer Master io', 'embed', 'https://img.gamemonetize.com/hjy2vk3puaewim5dm7wrlzzkwo7cbhle/512x384.jpg', 'https://html5.gamemonetize.co/hjy2vk3puaewim5dm7wrlzzkwo7cbhle/', 'Smash the players on the battlefield and absorb their power! Join the gang beasts fight and enjoy the crazy action. Become bigger and stronger kicking every buddy in the PvP io arena! Win the round and become the last stickman fighter who lived in this battle royal!

Instruções: Run smash avoid other smash heroes to become the last alive Only one fighter will stay in this arena So be this fighter ', 'Médio', 100, '{"width": 1334, "height": 750}', false, 'available'),
('Escape Room: Mystery Word', 'embed', 'https://img.gamemonetize.com/diy0pg8mpyflucxnulnxwm1c2vx7tawj/512x384.jpg', 'https://html5.gamemonetize.co/diy0pg8mpyflucxnulnxwm1c2vx7tawj/', 'The most innovative escape game of all time with a puzzle experience, you don''t want to miss it! Locked in a strange room, you must constantly observe, think, guess, infer, until you escape.', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Tank War Zone', 'embed', 'https://img.gamemonetize.com/2w1n1ma24ws9ijsb4yg597dvai27geyv/512x384.jpg', 'https://html5.gamemonetize.co/2w1n1ma24ws9ijsb4yg597dvai27geyv/', 'Congratulations, Welcome to the Mobile Tank League, this is a simple but exciting tank PVP game，you are about to have a tank regiment under your command.

Instruções: 3 You can control your own tank to survive in the world of tanks constantly defeat other tanks pick up various equipment on the map to improve your tank ', 'Fácil', 100, '{"width": 720, "height": 1280}', false, 'available'),
('Falling Elevator', 'embed', 'https://img.gamemonetize.com/cdr69da45cke7ybepsd3e50mj15xlh5g/512x384.jpg', 'https://html5.gamemonetize.co/cdr69da45cke7ybepsd3e50mj15xlh5g/', 'Fall from the Elevator up and down You have to get off the elevator avoid obstacles, so as not to be arrested by the police. Save the elevator from exploding.

Instruções: Fall Breaking Fall down', 'Médio', 100, '{"width": 600, "height": 960}', false, 'available'),
('Missile Escape Master', 'embed', 'https://img.gamemonetize.com/1v4997ji58r2smhaamogig8cip9ltzn0/512x384.jpg', 'https://html5.gamemonetize.co/1v4997ji58r2smhaamogig8cip9ltzn0/', 'Missile Escape is a simple, fast paced and addictive 2D game where your mission is to dodge all homing missiles that comes towards you with one single objective: shoot you down! Use the simple control to fly your plane and avoid the missiles. Make them collide with each other and collect stars to increase final score.

Instruções: Control the plane with joystick whole screen or left right buttons', 'Difícil', 100, '{"width": 720, "height": 1280}', false, 'available'),
('Imposter Smasher IO amusants', 'embed', 'https://img.gamemonetize.com/5bgkn3c1izt5dnf3cyqcqhat79c6bfgc/512x384.jpg', 'https://html5.gamemonetize.co/5bgkn3c1izt5dnf3cyqcqhat79c6bfgc/', 'Imposter Smashers - Fun io game is a super cool, easy and relaxing game. To win this, your mission is simple: crush another teammate with a huge hammer, consume his power to become bigger and stronger, be the only Imposter survival on the battlefield. However, be careful and try to run into other difficult impostors, otherwise you will be crushed.', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Leap the bottle', 'embed', 'https://img.gamemonetize.com/wr4wlp74kijqnfpkkdn69ethjgc0u2j5/512x384.jpg', 'https://html5.gamemonetize.co/wr4wlp74kijqnfpkkdn69ethjgc0u2j5/', 'Flip Bottle Leap 3D - Flip Flip Game Leap Bottle Flip will allow you to explore different rooms, jumping on all kinds of objects: tables, sofas, shelves, lamps, chairs and any object you can imagine that can be found in a room!', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Matchcandy.io', 'embed', 'https://img.gamemonetize.com/tpxorkvnswl2wqz8rwvebyong1g93lkf/512x384.jpg', 'https://html5.gamemonetize.co/tpxorkvnswl2wqz8rwvebyong1g93lkf/', 'Matchcandy.io is a match 3 .io game. Swap and match 3 or more candies of the same type and make points and special candies before time runs out. Play against other players from around the world, earn points, level up, rise to the top of the global leaderboard and unlock achievements.

Instruções:  Mouse on PC Touch on Smartphone and Tablet ', 'Difícil', 100, '{"width": 1200, "height": 830}', false, 'available'),
('Color Crazy Ball Blast - Fire', 'embed', 'https://img.gamemonetize.com/7mifxqbveugr3pzi2b6s3sah8gaomoyn/512x384.jpg', 'https://html5.gamemonetize.co/7mifxqbveugr3pzi2b6s3sah8gaomoyn/', 'Color Crazy Ball Blast is a FREE, fun, and addictive switch color game. However, instead of climbing up the color wheels, you have to shoot the ball to score. However, you should not touch obstacle with different colours or you will die instantly! It’s not as difficult as the usual color switcher reflex game because you can wait until the right moment to shoot the ball.', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Private Zombie Town', 'embed', 'https://img.gamemonetize.com/01u0h96annu7msjhhmg6bgubolsxxs3j/512x384.jpg', 'https://html5.gamemonetize.co/01u0h96annu7msjhhmg6bgubolsxxs3j/', 'Capture people and turn them into zombies. Destroy other zombie teams by increasing the number of zombies. There is always more zombie teams for the last zombie alive.

Instruções: Tab to screen', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Guild of Zany', 'embed', 'https://img.gamemonetize.com/4wy4qs013dt1pgen6bk5giihnbfs57qi/512x384.jpg', 'https://html5.gamemonetize.co/4wy4qs013dt1pgen6bk5giihnbfs57qi/', 'Among the cards you have in your hand, you will often have weapons and shields. These cards are called equipment. When your character moves on them, the card is added to thier inventory. They gains the effect of the weapon and its power. The value of weapons (in yellow) is added to your basic attack. The shields (in blue) give you protection against the first damage received. In this game, you must travel through different levels until you defeat the last boss. To do so, play cards from your hand to the free slots on the field. Once done, end the turn and you will be able to see your character moving forward and interact with the items you played as well as epic battles taking place. Place your cards as best as possible to allow your character to survive.

Instruções: Tap To Play', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Happy Farm Familly', 'embed', 'https://img.gamemonetize.com/x0nfxtoft8ow8idjtdymma9g873pjx62/512x384.jpg', 'https://html5.gamemonetize.co/x0nfxtoft8ow8idjtdymma9g873pjx62/', 'Happy Farm is a fun and challenging management game on farming fruit crops and vegetables. Can you manage a farm and plant crops that you can sell? Plants vegetable and take good care of the plants and be aware of changing weather conditions that affect the plants. Harvest the crop and earn money for upgrades

Instruções: Click To Play ', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Dual Balls', 'embed', 'https://img.gamemonetize.com/3isv7toy4os2tjqtddqudpnnhsrcagjq/512x384.jpg', 'https://html5.gamemonetize.co/3isv7toy4os2tjqtddqudpnnhsrcagjq/', 'This is a simple casual game which rotates in a counter clockwise and a clockwise direction, which makes it a kind of endless runner. If you press left side of the screen, the game will block left and lock its rotation heading and you will start to make a jump quite "unnatural"

Instruções: Tap the two sides of the screen to control', 'Médio', 100, '{"width": 720, "height": 1280}', false, 'available'),
('Jungle Adventures 3', 'embed', 'https://img.gamemonetize.com/voc1v6bm5awehg819h51953hmmn9hidj/512x384.jpg', 'https://html5.gamemonetize.co/voc1v6bm5awehg819h51953hmmn9hidj/', 'If you enjoyed Jungle Adventures & Jungle Adventures 2, you''re sure to love the newest addition to the series. In the middle of the night, the cute Furry inhabitants of the forest are kidnapped by a gang of thugs! Our hero Addu witnesses this tragic act!', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Princess on the Run.io', 'embed', 'https://img.gamemonetize.com/er04qf6rrqq4vpnb4t2pzbskyfportzy/512x384.jpg', 'https://html5.gamemonetize.co/er04qf6rrqq4vpnb4t2pzbskyfportzy/', '"Princess on the Run.io", you will help the princess escape from the castle. They want to marry the girl to the unloved, and she decides to run away. But before you leave the palace, you need to collect your things that the princess will need on the way. But how could it be otherwise, if she should always look beautiful and dignified, corresponding to her status! So let''s help her!

Instruções: Press your finger In the screen ', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Boxer.io - Fun io games', 'embed', 'https://img.gamemonetize.com/2xuio3yz8k4otg14ugm0m5qyoyxxvpw4/512x384.jpg', 'https://html5.gamemonetize.co/2xuio3yz8k4otg14ugm0m5qyoyxxvpw4/', 'Smash the players on the battlefield and absorb their power! Join the gang beasts fight and enjoy the crazy action. Become bigger and stronger kicking every buddy in the PvE io arena! Win the round and become the last stickman fighter who lived in this battle royal!

Instruções: Run smash avoid other smash heroes to become the last alive Only one fighter will stay in this arena So be this fighter ', 'Médio', 100, '{"width": 750, "height": 1334}', false, 'available'),
('CrazySteve.io', 'embed', 'https://img.gamemonetize.com/uqzbzhkjckdjj96mn9sm0mcyoz68tagn/512x384.jpg', 'https://html5.gamemonetize.co/uqzbzhkjckdjj96mn9sm0mcyoz68tagn/', 'The game Crazy Steve io was created for fun and fast fighting. The main task in Crazy Steve is to score as many points as possible and be the coolest. To do this, you need to collect diamonds and apples that appear on the map. For diamonds, you charge more experience than apples, but thanks to apples you can recovery your health. A lot of diamonds fall out of the killed rival. Do you understand what we are inclined to? Yes! You need to scatter around the dynamic checkers, shoot from the bow, attack with the sword, shoot from the fireball and use other weapon in every way to kill the rivals, and then take their diamonds to yourself. By the way, be careful, you can undermine yourself, will be more blood! On the map running animals that you can kill and recovery health. With each new level you increase slightly. Together with the volume increases the ability of your character to collect apples and diamonds. But at the same time you gradually slow down and become more vulnerable to attacks by fast, small and agile rivals. Therefore, the Top player quickly opens the hunting season. Players scour the field in search of a ''fat boy''. So the more diamonds you recruit, the sharper the battle becomes! Another feature of Crazy Steve is that you can undermine your own sword. You can throw 4 dynamite at a time. Only after the explosion of one of them you can throw a new one. On the map are scattered different helmets: wooden, iron, gold, diamond and cart, wear them or sit in the cart to be more protected! Apples and diamonds appear on the map constantly. Players usually fight in the center and therefore one should periodically look at the edges of the map to collect diamonds.

Instruções: Mouse move - Move Left mouse button - Attack Right mouse button - Speed up Enter - Chat', 'Difícil', 100, '{"width": 1000, "height": 800}', false, 'available'),
('EvoWarriors.fun', 'embed', 'https://img.gamemonetize.com/gf8ve9ub8patlfqyyeplw3e40kjriymz/512x384.jpg', 'https://html5.gamemonetize.co/gf8ve9ub8patlfqyyeplw3e40kjriymz/', 'EvoWarriors.fun is a free fantasy style game. Eat steaks, eggs, milk and everything you find to grow in size while you are small, most importantly do not eat amanita, because it reduces your experience and you become smaller! Attack smaller enemies, so you have a better chance of staying alive. You can insurance yourself just run away from large enemies so that they do not kill you with one fell swoop of their powerful weapon or you can donate your experience to the enemy. But you won’t be able to run for a long time, because when you run, your experience decreases. The game has only 15 levels: Knight lvl 1 Knight lvl 2 Knight lvl 3 Assassin lvl 1 Assassin lvl 2 Dwarf lvl 1 Dwarf lvl 2 Dwarf lvl 3 Skeleton lvl 1 Skeleton lvl 2 Skeleton lvl 3 Golem lvl 1 Golem lvl 2 Orc lvl 1 Orc lvl 2 Orc lvl 3 Can you get to level 16 and become the biggest and strongest in the game? Hint: for players who disable the ad blocker, an additional 20% of experience is awarded! One of the effective attack tactics: approach the enemy on the left side so that it is to your right and from your sword, then - immediately attack first!

Instruções: Attack - left mouse button Speed Up - right mouse button', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('MineEnergy.fun', 'embed', 'https://img.gamemonetize.com/bs2466de0q7tdyhevlqw5djxerbabbzm/512x384.jpg', 'https://html5.gamemonetize.co/bs2466de0q7tdyhevlqw5djxerbabbzm/', 'MineEnergy.fun - is a free Minecraft style game. Mine resources, buy in the store and put generators for energy production, put selling blocks to sell resources and energy for money. Buy improved tools, armor, new generators, and automatic miners. Protect your buildings with walls and Tesla coils. Get resources from ores: coal ore iron ore golden ore diamond ore uranium ore Each type of ore has its own miner for automatic extraction of resources. Put the generators: manual generator - generates energy from interacting with it. Not effective, but suitable when there are no other options. solar generator - generates energy from sunlight. wind generator - generates energy from wind. coal generator - generates energy from coal. geothermal generator - generates energy from lava. water turbine - generates energy from water. nuclear generator - generates energy from uranium. Each generator consumes something (or not) and produces energy. Place the “Small seller” or “Big seller” block to sell resources for money. For money you can buy an improved tools: wooden pickaxe - the easiest pickaxe. It produces a few resources, but the cheapest. iron pickaxe - improved pickaxe. Mining more resources. With it, you can mine gold. golden pickaxe - improved pickaxe. Mining more resources. With it, you can mine diamonds. diamond pickaxe - the best pick that does not require energy. Mining more resources. With it, you can mine uranium. drill - dimple electric drill. It extracts more resources, but consumes energy during operation. diamond drill - the best tool for resource extraction. It extracts a huge amount of resources per hit, but also consumes more energy. wrench - removes your blocks. Hit your block with a wrench to remove the block. You can buy armor: leather armor - hard to call it armor, but it''s better than nothing. iron armor - absorbs part of the damage. golden armor - better than iron armor, it absorbs more damage. And players like to show off at her. diamond armor - the most durable armor that does not require energy. A great choice if you do not have generators, but have a lot of money o_O nano armor - carbon fiber armor. It protects better than a diamond armor but consumes energy while absorbing damage. quantum armor - the best armor! Effectively absorbs most of the damage, but consumes more energy. Alas, it does not protect against coronavirus. Protect your buildings with walls, Tesla coils and put a bed that will revive you after death. MineEnergy will let you have fun and not let you get bored!

Instruções: W A S D - Move Left Mouse Button - Attack Place block Left Shift - Speed up E - Shop', 'Médio', 100, '{"width": 1000, "height": 800}', false, 'available'),
('Cross Miners', 'embed', 'https://img.gamemonetize.com/5lwfmp8gwutcywxf6271mz5pi0tn618g/512x384.jpg', 'https://html5.gamemonetize.co/5lwfmp8gwutcywxf6271mz5pi0tn618g/', '"Miners at the Crossroads" is an interesting arcade game, the gameplay of which is similar to the classic third-person runner. Here you will need to help one miner get home after a hard day''s work. But in this he can be prevented by packs of trolls, who can attack the main character at any moment. Also, in addition to this, there is still a large pond and a railway, which also need to be overcome somehow. Such a trip home can be called a whole adventure.

Instruções: jump over logs dodge mining carts and collect coins ', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Gravity Rider: Space Bike Race', 'embed', 'https://img.gamemonetize.com/qc8wtmr7zjju3tnhzap5txofompvdt98/512x384.jpg', 'https://html5.gamemonetize.co/qc8wtmr7zjju3tnhzap5txofompvdt98/', 'On your marks, get set, go! Ride your bikes through space and compete in 3D races on a selection of planets to become the best rider. Beat your opponents, break records and become the champion in this Superbike game. Select a motocross bike and try your hand at some fast-paced motorcycle racing, or opt for a hoverbike for some extreme riding - or even an off-road quad bike if you prefer.', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Tornado.io', 'embed', 'https://img.gamemonetize.com/1smka6j97blcuektwham1dtdk7atuhzd/512x384.jpg', 'https://html5.gamemonetize.co/1smka6j97blcuektwham1dtdk7atuhzd/', 'A powerful tornado can destroy everything! Especially the water tornado formed from the sea. In Super Tornado.io this multiplayer online game, you will become the master of the world. You can control the city by the sea at will, blow away all the buildings and cars, and compete with other players. Tornadoes fight, swallow them and absorb them as part of your own power. When you have enough power, don''t be afraid of any other players, use tornadoes to rule the world until you are satisfied.

Instruções: Mouse or tap to play ', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('SuperHero.io', 'embed', 'https://img.gamemonetize.com/eccaym7ri1dqacofsiygwcl9oc66hqwo/512x384.jpg', 'https://html5.gamemonetize.co/eccaym7ri1dqacofsiygwcl9oc66hqwo/', 'A game with elements of a shooter in which you have to fend off enemies. They will attack from all sides. The player\\\\\\\&#39;s arsenal may contain various items that can be used to defeat the enemy. You need to move around the playing field, dodging enemy attacks and hit him with your weapons. There are items on the field that can both help the player and harm

Instruções: Use the mouse to control the SuperHero 39 s direction and space bar to speed up it ', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Archers.io', 'embed', 'https://img.gamemonetize.com/cnnfqizfjcczajyet2v4aruj1id3ykkf/512x384.jpg', 'https://html5.gamemonetize.co/cnnfqizfjcczajyet2v4aruj1id3ykkf/', 'Dexterity and the ability to make quick decisions will help you become the first and strongest in the new multiplayer io fun, not only the place in the standings, but also the number of your archer warriors depends on this.

Instruções: Click in the screen to collect more archers ', 'Fácil', 100, '{"width": 720, "height": 1280}', false, 'available'),
('Knives Strikes', 'embed', 'https://img.gamemonetize.com/fczte5630i0p1fp7v58oc8w6eo3zc54c/512x384.jpg', 'https://html5.gamemonetize.co/fczte5630i0p1fp7v58oc8w6eo3zc54c/', 'Throw the knives and hit the targets and get all the tomatoes. Unlock all knives!

Instruções: Simple input just click with your mouse on PC or tap on smartphone', 'Médio', 100, '{"width": 960, "height": 600}', false, 'available'),
('Magic Tiles - Piano Squid', 'embed', 'https://img.gamemonetize.com/7s9hk1ka1l8joyhwzkkn88dr4294bzam/512x384.jpg', 'https://html5.gamemonetize.co/7s9hk1ka1l8joyhwzkkn88dr4294bzam/', 'How fun is it to capture the most precious moments of the year with a wink of rhythms? Let’s MUSIC your soul with the beat of hit songs 2022. Magic Tiles - Piano Fire is a special game in different genres of piano games with wonderful gameplay. It Blends piano and EDM music perfectly, you can feel the collision of ice and fire, and get addicted to hot and popular songs around the world! Learn piano online is an extremely interesting music game on Fun Game. When participating in Learn Piano Online, players will have the opportunity to experience the feeling of playing the piano right on their screen. Your task is to touch the running notes to play the piano. If you accidentally touch and slide out, you will lose.', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Animal.io 3D', 'embed', 'https://img.gamemonetize.com/01afiyuzovajt0olhhl3z6cr6cnjp2sp/512x384.jpg', 'https://html5.gamemonetize.co/01afiyuzovajt0olhhl3z6cr6cnjp2sp/', 'Animal.io is an interesting multiplayer online game. Control your animal to push others off the platform by swinging your tail. Meat can increase your size and hamburger can add the length of the tail, the mushroom will become little size but faster. Kill your enemies and win the game! To unlock more adorable animals!

Instruções: Mouse or tap to play ', 'Fácil', 100, '{"width": 500, "height": 800}', false, 'available'),
('Paddle', 'embed', 'https://img.gamemonetize.com/mnweirvai2f2rakj0cmoye26cna3k3wp/512x384.jpg', 'https://html5.gamemonetize.co/mnweirvai2f2rakj0cmoye26cna3k3wp/', 'The game is a leisure puzzle game. It has a large-scale production scene, a variety of styles, and color matching to bring a new visual experience. It enjoys a large-scale water battle in the water park. The passionate large-scale battle mode tests the reaction and hand speed of the players. It is an interesting game that can ignite the passion of the players.

Instruções: 1 global co-servers and players from around the world compete 2 Classic IO casual games with magical level breaking gameplay 3 a variety of online competition mode air and underground dual experience 4 Control the character to sprint to the en', 'Médio', 100, '{"width": 750, "height": 1334}', false, 'available'),
('Tsoro', 'embed', 'https://img.gamemonetize.com/4v8t1gqglgte0af8mlr4slgdbo6lyoq0/512x384.jpg', 'https://html5.gamemonetize.co/4v8t1gqglgte0af8mlr4slgdbo6lyoq0/', 'Tsoro is based on an ancient board game which has been played for hundreds of years. They are three game modes which you can freely choose from: (1) Time restricted (2) Moves restricted (3) Points restricted (4) Open Game The goal of the game is to pick balls and drop as many as you can in the bank. What makes this tsoro a cut from its peers are star balls. These drop the standard clichés in a bucket by changing the ball colour, miraculously adding balls and so much more, making the game more exciting than ever. After all we’re in a digital generation

Instruções: Use arrow keys joystick axis buttons for hand movement Press A or joystick button 0 to drop pick balls ', 'Difícil', 100, '{"width": 640, "height": 480}', false, 'available'),
('Mr Gunslinger-shooting games', 'embed', 'https://img.gamemonetize.com/f7vjhd1zwyd8mdnxi29uqmuppxak19x2/512x384.jpg', 'https://html5.gamemonetize.co/f7vjhd1zwyd8mdnxi29uqmuppxak19x2/', 'The lone gunman, you must defeat a group of zombies who want to catch you.The game has a variety of classic gun battle modes, exquisite graphics, smooth shooter combat actions, fierce and exciting shooting effects, and amazing game effects!

Instruções: Be careful You are surrounded To stand out from the siege you must defeat groups of zombies who want to catch you Entering a world where being itself is destroying you You are a lone gunman the only force capable of resisting and defeating the co', 'Fácil', 100, '{"width": 750, "height": 1334}', false, 'available'),
('Bumper Ball io', 'embed', 'https://img.gamemonetize.com/exr8ozp5gdvau2u6ye32wnh5nxufb570/512x384.jpg', 'https://html5.gamemonetize.co/exr8ozp5gdvau2u6ye32wnh5nxufb570/', 'Knock opponents off the stage with your bumper ball.A fun and fast-paced hyper-casual .io game. Every time you beat an opponent, you will change your size and try to be the last laughing person on the map.

Instruções: Bravely smash other players in action-packed competitive matches with simple one-finger controls ', 'Médio', 100, '{"width": 1334, "height": 750}', false, 'available'),
('Flappy Berker', 'embed', 'https://img.gamemonetize.com/6f3wdunoybm0uebom3fs2v598ho2p36c/512x384.jpg', 'https://html5.gamemonetize.co/6f3wdunoybm0uebom3fs2v598ho2p36c/', 'Every 15 Bananas you get 1 speed level up Can You Reach to the Level 10!

Instruções: W or UpArrow for jumping', 'Difícil', 100, '{"width": 960, "height": 600}', false, 'available'),
('Knives Crash io', 'embed', 'https://img.gamemonetize.com/nu0d75e4ljy0m9xf9at70sug2fvz5hzu/512x384.jpg', 'https://html5.gamemonetize.co/nu0d75e4ljy0m9xf9at70sug2fvz5hzu/', 'Strike with greater force Navigate your way across this knives game to crush your opponents and collect knives. The more knives you collect, the better are your chances to run and strike your opponents with greater force. Defeat your opponents Crush your competitors and slice their knives,collect them for growing your strength later on. You can also kill your enemy by defense！

Instruções:  Hit the play button to match with opponents Control the direction of your Knives Devour smaller opponents and grow in size Collect all the knives to win a level', 'Fácil', 100, '{"width": 720, "height": 1280}', false, 'available'),
('Count Masters: Stickman Games', 'embed', 'https://img.gamemonetize.com/cdbqrwl45z3ant14u6re9d4c6cysytk6/512x384.jpg', 'https://html5.gamemonetize.co/cdbqrwl45z3ant14u6re9d4c6cysytk6/', 'Choose the best gate, pass through it, and bring stickman warriors together to clash with the opposing crowd. Become the crowd master and lead your people through the crowded city till the end of this epic race. Crash obstacles and beat everyone on your way, collect coins and upgrade your levels. Defeat the King-stickman in the final battle and take the castle! Looking for some fun and thrill? Then this 3d running game is just for you. Count Masters is one of the most exciting clash games of all times! You start the battle alone but trust us: there are no chances for you to feel lonely. This city takeover game features fascinating graphics and simple mechanics. You have a chance to get absorbed in the bright world of Count Masters full of gang fights and stickman battles. Get ready to spend hours playing one of the most thrilling running games. We promise: you won’t get bored! FEATURES: Dynamic race. You are not a simple runner but the boss of a whole crowd of stickmen. Gather your gang and lead them to the main clash of their life!

Instruções: USE YOUR MOUSE TO PLAY', 'Médio', 100, '{"width": 600, "height": 960}', false, 'available'),
('snake.io puzzle', 'embed', 'https://img.gamemonetize.com/7r4ohwbb9xn1hdsmltgegvoaxkl3o5ca/512x384.jpg', 'https://html5.gamemonetize.co/7r4ohwbb9xn1hdsmltgegvoaxkl3o5ca/', 'Play against other people online! Can you become the longest slither? If your head touches another player, you will explode and then it''s game over. But if others run into YOU, then THEY will explode, and you can eat their remains! In slither.io, you have a chance to win even if you''re tiny. You can swerve in front of a much larger player to defeat them, no matter how big you are! Download now and start slithering! Good luck!

Instruções: Use the mouse to control the worm s direction and space bar to speed up it ', 'Difícil', 100, '{"width": 960, "height": 600}', false, 'available'),
('Snake io war', 'embed', 'https://img.gamemonetize.com/3oeuck11kfyukgvc8zplpnkf3hyuwgr9/512x384.jpg', 'https://html5.gamemonetize.co/3oeuck11kfyukgvc8zplpnkf3hyuwgr9/', 'Snake io war combines a new pop aesthetic with the oldest classic snake game mechanics.You love games with tons of real fun and dynamic action? Then welcome to the Snake io war, an awesome arcade, where you can become the great champion of the arena! Collect yummies and different powerups, defeat enemies, and become the biggest worm of them all!

Instruções: Snake io war started with a snake and tried to eat something in each level to make it bigger Twist your snake in the food pile and try to beat the scores of other players-how long can you survive ', 'Fácil', 100, '{"width": 1280, "height": 720}', false, 'available'),
('Stickman vs Zombies Wars', 'embed', 'https://img.gamemonetize.com/99yaycc36np5ve6eto9pr9qfrwgy5xqx/512x384.jpg', 'https://html5.gamemonetize.co/99yaycc36np5ve6eto9pr9qfrwgy5xqx/', 'Ninja vs Zombies is an action-packed platformer. Fight your way through challenging environments filled with zombie hordes and dangerous traps deadly not just for ninja, but zombies too (giant saw blades, fire, acid, explosive barrels, spikes, spears, rolling stones...). Use throwing ninja knives and sword combo attacks to defeat zombies. Be fast or else zombies will get you!

Instruções: Move with ninja skill through chaotic hostile levels avoiding thunder hits and explosions Evade traps with timing and precision Collect various power-ups shield thunder knives coins health ', 'Médio', 100, '{"width": 1280, "height": 720}', false, 'available'),
('Aquapark.io Water Slide Park', 'embed', 'https://img.gamemonetize.com/o7ec003cidllbncxbuwawxhsk8kfgcco/512x384.jpg', 'https://html5.gamemonetize.co/o7ec003cidllbncxbuwawxhsk8kfgcco/', 'The summer is magic in this awesome action packed water park game. Visit thrilling aqua parks around the world for the ultimate rush and compete against other water park maniacs to be the first down the slide! No worries: Smashing and crashing into your opponents is allowed! This game offers the summer in your pocket: - Smash and bump your opponents of the water slide - Unlock many different aqua parks - Every aquapark features unique slippery tracks - Incredible ragdoll physics - Simple one touch io style game play - Choose your own characters (new girls and boys added) - Pick and upgrade your ride slide

Instruções: Use your Mouse to Play', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available');



INSERT INTO games (title, type, image_url, game_url, description, difficulty, xp_reward, config, is_active, status) VALUES
('Aqua Park Drift.IO', 'embed', 'https://img.gamemonetize.com/8ssqpsc6ezo8hpo5s5i7h1huwuhkqgij/512x384.jpg', 'https://html5.gamemonetize.co/8ssqpsc6ezo8hpo5s5i7h1huwuhkqgij/', 'Enjoy the "Aqua Park Drift" game! You will control an inflatable boat. Rescue people who have fallen into the water along a deep and long river. Will you manage to save all the people? Be careful. You can also accidentally drown everyone by crashing into something. Visiting the game every day will get different bonuses with which it will be easier to level up. Successfully overcome the various obstacles and deep waterfalls that will meet on your way and perform incredible acrobatic tricks! Splash upside down, so you don''t lose your team members. It sounds simple. But will you make it to the finish line? Only the most experienced and poised sailors will accomplish their mission.

Instruções: Drag to left right or left ', 'Fácil', 100, '{"width": 720, "height": 1280}', false, 'available'),
('Bridge Sort', 'embed', 'https://img.gamemonetize.com/5kpmjgzliywuy39q882c46lgg6ri6ahm/512x384.jpg', 'https://html5.gamemonetize.co/5kpmjgzliywuy39q882c46lgg6ri6ahm/', 'Build bridges between platforms and sort colorful crowd to their platform.

Instruções: Tap To Play', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('ItchExplorer', 'embed', 'https://img.gamemonetize.com/atziri2dqs8fnpdj9jdn8jo93tj9fv7g/512x384.jpg', 'https://html5.gamemonetize.co/atziri2dqs8fnpdj9jdn8jo93tj9fv7g/', 'ItchExplorer, a virtual arcade! Browse and play the top games on itch.io Brought to you by MIDL. Click on this link for more games >> https://www.midl.tk

Instruções: W UP Arrow Up S Down Arrow Down A Left Arrow Left D Right Arrow Right Mouse Cursor Select Game Drag Items Move', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('2048 Unicorn', 'embed', 'https://img.gamemonetize.com/m1bpq57w39l7896s3raroj511c9jqpxa/512x384.jpg', 'https://html5.gamemonetize.co/m1bpq57w39l7896s3raroj511c9jqpxa/', 'Join the numbers and get to the 2048 tile!

Instruções: Use mouse to play ', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('2048 Bubble Box 3D', 'embed', 'https://img.gamemonetize.com/q2kj6s7yjm91dxq7ajmcl67xgc4qg568/512x384.jpg', 'https://html5.gamemonetize.co/q2kj6s7yjm91dxq7ajmcl67xgc4qg568/', 'Chain Cube 2048 is a great puzzle game for those, who like challenging brain-teasers and logic number games. Believe us, it is much harder to reach 2048 than drop the number. A whole new take on the famous brainteaser number game! Now in 3D with crazy fun physics! The blocks don\&#39;t stay in place they fall realistically and bounce off each other if you havent managed to merge cube blocks! Don\&#39;t try and hide it, we know you can\&#39;t get enough fun 2048 games! So don\&#39;t be shy, do yourself a favor and download Chain Cube 2048! You need to drop the number blocks to get the highest score and solve the puzzle!.

Instruções:  Tap screen shoot bricks Merge blocks in a line with the same number Get higher number and challenge high score', 'Médio', 100, '{"width": 600, "height": 960}', false, 'available'),
('Party io 3d', 'embed', 'https://img.gamemonetize.com/f87z6uizn4ky192t9i9t58zt4el1kc2e/512x384.jpg', 'https://html5.gamemonetize.co/f87z6uizn4ky192t9i9t58zt4el1kc2e/', 'Party.io is an addicting 3D multiplayer arena game. In the game, players need to control their character to fight with other players. You need to throw all your opponents down. The more people you throw, the higher score you will get. Come on, it''s not an easy game, try to get a high rank on the Party.io!

Instruções: Mouse or tap to play ', 'Difícil', 100, '{"width": 504, "height": 800}', false, 'available'),
('Nitro Knight io', 'embed', 'https://img.gamemonetize.com/kr9c0agadokmceuijswdrusxvwnln7nr/512x384.jpg', 'https://html5.gamemonetize.co/kr9c0agadokmceuijswdrusxvwnln7nr/', 'Nitro Knights.io is undoubtedly one of the most interesting multiplayer online battle games this year, with addictive gameplay and a 2D art style. If you are a lover of IO games, don''t miss this game! Vigorously triumph in lance battles between futuristic knights in hyperspace. Beat all the levels! Equip the best hovercraft and lance your way to victory! Are you ready? If you like this game, don''t forget to share it with your friends!

Instruções: Mouse or tap to play ', 'Fácil', 100, '{"width": 504, "height": 800}', false, 'available'),
('Flappy Bird Old Style', 'embed', 'https://img.gamemonetize.com/chjmxfxpz4uzqk90ayam4mg5l4hqm404/512x384.jpg', 'https://html5.gamemonetize.co/chjmxfxpz4uzqk90ayam4mg5l4hqm404/', 'Play Flappy bird old style here online and is for free. Click or Tap on the screen, to get started. Fly the bird as far as you can without hitting a pipe and try to wins all medals.

Instruções: Just Click Tap to play ', 'Médio', 100, '{"width": 320, "height": 568}', false, 'available'),
('The Simple Piano', 'embed', 'https://img.gamemonetize.com/3ys6b87ick5q71415hbzjaemf36f2csw/512x384.jpg', 'https://html5.gamemonetize.co/3ys6b87ick5q71415hbzjaemf36f2csw/', 'Simple piano application to learn play the piano and with realistic sounds of instruments. How to Play Piano: Just run your fingers over the real piano tiles, playing live music and feel like a real musician. Features: • It works with all screen resolutions • Full piano keyboard • Multi-Touch • Easy for children

Instruções: Just one Click Tap to play ', 'Difícil', 100, '{"width": 1024, "height": 600}', false, 'available'),
('Knifes VS Sword.Io', 'embed', 'https://img.gamemonetize.com/9egr7svnw9paqfb6cserkibbjee6lf3p/512x384.jpg', 'https://html5.gamemonetize.co/9egr7svnw9paqfb6cserkibbjee6lf3p/', '"Knife Vs Sword" in which you have to find out which melee weapon will be most effective during a fierce battle on the battlefield? Will you be a stealthy ninja, stealthily eliminating enemies with insidious backstabs, or a valiant samurai fighting the enemy in a fair duel? The choice is yours!

Instruções: Click on the screen move left or right ', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Fly SmasherZ', 'embed', 'https://img.gamemonetize.com/zs96k86pjdu8kd1fnfcifeeb5li7kai3/512x384.jpg', 'https://html5.gamemonetize.co/zs96k86pjdu8kd1fnfcifeeb5li7kai3/', 'Smash all the Flies that appear on the screen with your fingers, before they leave the screen, you have three lives and be very careful don''t tap the red fly, they are very dangerous. Have fun with this endless smasher game. Product feature bullets: • Very fun game for kids and babies. • Endless game modality for Kids. • Very easy to play. • Nice 2D graphics. • Cool ambience nature music. • Amazing animations.

Instruções: Just one Click Tap to play ', 'Médio', 100, '{"width": 1024, "height": 600}', false, 'available'),
('Dont Drop The Soap', 'embed', 'https://img.gamemonetize.com/rpsk0jfhk8n6wyez74v48qpkzxe6yk4k/512x384.jpg', 'https://html5.gamemonetize.co/rpsk0jfhk8n6wyez74v48qpkzxe6yk4k/', 'Welcome to Don’t Drop the Soap! The object is simple. Keep the soap in the air for as long as you can, and pop as many bubbles as possible to increase your score along the way. How long until you drop the drop the soap? have fun!

Instruções: Just one Click Tap to play ', 'Difícil', 100, '{"width": 768, "height": 1024}', false, 'available'),
('Nitro Knights.io - Strategy Fighting Game', 'embed', 'https://img.gamemonetize.com/u6euldk5mipqphq3gd35t37vuhmlb9t7/512x384.jpg', 'https://html5.gamemonetize.co/u6euldk5mipqphq3gd35t37vuhmlb9t7/', 'Nitro Knights.io is undoubtedly one of the most interesting multiplayer online battle games this year, with addictive gameplay and a 2D art style. If you are a lover of IO games, don''t miss this game! Vigorously triumph in lance battles between futuristic knights in hyperspace. Beat all the levels! Equip the best hovercraft and lance your way to victory! Are you ready? If you like this game, don''t forget to share it with your friends!

Instruções: Tap or click ', 'Fácil', 100, '{"width": 720, "height": 1280}', false, 'available'),
('Saw Machine.io - 3D Survival Game', 'embed', 'https://img.gamemonetize.com/mh2w49xb539wnjgu6d808liynzner1ny/512x384.jpg', 'https://html5.gamemonetize.co/mh2w49xb539wnjgu6d808liynzner1ny/', 'Saw Machine.io is an exhilarating casual game. It will not be exaggerating to say that human history is somehow a history full of suppression, vividly demonstrating the principle of survival of the fittest. In this game, similar rules apply. Ruthlessness is the key to survival. Initially serving as a tool with a long blade with sharp points or teeth along with one of its edges, a saw will turn into a deadly weapon. The velocity of the vehicle carrying the saw will enhance its lethality to an unimaginable extent!

Instruções: Tap or click ', 'Médio', 100, '{"width": 720, "height": 1280}', false, 'available'),
('Party.io - 3D Survival Game', 'embed', 'https://img.gamemonetize.com/9j0mf9y3942pekpu2phm9tfj1ou8u3mk/512x384.jpg', 'https://html5.gamemonetize.co/9j0mf9y3942pekpu2phm9tfj1ou8u3mk/', 'Party.io is an addicting 3D multiplayer arena game. In the game, players need to control their character to fight with other players. You need to throw all your opponents down. The more people you throw, the higher score you will get. Come on, it''s not an easy game, try to get a high rank on the Party.io!

Instruções: Tap or click ', 'Difícil', 100, '{"width": 720, "height": 1360}', false, 'available'),
('Farmers.io', 'embed', 'https://img.gamemonetize.com/yt7e8qx4za8r805j6i5gwsyzccmf7xi2/512x384.jpg', 'https://html5.gamemonetize.co/yt7e8qx4za8r805j6i5gwsyzccmf7xi2/', 'Farmers.io is an interesting multiplayer relaxing game in which you can compete with other players. You will drive a truck and collect crops. The more crops you collect, the longer you will become. Avoid other trucks, if you crash into them, you will lose. Try to get the first place to enter the next level. You will unlock more cars when you pass a certain number of levels. Have a good time in our new game Farmers.io!

Instruções: Tap or click ', 'Fácil', 100, '{"width": 1080, "height": 1920}', false, 'available'),
('Super Tornado.io - Tornado Rush', 'embed', 'https://img.gamemonetize.com/kdrph2e3tzo27kl1jhz1ays9urs7ib16/512x384.jpg', 'https://html5.gamemonetize.co/kdrph2e3tzo27kl1jhz1ays9urs7ib16/', 'A powerful tornado can destroy everything! Especially the water tornado formed from the sea. In Super Tornado.io this multiplayer online game, you will become the master of the world. You can control the city by the sea at will, blow away all the buildings and cars, and compete with other players. Tornadoes fight, swallow them and absorb them as part of your own power. When you have enough power, don''t be afraid of any other players, use tornadoes to rule the world until you are satisfied.

Instruções: Tap or click ', 'Médio', 100, '{"width": 720, "height": 1280}', false, 'available'),
('Animal.io - 3D Animal Warfare', 'embed', 'https://img.gamemonetize.com/ccox3h8gw8bzvvwbx7hnmnhzujb7lum4/512x384.jpg', 'https://html5.gamemonetize.co/ccox3h8gw8bzvvwbx7hnmnhzujb7lum4/', 'Animal.io is an interesting multiplayer online game. Control your animal to push others off the platform by swinging your tail. Meat can increase your size and hamburger can add the length of the tail, the mushroom will become little size but faster. Kill your enemies and win the game! To unlock more adorable animals!

Instruções: Tap or click ', 'Difícil', 100, '{"width": 750, "height": 1334}', false, 'available'),
('Best Sonic Boom Mod', 'embed', 'https://img.gamemonetize.com/5pns2ma8rdnm760jqkww77mxr76kzab4/512x384.jpg', 'https://html5.gamemonetize.co/5pns2ma8rdnm760jqkww77mxr76kzab4/', 'Prepare yourself for the most epic parkour map collection for mcpe, with the hedgehog named sonic boom! DISCLAIMER: This is an unofficial application for Minecraft Pocket Edition. This application is not affiliated in any way with Mojang AB. The Minecraft Name, the Minecraft Brand and the Minecraft Assets are property of Mojang AB or their respectful owner. All rights reserved. In accordance with http://account.mojang.com/documents/brand_guidelines Welcome to Mod Sonic Boom for MCPE! This app compiles the popular sonic boom dash skins for minecraft pocket edition 1.14 that you’ve been looking for. Plenty of parkour maps every version of PE can run, and Sonic boom the hedgehog skins that will blow your mind! Wearing sonic boom the hedgehog skins will give you the ability to jump all over the map of minecraft and gives mcpe world a very strange, anime touch. You can enjoy these sonic boom mods and the hedgehog skins with friends in online servers or offline with mod launcher. Don’t forget that there’s no required third-party apps such as launcher mcpe or master addons installer. The skins and mods of sonic boom the hedgehog provided are one click download.

Instruções: touchscreen or mouse', 'Fácil', 100, '{"width": 1280, "height": 720}', false, 'available'),
('City Runner 3D.io', 'embed', 'https://img.gamemonetize.com/ty5z6wiuzekwmgh448ie9865wmyu33id/512x384.jpg', 'https://html5.gamemonetize.co/ty5z6wiuzekwmgh448ie9865wmyu33id/', 'Welcome to City Runner.io Multiplayer game. Choose your character and tap play! Run, and avoid obstacles and be the first who touches the finish line and don''t let the giant blue monster crushes you. Collect more coins to unlock more characters

Instruções: follow game instructions', 'Médio', 100, '{"width": 720, "height": 1280}', false, 'available'),
('Knives.IO', 'embed', 'https://img.gamemonetize.com/4rl2r7mdk02ry33lqmp8aon2zrhlwl8o/512x384.jpg', 'https://html5.gamemonetize.co/4rl2r7mdk02ry33lqmp8aon2zrhlwl8o/', 'Knife.Io is a game with a dynamic storyline. Start growing your knife right now. Having tried to get a more knifes, a small knife never gets stuck in one place – he’s ready to bite everyone. However, there is a danger to be eaten by a more successful player.

Instruções: Use the mouse to control the knife s direction and space bar to speed up it ', 'Difícil', 100, '{"width": 720, "height": 1280}', false, 'available'),
('Falling People 3D', 'embed', 'https://img.gamemonetize.com/1ja8is09kvuz9m5gaiy8jaqq90shjfwn/512x384.jpg', 'https://html5.gamemonetize.co/1ja8is09kvuz9m5gaiy8jaqq90shjfwn/', 'Are You ready for the ultimate crazy race? Complete all the parkours with lots of different obstacles and experience breath taking challenge. Take risks to be first, Avoid moving obstacles and do not fall from edges. Fall People 3D also has Epic Chellenging and crazy Levels and your mission is to complete them all. Good Luck

Instruções: Hold joystick and move left right', 'Fácil', 100, '{"width": 720, "height": 1280}', false, 'available'),
('Pixel Parkour', 'embed', 'https://img.gamemonetize.com/k8cvztgjdizbgpfwnw52ux5c5ihuubu1/512x384.jpg', 'https://html5.gamemonetize.co/k8cvztgjdizbgpfwnw52ux5c5ihuubu1/', 'Pixel parkour, this is a Parkour game created in pixel style. This pixel Parkour has a large number of levels, and each level has different props that players need to collect

Instruções: Simple to play easy to use and smooth operation experience will bring you the ultimate Parkour experience Rich game prop settings make it easier for you to get through one obstacle after another and run farther Mengmengda s cute pet is waiting fo', 'Médio', 100, '{"width": 720, "height": 1334}', false, 'available'),
('Extreme Parkour', 'embed', 'https://img.gamemonetize.com/9we18sm7y3cvlkc41466ixdot5o258w5/512x384.jpg', 'https://html5.gamemonetize.co/9we18sm7y3cvlkc41466ixdot5o258w5/', 'A very good parkour theme of the Sports Game, very smooth, can make a lot of professional action, do not look down on her oh, her skill is very good, can be said to be a wall.

Instruções: Parkour theme of a very good sports game very smooth can do a lot of professional action do not underestimate her oh her skills but very good ', 'Difícil', 100, '{"width": 750, "height": 1334}', false, 'available'),
('Strongest Parkour', 'embed', 'https://img.gamemonetize.com/5f8f45cw7j4l5y4tl0smrnev01s11qux/512x384.jpg', 'https://html5.gamemonetize.co/5f8f45cw7j4l5y4tl0smrnev01s11qux/', 'A full of fun Parkour challenge game

Instruções: The game combines a number of popular Parkour Games bring you a new adventure experience each level there are many dangerous obstacles and traps constantly watching the changes in their tactics to avoid all the risks ', 'Fácil', 100, '{"width": 750, "height": 1334}', false, 'available'),
('Fruits merge Battle', 'embed', 'https://img.gamemonetize.com/jrxjv52jx0p40om03x77svr4yy7vw7wp/512x384.jpg', 'https://html5.gamemonetize.co/jrxjv52jx0p40om03x77svr4yy7vw7wp/', 'Welcome to Fruits Merge battle games! Hold and slide your finger to control your fruit. Collect identical and smaller fruits to upgrade your fruit hero. Can yo last till the last Fruit

Instruções: slide your finger or hold mouse click', 'Médio', 100, '{"width": 720, "height": 1280}', false, 'available'),
('Rebels Clash', 'embed', 'https://img.gamemonetize.com/ka7un4bgi85qnfjus78uvtmtq5lad0c3/512x384.jpg', 'https://html5.gamemonetize.co/ka7un4bgi85qnfjus78uvtmtq5lad0c3/', 'An uprising took place in the virtual city, the participants of which entered into a tough fight. Only the strongest can survive here, because there are absolutely no rules in this battle. Crash into a crowd of angry rebels in order to destroy the maximum number of them.

Instruções:  The mouse will allow you to aim and shoot at one of them ', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Impostor Farm Killer.io', 'embed', 'https://img.gamemonetize.com/cdu75mkagpz3ex9mmpbw96bdz883d9rh/512x384.jpg', 'https://html5.gamemonetize.co/cdu75mkagpz3ex9mmpbw96bdz883d9rh/', 'Get ready for an action-packed impostor game. Grow your family with the food found on the farm and challenge other players. You can give your character an advantage with different bonuses in Impostor Farm Killer, which is a fun .io game. You can improve your strategy with armor bonus, speed bonus and extra impostor bonus. Challenge all players by improving your character with daily bonuses, achievements and many surprises. Join the farm war now with 15 different characters.

Instruções: Use mouse or touch pad to play this game ', 'Fácil', 100, '{"width": 900, "height": 506}', false, 'available'),
('Death Car.io', 'embed', 'https://img.gamemonetize.com/lohjsihutqdu041wcrmfv552os69yjlf/512x384.jpg', 'https://html5.gamemonetize.co/lohjsihutqdu041wcrmfv552os69yjlf/', 'Do you like high speed, drifting and cool stunts while driving a car? Then you definitely should not miss the opportunity to become a member of this automotive madness. You can forget about restrictions and at the same time not worry about safety, because all the tricks will be performed in a virtual arena.

Instruções: Move your finger to broke other cars Hold your finger to make car more fast ', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('PLAY TIME Chicken.io', 'embed', 'https://img.gamemonetize.com/drgx9pmsts4kdch9smwistlxp0auex2c/512x384.jpg', 'https://html5.gamemonetize.co/drgx9pmsts4kdch9smwistlxp0auex2c/', 'Easy To play And hard to master ! Try To Collect the Higher Number Of the object to have the advantage on your opponent ! , Smash your opponent that seems to have less object than you to beat them , and escape the ones that seems to have higher number of object ! Super Addicitive Hyper casual game .

Instruções: mouse or arrow keys', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('The floor is lava! Balls ', 'embed', 'https://img.gamemonetize.com/h69r62st7pjtge53wvqguee776r2ud4o/512x384.jpg', 'https://html5.gamemonetize.co/h69r62st7pjtge53wvqguee776r2ud4o/', 'The floor is lava! Balls. A new puzzle platformer game. Sophisticated and complex levels will not let you get bored. Will test their control skills and tactics. In the game you will find: - Dozens of different levels - Sophisticated surface physics and ball weights - Variety of skins - Responsive controls All of this is available in the new game "Floor is Lava! Balls." Pass the hardest levels, unlock unique balloon skins. And try not to fall into the lava!

Instruções: In the game you have to guide the ball from the starting point to the end point Thanks to responsive controls to do this it s quite easy Gradually the difficulty will grow the design of towers will change With the passage of levels you earn local cu', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Tethan Arena', 'embed', 'https://img.gamemonetize.com/lvaw9m5z5wxn7v9ts6xz86zkxfx7t625/512x384.jpg', 'https://html5.gamemonetize.co/lvaw9m5z5wxn7v9ts6xz86zkxfx7t625/', 'Thetan Arena uses two different tokens, and players can earn both THC and THG tokens. The main in-game currency is the Thetan Coin (THC), which users gather by playing game modes and participating in various other activities. Once the player earns these THC tokens, they can claim them to their wallet

Instruções: Move your player kill your enemies ', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Sonic Hidden Diamonds Game', 'embed', 'https://img.gamemonetize.com/0cpm4j6be7hfomhe9u825elztpt542kd/512x384.jpg', 'https://html5.gamemonetize.co/0cpm4j6be7hfomhe9u825elztpt542kd/', 'Sonic Hidden Diamonds is a fun online skill and hidden object game. Find out the hidden diamonds in the specified images. Each level has 10 hidden diamonds. There are 8 levels in total. The time is limited so be fast and find all hidden objects before time runs out. Clicking in the wrong place several times reduces the time by an additional 5 seconds. So, if you are ready start the game and have fun!

Instruções: Use mouse or touch the screen to find the diamonds ', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Hungry Shark Arenak', 'embed', 'https://img.gamemonetize.com/q12mhrcqa7uqcjd27din347h60zmi60w/512x384.jpg', 'https://html5.gamemonetize.co/q12mhrcqa7uqcjd27din347h60zmi60w/', 'Hungry Shark Arena is the online multiplayer shark battle royale game that takes you on a vicious underwater war for supremacy. HUNT and GROW your shark to become the biggest predator in the sea. KILL other players and stay on top of the food chain. SURVIVE the dangers of a ruthless underwater arena.

Instruções: HUNT and GROW your shark to become the biggest predator in the sea KILL other players and stay on top of the food chain ', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Chicas Barbie', 'embed', 'https://img.gamemonetize.com/k8cvvvu4ezkf0i9t64br5qohu9xrlpce/512x384.jpg', 'https://html5.gamemonetize.co/k8cvvvu4ezkf0i9t64br5qohu9xrlpce/', 'A world just for barbie girls lots of emoticons and gifs entertaining social box chat with your friends and share your ideas in barbie girls.', 'Médio', 100, '{"width": 800, "height": 720}', false, 'available'),
('Barrel Wars', 'embed', 'https://img.gamemonetize.com/q15mejhcg5526s4bt4quatj223u8kbn1/512x384.jpg', 'https://html5.gamemonetize.co/q15mejhcg5526s4bt4quatj223u8kbn1/', 'Prepare for war with different barrels in Barrel Wars. Take a small hit so that the barrel does not break and you must swing your weapon accurately to destroy the enemy. Action-packed arena battles await you in the multiplayer Barrel Wars game. Thanks to daily and hourly bonuses, you will be able to earn money quickly and strengthen your character. If you want to gain an advantage over other players, you have to fight and win many battles. Upgrade your warrior with 16 different weapons with unique mechanics and 7 different barrel characters! Note that sometimes character power-ups can fail. Grab your gun now and join the barrel wars!

Instruções: Desktop W A S D or arrow keys or Mouse Mobile Touch', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Viking.io', 'embed', 'https://img.gamemonetize.com/i73egb6t8luubl6h6ljmacpi8dohga4w/512x384.jpg', 'https://html5.gamemonetize.co/i73egb6t8luubl6h6ljmacpi8dohga4w/', 'Viking.io is a great run and jump game. Run with you Viking faster you can jump over obstacles using your skills. Pick up beer to make your race longest

Instruções: use mouse or keyboard fingers', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Justin Bieber Tik Tok', 'embed', 'https://img.gamemonetize.com/ujf2zcfa43aiub68zh885pwc9ealomzi/512x384.jpg', 'https://html5.gamemonetize.co/ujf2zcfa43aiub68zh885pwc9ealomzi/', 'Are you a fan of Justin Bieber? tik tok games dance and sing playing justin bieber. Only fans for biliebers', 'Médio', 100, '{"width": 800, "height": 720}', false, 'available'),
('Transporters IO', 'embed', 'https://img.gamemonetize.com/sn6iubd8uf0c3wpeldimwrpz8ddjt9ku/512x384.jpg', 'https://html5.gamemonetize.co/sn6iubd8uf0c3wpeldimwrpz8ddjt9ku/', 'Go home for the new year, or celebrate the new year on the spot?', 'Difícil', 100, '{"width": 526, "height": 930}', false, 'available'),
('Princess on Run IO', 'embed', 'https://img.gamemonetize.com/s2ifkh61chtq9aj6tm29zq4eo7b2zyy5/512x384.jpg', 'https://html5.gamemonetize.co/s2ifkh61chtq9aj6tm29zq4eo7b2zyy5/', 'collecte fashionista collection.', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Real Car Parking : Driving Street', 'embed', 'https://img.gamemonetize.com/33umxbirp5yyrxqgxqxn54wh82mgvfzm/512x384.jpg', 'https://html5.gamemonetize.co/33umxbirp5yyrxqgxqxn54wh82mgvfzm/', 'Are you annoyed by all the similar parking games, and the lack of graphics and originality? Are you looking for a new car park to park your vehicle as much as you want? We know you''re here hoping to find a game that''s perfect for you.', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Ariana Grande Tik Tok', 'embed', 'https://img.gamemonetize.com/pu3r2i7wy70mq3qub4mumaduy8bfyk80/512x384.jpg', 'https://html5.gamemonetize.co/pu3r2i7wy70mq3qub4mumaduy8bfyk80/', 'have fun dancing with the most popular music of ariana grande and learn her most famous dances of tik tok', 'Difícil', 100, '{"width": 800, "height": 720}', false, 'available'),
('Birds to phoenix IO', 'embed', 'https://img.gamemonetize.com/23t9y96ikbbm42x5p3dvqr7458dwt9zn/512x384.jpg', 'https://html5.gamemonetize.co/23t9y96ikbbm42x5p3dvqr7458dwt9zn/', 'Tap the screen to string beads, and two beads of the same level will synthesize more advanced beads.', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Squid Hook Game', 'embed', 'https://img.gamemonetize.com/6gquwx25wy4uy4z56zk332i28tmndd0o/512x384.jpg', 'https://html5.gamemonetize.co/6gquwx25wy4uy4z56zk332i28tmndd0o/', 'In Squid Hook Game, pull the Squid Game character on the opposite side to your side with the rope. Take advantage by sending the rope accurately to the other side. You can buy 5 different Squid game characters by accumulating the points you will earn at the end of each game. You can increase the action by purchasing dolls, players and workers. Grab your hook and fight against other players! Have fun.

Instruções: Use mouse or touch pad to play this game ', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Do Not Fall.io', 'embed', 'https://img.gamemonetize.com/853bctozi7tb6yexowfbtjj3nx1jpxfz/512x384.jpg', 'https://html5.gamemonetize.co/853bctozi7tb6yexowfbtjj3nx1jpxfz/', 'You like fun arcades and endurance races? Like playing online with other players? Then welcome to Do Not Fall .io! Here you will find a lot of fun and a huge devastating arena! Your task is to stay as long as possible and not fall. But you''re not the only one in this arena. You have 20 enemies and you have to beat them all! To become a champion, you need to be the last one in the arena that''s always destroying right under your feet! Stay as long as you can and don''t fall! The rules have never been so simple: just jump on the platforms and don''t fall down. The one who fell – lost. The last survivor becomes the winner! Handle it?

Instruções: - Simple and fun game - Interesting gameplay', 'Difícil', 100, '{"width": 600, "height": 960}', false, 'available'),
('Merge Dragons', 'embed', 'https://img.gamemonetize.com/r85gwr5i23i5jpxa15s56pgfk9ngl8qn/512x384.jpg', 'https://html5.gamemonetize.co/r85gwr5i23i5jpxa15s56pgfk9ngl8qn/', 'Slide the screen to Control the character to eat low-level Creatures

Instruções: Control movement with mouse After the game is loaded click on the game interface to start the game Operate reasonably and successfully evolve into a dragon ', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Number Snake', 'embed', 'https://img.gamemonetize.com/1f1nc1ov0i4ft9uu58v5ja41t2pqe9yc/512x384.jpg', 'https://html5.gamemonetize.co/1f1nc1ov0i4ft9uu58v5ja41t2pqe9yc/', 'Swipe your finger to guide a snake of balls and break the bricks. With Number Snake Game, you can play this challenging game using your finger. The objective is to guide the snake of balls through a maze of obstacles, and break as many bricks as possible. There are different levels of difficulty that you can change at any time, so there''s always something new to try. Get additional balls and make the biggest snake ever! This fun and challenging game is easy to play but hard to reach high scores, so be sure to challenge yourself!

Instruções: Tap Drage', 'Médio', 100, '{"width": 480, "height": 854}', false, 'available'),
('Dots.io', 'embed', 'https://img.gamemonetize.com/luieuk312u2fyem7isdnwp8dl375cha8/512x384.jpg', 'https://html5.gamemonetize.co/luieuk312u2fyem7isdnwp8dl375cha8/', 'Dots.io is an amazing dots battle game. You will begin as a small grey Dot. Avoid Bigger Dots and try to eat small ones. Once you get bigger, you will find a lot of dots to eat, but be careful always from the bigger ones. Good luck

Instruções: Touch or hold click and slide to play', 'Difícil', 100, '{"width": 720, "height": 1280}', false, 'available'),
('Zumble Game', 'embed', 'https://img.gamemonetize.com/8pkcbi3sjidzt4yi63nbpencba792oqz/512x384.jpg', 'https://html5.gamemonetize.co/8pkcbi3sjidzt4yi63nbpencba792oqz/', 'Run a marble into the chain of colored balls and create a blast to eliminate them. We notice that Marble Game had the classic Marble Style Games but easily addictive. -Zumble Game ! Classic comes back! Fantastic designed puzzle game! One of the most classic and most fun game!', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Shortcut Race 3D!', 'embed', 'https://img.gamemonetize.com/8n1dyc1cai3o1r62f6xzgb7axr88gb7w/512x384.jpg', 'https://html5.gamemonetize.co/8n1dyc1cai3o1r62f6xzgb7axr88gb7w/', 'Race with opponents in and collect as much boards as you can along the track! As you build shortcuts, you''re going to start running faster. But the more you stack boards the more you slow down. Balance it well to outsmart your opponents. Let''s go!

Instruções: Touch and swipe to move', 'Médio', 100, '{"width": 480, "height": 864}', false, 'available');

