INSERT INTO games (title, type, image_url, game_url, description, difficulty, xp_reward, config, is_active, status) VALUES
('Pop it! Battle Royal', 'embed', 'https://img.gamemonetize.com/rq6oblzja0d2sj98lrf6d8v3vn6824tp/512x384.jpg', 'https://html5.gamemonetize.co/rq6oblzja0d2sj98lrf6d8v3vn6824tp/', 'Pop It! Battle Royal is a competitive version of Pop It! where you need to pop all the bubbles as fast as you can before the opponent''s in 3-round and 5-round matches to win new pop-its and status.

Instruções: PC Press the left mouse button to pop Mobile Tap the screen to pop', 'Difícil', 100, '{"width": 1280, "height": 720}', false, 'available'),
('Squid Game Hook', 'embed', 'https://img.gamemonetize.com/hsw9alys2q1dn3bpowx2se0b0bi6vngq/512x384.jpg', 'https://html5.gamemonetize.co/hsw9alys2q1dn3bpowx2se0b0bi6vngq/', 'Are you ready for Squid Game Hook as two teams? Throw the hook at the opposing player and pull the player towards you. If you make an accurate shot, you will score. You can buy 5 different Squid Game characters with the points you earn. You can increase the action with the players, workers and doll characters. Grab your hook now and fight against other players in Squid Game Hook! Have fun.

Instruções: Use mouse or touch pad to play this game ', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('MOTO Furious HD', 'embed', 'https://img.gamemonetize.com/p5xurnfmcr24hwa5fy7e56rfydm9u9xw/512x384.jpg', 'https://html5.gamemonetize.co/p5xurnfmcr24hwa5fy7e56rfydm9u9xw/', 'Start some Drag Racings on the Road with your Super Powerful Motorcycle and runaway from Police if necessary, it''s a very challenging moto game with a lot of levels and bikes to unlock!!!', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Disc Challenge', 'embed', 'https://img.gamemonetize.com/tvw5ddin06ma8z98t1f9gewzsag6lo7p/512x384.jpg', 'https://html5.gamemonetize.co/tvw5ddin06ma8z98t1f9gewzsag6lo7p/', 'Throw the disc and eliminate opponents defences. But be carefull... If he catches the disc, he will throw it back. This is the first time you’ll see a sling puck game like this on mobile and you are guaranteed to get hooked, this is the most addictive Slingpuck game on mobile! and the most fun sling experience you can get. There are a numerous amount of levels and players that will seek to destroy your trophies balance in their quest to get the highest rank possible.

Instruções: Throw the disc and eliminate opponents defences But be carefull ', 'Difícil', 100, '{"width": 600, "height": 960}', false, 'available'),
('Barbie Creator', 'embed', 'https://img.gamemonetize.com/ymrg3kagr8w72iqemaaumrw9aj3vuxu8/512x384.jpg', 'https://html5.gamemonetize.co/ymrg3kagr8w72iqemaaumrw9aj3vuxu8/', 'Create your own cute and special Barbie character! Dress up a cute character and save it as cute wallpaper on your device. You can design a Barbie doll in any style you like. Choose your favorite hairstyle for your Barbie doll and complete her look with kawaii eyes, eyebrows, and blush. Add accessories to match her outfit!

Instruções: Tap or click ', 'Fácil', 100, '{"width": 504, "height": 800}', false, 'available'),
('Elsa Dresser Decorate And Makeup', 'embed', 'https://img.gamemonetize.com/46u49y3hhncet8dz3pxns7acsuwuntjp/512x384.jpg', 'https://html5.gamemonetize.co/46u49y3hhncet8dz3pxns7acsuwuntjp/', 'Are you a lover of makeover games and dress-up games? Do you love ice princess games and ice queen games? Do you want to make up and dress up ice queen Elsa and help her decorate her dresser? Download Ice Queen Beauty Salon Game for Free and enjoy! If you''re addicted to ice queen Elsae''s games and make-up and makeover and dress-up games, you will love Ice Queen Beauty Salon Game. Elsa gets a new dresser, she wants to decorate it to make it looks beautiful. Elsa will try her make-up after she decorated her dresser, helping her to become a beautiful princess and snow queen.

Instruções: Tap or click ', 'Médio', 100, '{"width": 720, "height": 1280}', false, 'available'),
('Princess Eye Art Salon - Beauty Makeover Game', 'embed', 'https://img.gamemonetize.com/pq5lmx4a5gu2yo3rse9dinrt9d28uo8l/512x384.jpg', 'https://html5.gamemonetize.co/pq5lmx4a5gu2yo3rse9dinrt9d28uo8l/', 'Create your own exclusive eye makeup in Princess Eye Art Salon! You are the makeup artist, and all you have to do is move your fingers to create a variety of designs. You''ll get thousands of "Likes" from fans every time you finish a beautiful eye makeup. Additionally, as your talent and influence develop, more creative Eye Art becomes available.

Instruções: Tap or click ', 'Difícil', 100, '{"width": 504, "height": 800}', false, 'available'),
('Color Adventure: Draw and Go', 'embed', 'https://img.gamemonetize.com/twn8ysjlcaf0tlxksdzrj0x9opditwun/512x384.jpg', 'https://html5.gamemonetize.co/twn8ysjlcaf0tlxksdzrj0x9opditwun/', 'Color Adventure est à la fois un jeu de coloriage et d''entraînement cérébral ! Touchez le cube et maintenez pour colorier un chemin vers de nouveaux lieux et pays. Mais attention ! C''est moins simple que ça en a l''air !

Instruções: Click screen to start or stop the color cube ', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('TonkWars.io', 'embed', 'https://img.gamemonetize.com/s0hre8v0prilayb5c3zmj5iwkytnb12v/512x384.jpg', 'https://html5.gamemonetize.co/s0hre8v0prilayb5c3zmj5iwkytnb12v/', 'Tank Battle Multiplayer Game! Shoot other tanks, destroy terrain and collect powerups! Customize your tank with flags and hats.

Instruções: Mouse to move Click to shoot', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('DinosaurStorm.io', 'embed', 'https://img.gamemonetize.com/on67rzfjboqqzlo8tg6ta0zg2ppoy18t/512x384.jpg', 'https://html5.gamemonetize.co/on67rzfjboqqzlo8tg6ta0zg2ppoy18t/', 'This is a new era of the resurrection of dinosaurs! You are no longer a weak human being, but a strong dinosaur. Fierce competition is about to begin. Collect humans, destroy buildings, and collect gold coins to make yourself stronger, and then defeat other dinosaurs to win. Move your dinosaur with simple controls. Can you be the strongest?

Instruções: Slide to play ', 'Difícil', 100, '{"width": 750, "height": 1334}', false, 'available'),
('High School Princess Date Spa', 'embed', 'https://img.gamemonetize.com/rqe90jqv3twofx74ym5bol9f68l857gc/512x384.jpg', 'https://html5.gamemonetize.co/rqe90jqv3twofx74ym5bol9f68l857gc/', 'Play as a royal princess this fun high school themed design game. Get ready for romance and sweep Prince Charming off his feet! Start at the spa for a relaxing facial using all natural oils and scrubs. Wash, exfoliate and tone your skin. Trim your eyebrows and shape them into striking arches! Apply moisturizer to highlight your natural glow and get ready for a fun trip to the salon.

Instruções: How to Play - Tap to choose clothes and jewelry - Tap to select makeup - Swipe to apply cosmetics and use real spa tools ', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Red Light Green Light.io', 'embed', 'https://img.gamemonetize.com/lmpbomfgkaz5j2p7uvmryriby41s24rr/512x384.jpg', 'https://html5.gamemonetize.co/lmpbomfgkaz5j2p7uvmryriby41s24rr/', 'Red Light Green Light game, one of the most popular Squid Game games of recent times, is here with its .io version. Your goal in Red Light Green Light game is to complete the game simultaneously with players from all over the world. When the killer baby says the red light, you must stop, and when it says the green light, you must take action. You have to be both fast and careful to finish the game before other players. Squid Game Red Light Green Light.io game does not contain links.

Instruções: Use mouse or touchpad to play this game You can also use the W A S D or Arrow keys ', 'Médio', 100, '{"width": 900, "height": 506}', false, 'available'),
('Squid Game Muscle Run.io', 'embed', 'https://img.gamemonetize.com/77oz5lymty8hhgr3u0a72dr1yvrm06oh/512x384.jpg', 'https://html5.gamemonetize.co/77oz5lymty8hhgr3u0a72dr1yvrm06oh/', 'Meet Muscle Run.io, one of the new Squid Game games. In Squid Game Muscle Run.io, your character has to complete the challenging track in order to escape from the island. For this, you must strengthen your character by collecting the pink dumbbells on the ground. Complete the escape quickly by making wise choices as actions such as swimming, running, wall pushing will reduce your character''s strength. Play the action and exciting IO style Squid Game now! For more, you can visit meyagames.com.

Instruções: Use mouse or touch pad to play this game ', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('SnowWars.io', 'embed', 'https://img.gamemonetize.com/ul7xv2s953oifo0wwm3m8uula51fmzug/512x384.jpg', 'https://html5.gamemonetize.co/ul7xv2s953oifo0wwm3m8uula51fmzug/', 'Multiplayer game with snowmen and snowballs! Collect snow to grow, find power ups and throw snow balls at other players!

Instruções: Mouse to move Click to shoot', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Laser Over Load', 'embed', 'https://img.gamemonetize.com/5ojxwc3ln7q1qryc46cwh9e8gd27ij01/512x384.jpg', 'https://html5.gamemonetize.co/5ojxwc3ln7q1qryc46cwh9e8gd27ij01/', 'Laser Overload is the free Puzzle game from the makers of Connect. The goal is to connect energy sources with the batteries to recharge them.

Instruções: Features Free - The game is 100 free for everyone you can play the game without any payment Accessible - The difficulty is designed for everyone Special objectives are designed for veterans Can you collect all the stars without breakin', 'Médio', 100, '{"width": 640, "height": 960}', false, 'available'),
('Mini Shooters', 'embed', 'https://img.gamemonetize.com/eula2xrifftawyos28e9o6heiigzqdii/512x384.jpg', 'https://html5.gamemonetize.co/eula2xrifftawyos28e9o6heiigzqdii/', 'Mini Shooters is a fun 2D shooting game where you can equip multiple weapons and fight in a deathmatch gameplay.

Instruções: WASD or arrow keys to move Use mouse to aim Left mouse click to shoot Space to pick up weapon ', 'Difícil', 100, '{"width": 960, "height": 600}', false, 'available'),
('Squid Game 456', 'embed', 'https://img.gamemonetize.com/fj4gonhi4h0yp2eu7yjbz5xua6kncc5k/512x384.jpg', 'https://html5.gamemonetize.co/fj4gonhi4h0yp2eu7yjbz5xua6kncc5k/', 'Survival games are becoming a reality in the modern world. In case of victory, the best one gets a cash prize and recognition. Many mobile games have been created on the topic of survival, where each player tested fate, endurance, and their own health. There will be only one winner

Instruções: Level 1 - move when the green light stop when the red light Use a mouse or your finger to act move and jump ', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Princess Glitter Coloring - For Kids', 'embed', 'https://img.gamemonetize.com/jbv52bc73kinmvsrdsp28om8urebxkp7/512x384.jpg', 'https://html5.gamemonetize.co/jbv52bc73kinmvsrdsp28om8urebxkp7/', 'This game is designed for kids of all ages. Especially by girls, as they love to dress up and decorate princesses. It is absolutely a fun app and easy to use. It helps kids to explore their creative side and improves their hand-eye coordination. No Internet is required and can be used while traveling as well. It keeps kids busy for hours.

Instruções: Tap or click ', 'Médio', 100, '{"width": 504, "height": 800}', false, 'available'),
('Cute Pet Friends - Virtual Pet Care & Dress up', 'embed', 'https://img.gamemonetize.com/g9lpck9m3f7j0hqb67px0epo00jfh81u/512x384.jpg', 'https://html5.gamemonetize.co/g9lpck9m3f7j0hqb67px0epo00jfh81u/', 'Meet the cutest pet friends the Cat and the Dog! Feed, bath, style, and dress up your new virtual pets in this super fun kids game! Play and take care of two sweet virtual pets: cat Kiki and dog Fifi. Give a bubble bath, shower, clean up, brush fur, polish nails, and design the perfect outfits for your virtual pets. Build a house and design the sweetest home for them. A perfect game for kids who want to have a cat or a dog and love taking care of cute virtual pets!

Instruções: Tap or click ', 'Difícil', 100, '{"width": 800, "height": 504}', false, 'available'),
('Squid Game Online Multiplayer', 'embed', 'https://img.gamemonetize.com/f9kc49j4awgatd4pl3yfnns0bu0lcz4c/512x384.jpg', 'https://html5.gamemonetize.co/f9kc49j4awgatd4pl3yfnns0bu0lcz4c/', 'Do you want to play Squid Game red light green light online with other players? Run when the doll says green light, stop when it says red light. If you can''t stop, the doll will detect you and eliminate you from the game. Enjoy Squid Game with players in groups of 30 from around the world. Pay attention to the sound of the toy to get the best ranking. For more Squid Game games, visit maskedgames.com.

Instruções: Use mouse or touchpad to play this game You can also use the W A S D or Arrow keys ', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Crash of Cars.io', 'embed', 'https://img.gamemonetize.com/4bocqdammwg0qr0x5jhbz9m98g7e6wqq/512x384.jpg', 'https://html5.gamemonetize.co/4bocqdammwg0qr0x5jhbz9m98g7e6wqq/', 'Welcome to Crash of Cars.io, A new Car bumper io game. The goal is very simple, Collect as many Stars as you can. Avoid bumping into other cars without having a shield or freezing them. Try to unlock all worlds by collecting enough stars. Let''s begin!

Instruções: Tap left and right to control your car', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Icy Dress Up - Girls Games', 'embed', 'https://img.gamemonetize.com/cakzazpy1y2issafjjmqdjxvvyld76lr/512x384.jpg', 'https://html5.gamemonetize.co/cakzazpy1y2issafjjmqdjxvvyld76lr/', 'It’s a new sisters'' dressup & makeover game! Icy girls are going to princess fashion salon. They are always together and their favorite thing is – fashion! Changing clothes, doing hairstyle and makeup are the most exciting things for them! Since they are ice princesses, they trust only their own fashion designer and it is you! Although they are twins, they still like different types of clothes, so it’s your goal to dress twins the way that they’ll look harmoniously or the way you want.

Instruções: Accessories The frozen princess had left them so many different capes necklaces bracelets and hair decorations Now their outfit is almost done The final touch are pets It s not a surprise every princess love animals and nature So just like all pr', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Crowdy City.io', 'embed', 'https://img.gamemonetize.com/3yrlza468z3vsm3r4mv8v9bi7iv2p3tl/512x384.jpg', 'https://html5.gamemonetize.co/3yrlza468z3vsm3r4mv8v9bi7iv2p3tl/', 'Become the biggest crowd in town! Gather people accross the city and crush your opponents with your overwhelming leadership! Run and collect people and avoid Bigger Crowds. Let''s go!

Instruções: Tap and slide to control your crowd or mouse click', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Boxing Star', 'embed', 'https://img.gamemonetize.com/1ezhgct6uvwkgek03w6zdzindab7fb6x/512x384.jpg', 'https://html5.gamemonetize.co/1ezhgct6uvwkgek03w6zdzindab7fb6x/', 'Rise from the box underground to the championship and become a boxing star. Improve your skills with rewards to compete in better tournaments. Put your boxing gloves on and box like there’s no tomorrow. Defeat all your opponents in fights and collect all trophies.

Instruções: Win matches by knocking out your opponent Use various attacks blocking and movement to create your own strategy and form your own story Train your abilities to compete in better tournaments ', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Unblock Car : Unblock Parking Car', 'embed', 'https://img.gamemonetize.com/su0txbsso85riz9kd44ursyov5mzyfay/512x384.jpg', 'https://html5.gamemonetize.co/su0txbsso85riz9kd44ursyov5mzyfay/', 'Unblock Parking Car is simple and nice game. More than 3,000 puzzles

Instruções:  Need to move the yellow car to the exit Horizontal cars can be moved from side to side Vertical cars can be moved up and down use HINT solve puzzle ', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Climbing Stars', 'embed', 'https://img.gamemonetize.com/4bs6gabb5sv0760dcgbpzumaigmnjnlr/512x384.jpg', 'https://html5.gamemonetize.co/4bs6gabb5sv0760dcgbpzumaigmnjnlr/', 'Climb the highest and become the best climber. A sports casual game that can be enjoyed by anyone thanks to simple controls Play a round of Speed Climbing, an official Olympic sport, with various cute characters Climbing Stars is a game with simple controls that anyone can enjoy anywhere, any time Unlock various characters and accessories by playing and earning Trophies

Instruções:  Climbing hardcore mode Be a legend of quick brains and timing Infinite Climbing Mode See what the limits of your two fingers are Reach the highest point in the 10 areas and reach the stage of gods Online Climbing Battle Mode A', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Color Pin Circle - Addictive Pin Shooter Game', 'embed', 'https://img.gamemonetize.com/d1roztursplnl1xyu57hxsw7nc3449vc/512x384.jpg', 'https://html5.gamemonetize.co/d1roztursplnl1xyu57hxsw7nc3449vc/', 'Color Pin Circle Game is specially designed for teenagers. It is an addictive pin through the game. This game is divided into levels. The next level will be harder from before levels. In this color arrow pin change game, you have to through all pins in the moveable multiple color circles to pass the level. The circle visible by different shapes of colored games and gets complete the level. Color Pin Circle is an addictive Pin Shooter Game created based on new ideas, new logic for passing boring time. It also has some advantages for increasing knowledge of accuracy. To play the Color Pin Circle game, you must set the same color to the color wheel. Be careful because you will have to pay attention to the variety of colors and not hit the other balls.

Instruções: To play our Color Pin Circle game successfully follows below instruction to win the game - Tap to shoot pin - The Pin Circle will be moved left and right with different colors Shoot Color arrow pin targeting the same circle color -Be careful to shoo', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('HALLOWEEN PUZZLE - PUZZLE', 'embed', 'https://img.gamemonetize.com/8xk5a0b4li21n2xpieg8jjf92l4aacl5/512x384.jpg', 'https://html5.gamemonetize.co/8xk5a0b4li21n2xpieg8jjf92l4aacl5/', 'A relaxing jigsaw puzzle game full of Halloween themed images. Go through the levels and use different ways of finishing current level. Halloween themed jigsaw is here for you. 75 levels halloween themed user friendly various game modes

Instruções: Move jigsaw puzzles into pre-prepared spaces and use available bonuses to complete levels more efficiently Each level is visually unique and represents different levels of difficulty choose the appropriate setting of your skills ', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Squid Game.io', 'embed', 'https://img.gamemonetize.com/i896wo97b5kza5qllyq9zx59lqffjv1r/512x384.jpg', 'https://html5.gamemonetize.co/i896wo97b5kza5qllyq9zx59lqffjv1r/', 'Fight your opponents in the red light green light game in Squid Game.io. Stop when the doll says a red light and take action when it says a green light. You have to be careful and fast to be ahead of other players within the set time. If you move at a red light, you will be shot by soldiers and you will lose the game. Get ready for the excitement with Squid Game.io! Visit meyagames.com for more games.

Instruções: Use mouse or touchpad to play this game You can also use the W A S D or Arrow keys ', 'Fácil', 100, '{"width": 900, "height": 506}', false, 'available'),
('Eye Art - Perfect Makeup Artist', 'embed', 'https://img.gamemonetize.com/zuxynundphdkddsg8uuc20g02d5r7hi4/512x384.jpg', 'https://html5.gamemonetize.co/zuxynundphdkddsg8uuc20g02d5r7hi4/', 'Create imaginative makeup on the eyes! In Eye Art, you are the makeup artist, just move your fingers and make diverse types of styles. Every time you finish gorgeous eye makeup, you will receive thousands of “Likes” from fans. And with your skill and influence accumulated, more creative Eye Art will be unlocked.

Instruções: Tap or click', 'Médio', 100, '{"width": 504, "height": 800}', false, 'available'),
('Traffic Road', 'embed', 'https://img.gamemonetize.com/likgfoklgi84zg3stzta5wz1t1n89d39/512x384.jpg', 'https://html5.gamemonetize.co/likgfoklgi84zg3stzta5wz1t1n89d39/', 'Traffic road is the real traffic tour racing game that will lead you to another level of smooth racing city rush arcade. City traffic driving game is the latest cars racing game where you can experience the real feel of chasing and drifting through the streets of a real city rush. Show your driving skills in the city traffic jam situation by safely overtaking and smoothly crossing all the traffic in the car rush game. All you have to do is to avoid crashing and stay intact for as long as you can. Dodge the busy street cars in this traffic road car racing game.

Instruções: Drive your traffic vehicle carefully so that you may be able to complete your challenge and task in order to be car driving hero Download the traffic road car game and enjoy the real world city rush traffic ', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Impostor Adventure', 'embed', 'https://img.gamemonetize.com/r86vq91nxtpe149rbgluseheknez4fhk/512x384.jpg', 'https://html5.gamemonetize.co/r86vq91nxtpe149rbgluseheknez4fhk/', 'Do you think you can catch the impostor in the space crew fast? Don’t kid yourself! Your spaceship is now invaded by many kinds of traitors! Discover them all if you want to survive.

Instruções: - Use buttons to run jump and throwing knife explore the spaceship - Travel across dangerous room machinery base etc - Collect coins gold acceleration props to help you defeat the Monster and imposter ', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Model Fashion Stylist: Dress Up Games', 'embed', 'https://img.gamemonetize.com/1n10w3s6ynbf13zfa40b7dytgymt2v4x/512x384.jpg', 'https://html5.gamemonetize.co/1n10w3s6ynbf13zfa40b7dytgymt2v4x/', 'Let’s enter into a brand new world of fashion games for girls. It’s time to design very stylish international outfits for a more glamorous look of models to keep the style game high. Now become the fashion designer of the amazing fashion show and amaze everyone with your creativity. Go beyond your imaginations and enjoy this exciting free dress up games & makeover games for unlimited fun. Get ready to have a bundle of girl fashion enjoyment by designing international fashion dress up for stylish models. They need to look very amazing to beat this fashion race. Let’s use various jewelry items and design something wonderful for our fashionistas and enjoy this fun style dress up game for girls.

Instruções: The makeup of these international supermodels has to be perfect Experiment with different makeup looks on these divas try new shades of lipsticks cute blush-on and so much more in this free model dress up game for girls ', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Catwalk Beauty - Super Stylish', 'embed', 'https://img.gamemonetize.com/pr702ec2t91yhb1rwej8i0r2c2797aym/512x384.jpg', 'https://html5.gamemonetize.co/pr702ec2t91yhb1rwej8i0r2c2797aym/', 'Hey beautiful, it''s showtime! All the baddies are choosing the most beautiful outfits for the catwalk! Your goal is to rock the catwalk like a queen. Choose your best outfit pieces for the runway in order to beat your opponent! If you want to walk like a QUEEN, always choose the most chic attire! The better the outfit, the higher the scores—you''ll be chic and unbeatable! GAME FEATURE -Exquisite clothing! -Step up your style! -Dress up, glam up, and show them that you are a FASHIONISTA! -Delicate and charming characters! -100+ levels! Yaaaaas queen! You look fabulous! Fabulous girls always figure out how to walk with style! Beat your opponent and show the audience who''s queen of the catwalk!', 'Difícil', 100, '{"width": 720, "height": 1280}', false, 'available'),
('Wheelie Bike New', 'embed', 'https://img.gamemonetize.com/9b0bxr3ep410xxl6s8bkltgzix5gctne/512x384.jpg', 'https://html5.gamemonetize.co/9b0bxr3ep410xxl6s8bkltgzix5gctne/', 'Wheelie Bike New Recently, the stickman wants to enter the wheelie competition in the city. Now can you help him to master the stunt, the front wheel off the ground and keep moving? If he loses his balance or the front wheel touches the ground, the performance fails. Help him to develop his excellent balance and keep a unique posture forward. This is a game that you can''t stop at all! Enjoy playing with Wheelie Bike!', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('2D Car Runner', 'embed', 'https://img.gamemonetize.com/nvtgml1ch483zwor5s6vddkpwc4pga9y/512x384.jpg', 'https://html5.gamemonetize.co/nvtgml1ch483zwor5s6vddkpwc4pga9y/', 'Are you ready for an endless 2D drive? In this fun, but challenging game, drive as far as you can, and reach your best distance by avoiding obstacles and picking up gas. You''ll need to keep your car gassed up to keep going, and you''ll be challenged by the progressive speed of the game. You will love the challenge of this game, and the smooth game tune will keep you engaged for hours!

Instruções:  Smooth easy controls - Simple Left Right Touch Arrows Totally 2D - Nice clean graphics Gas can pickups to keep your fuel meter up Endless game play Great enjoyable game music to keep you in to the game ', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('SquidGame.io', 'embed', 'https://img.gamemonetize.com/j4drf322s2noxvmrvou4ed4j7a0h2ugv/512x384.jpg', 'https://html5.gamemonetize.co/j4drf322s2noxvmrvou4ed4j7a0h2ugv/', 'Squid Game multiplayer game! Collect gems to grow and hunt smaller players! Customize your character with hats and colors.

Instruções: Mouse to move Click to boost', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Neon Bike Race', 'embed', 'https://img.gamemonetize.com/cwg7sddmng0a6hxdpsz1ksjlp9a0p2s4/512x384.jpg', 'https://html5.gamemonetize.co/cwg7sddmng0a6hxdpsz1ksjlp9a0p2s4/', 'Neon Biker- New Bike Racing|| Real bike Stunt Game is the game of bike stunting and racing. in this bike stunt game You will perform various stunt in game like back flip front flip.In this bike racing game You will race your bike with time.This neon bike game Run fast & smothly in android device without any laging and running slowing.Its time to tighten your seat belt and speed through the ultimate challenging missions. Each level is more difficult and thrilling than the previous level.It is not easy to Perform some serious stunts and skills to the finish line really fast! If you fall down in the middle of level then you will be res pawned on your last checkpoint you have already pass through. your mind presence is the key to balance your tricky stunt bike and complete challengesThe tracks of this impossible game are arranged in a very tricky way to make the game play exciting. Here is the real challenge, for all bike stunt game lovers, to perform crazy stunts Stunt Moto bike is characterized by stunts involving acrobatic maneuvering of the motorcycle stunt bike and take rider in the light of the moon. Drive different category of Moto stunt bike like wheelies, stoppies, burnouts and sport bikes which make wonder downsizing bright stunt in impossible tracks.Start your engines, Hit the gas and get ready for a thrill! Hurl yourself into the world of bike stunt adventures and experience the thrill of real-life stunts. stunt on extreme tracks, rush over beautifully designed race tracks, smash over rocks, boosting really high jumps, score insane and extreme combo tricks, complete challenges to unlock new better bikes, try new gear to be rightfully. Play the amazing, mind-boggling, racing stunt game with others around the globe. You’ll get into a lot of bike stunt accidents so drive carefully.', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('INSTAGIRLS VALENTINES DRESS UP (DCMA)', 'embed', 'https://img.gamemonetize.com/rkc2pt7iniuzt2hc10ic93yueow1olx4/512x384.jpg', 'https://html5.gamemonetize.co/rkc2pt7iniuzt2hc10ic93yueow1olx4/', 'Valentines Day is here! So it''s time to pick the perfect outfit, take selfies and try to receive as many likes on social media as possible. Complete the hashtags for even more likes an spend them to buy new clothes. Try different combinations so you''ll look stunning for your valentines date!

Instruções: Pick your favorite outfit from your wardrobe Take a selfie and spend the likes you receive on new clothes ', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Magic Dream Tiles', 'embed', 'https://img.gamemonetize.com/e1vosihri4bmofcf0txjj72nkveoc1jf/512x384.jpg', 'https://html5.gamemonetize.co/e1vosihri4bmofcf0txjj72nkveoc1jf/', '"Magic Dream Tiles" is a perfect combination of great songs and great voices from the world''s top singers.

Instruções: - Play real music by pressing the black keys - Many HITS accompanied by beautiful voices and frequently updated - A variety of musical genres pop electro classical country etc ', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Real Riders', 'embed', 'https://img.gamemonetize.com/q2d7xh2mwmu73vltcfmefcocihw99d5c/512x384.jpg', 'https://html5.gamemonetize.co/q2d7xh2mwmu73vltcfmefcocihw99d5c/', 'Enjoy the best physics simulation on two wheels and the best graphics. Beat your friends'' best times in the dashboards. An indie game that will make you dream with impossible speeds.

Instruções: Designed for tablets and smartphones No internet connection required to play Completely free with no ads or in-app purchases Does not store or share private data ', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Zumble Classic', 'embed', 'https://img.gamemonetize.com/r79yx43ezbxpfkqsuett3hmlb9sirk3h/512x384.jpg', 'https://html5.gamemonetize.co/r79yx43ezbxpfkqsuett3hmlb9sirk3h/', 'As an explorer in the Zumble Classic there, there is only one going to be blocked by the marbles and your mission is shooting to blast all them. You have to complete all the levels in challenge mode, help frog marble defense in jungle marble and try to get three stars in each level.

Instruções: Zumba Deluxe highlighted features Marbles game has more interesting levels of a lot of different temple quest Freeze stone Rainbow stone Bombs and many interesting props waiting for your exploration in shooting marbles This game contains the g', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Hammer Flight', 'embed', 'https://img.gamemonetize.com/d5h3j5ru07n2rf8k28n28axvlur452io/512x384.jpg', 'https://html5.gamemonetize.co/d5h3j5ru07n2rf8k28n28axvlur452io/', 'Fight with different hammers in Hammer Flight. Try to take the least blow so that the barrel does not break. You must be careful in every blow you give to the enemy. Prepare for action-packed battles in the arena in the multiplayer Hammer Flight. With daily and hourly bonuses, you can make rapid progress with the money you will earn. In order to level up in the rank system, you must win all the battles. Always fight to gain an advantage over other players! You can improve your warrior with 16 different weapons with unique mechanics and 7 different barrels. You can also strengthen your character with character upgrades. Note that the upgrade can sometimes fail. Come on, grab your gun now and join the Hammer Flight battle.

Instruções: Mouse swipe or Touch', 'Difícil', 100, '{"width": 900, "height": 506}', false, 'available'),
('Spinner.io 2', 'embed', 'https://img.gamemonetize.com/ajpd85rnmnbm1461nstw3xoi4t8m3gpn/512x384.jpg', 'https://html5.gamemonetize.co/ajpd85rnmnbm1461nstw3xoi4t8m3gpn/', 'The most addictive .io! The faster you are, the harder you hit.

Instruções: Knock your opponents off to become bigger and stronger Be the last one to win ', 'Fácil', 100, '{"width": 1080, "height": 1920}', false, 'available'),
('Hoop Stars', 'embed', 'https://img.gamemonetize.com/8wl1o0fch6z6d1tz3ottmauzgoyufw1p/512x384.jpg', 'https://html5.gamemonetize.co/8wl1o0fch6z6d1tz3ottmauzgoyufw1p/', 'Dunk a lot! You have never played sport like this before! Feel the fun of true “reverse” basketball dribbling. Challenge the world and collect all the trophies!

Instruções: Dunk a lot You have never played sport like this before Feel the fun of true reverse basketball dribbling Challenge the world and collect all the trophies ', 'Médio', 100, '{"width": 1080, "height": 1920}', false, 'available'),
('Butterfly connect game', 'embed', 'https://img.gamemonetize.com/w3vsybnkvs03etzn3yr33ek6t9er6jby/512x384.jpg', 'https://html5.gamemonetize.co/w3vsybnkvs03etzn3yr33ek6t9er6jby/', 'Butterfly connect The simplest matching pair is when same-species butterflies are located next to each other. This can occur on the edge of the board or somewhere in the middle. Because they are easy to spot, I usually look for these simple pairs first, to help clear out the center of the board. An alternative strategy might be to save some of these obvious matches for later, when you might need some quick matches to pump up the timer.

Instruções: Onnect - Pair Matching Puzzle ONNECT Butterflies is a connection-based PAIR MATCHING GAME with challenging levels Find the matching Butterflies connect the pairs Butterfly with up to three lines Remove all tile pairs before the time is over ', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('BACK TO SCHOOL PRINCESS PREPPY STYLE', 'embed', 'https://img.gamemonetize.com/3ssmm4xk88mvbfmtlfcw5a4wdekyc478/512x384.jpg', 'https://html5.gamemonetize.co/3ssmm4xk88mvbfmtlfcw5a4wdekyc478/', 'Going back to school now is like returning after long summer holidays! Are you looking forward to come back to the desk, books and school friends? Or you’re OK to have this break in the middle of the year? Help princess to make the most fashionable outfits for the first day of school! Turn them to an “A” students!

Instruções: Use mouse to play and use in-game instructions ', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Impostor Farm', 'embed', 'https://img.gamemonetize.com/a0uolq0vwebjz8ck84quy72mabc2fbqw/512x384.jpg', 'https://html5.gamemonetize.co/a0uolq0vwebjz8ck84quy72mabc2fbqw/', 'A fun and action-packed Impostor game is here with the difference of meyagames. A fun adventure awaits you in Impostor Farm. Grow your family with the food found around the farm and gain an advantage over rival impostors. You can get stronger with armor bonus, speed bonus and extra impostor bonus. You can improve your characters with daily bonuses, achievements and many surprises. You can also improve your character from the shop menu with the coins you will earn at the end of each game. Try Impostor Farm game now with 15 different characters and developable character structure!

Instruções: Use mouse or touch pad to play this game ', 'Médio', 100, '{"width": 900, "height": 506}', false, 'available'),
('Gun Shooting Action', 'embed', 'https://img.gamemonetize.com/ah34n6bghn9198miqoevfshqk2ba31mr/512x384.jpg', 'https://html5.gamemonetize.co/ah34n6bghn9198miqoevfshqk2ba31mr/', 'Grab your gun and take out many different opponents. Tap to shoot! In Gunner game you must get as high as possible. Use your coins to buy better weapons and many different skins. Take a look at your blacklist and take out special enemies.

Instruções: Tap to shoot ', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Super Knife Blades.IO', 'embed', 'https://img.gamemonetize.com/7x04gpc56mt9piievjlobh2ir4lop2sj/512x384.jpg', 'https://html5.gamemonetize.co/7x04gpc56mt9piievjlobh2ir4lop2sj/', 'Pick up knives and wrap them around yourself to fight with other guys in the arena. Use both offensive and defensive modes to defeat your enemies smartly!

Instruções: Hold drag to move and attack enemies ', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available');



INSERT INTO games (title, type, image_url, game_url, description, difficulty, xp_reward, config, is_active, status) VALUES
('Shaun the Sheep - jump', 'embed', 'https://img.gamemonetize.com/kicn4itocn3kludk7fod8r0wi42755ly/512x384.jpg', 'https://html5.gamemonetize.co/kicn4itocn3kludk7fod8r0wi42755ly/', 'Help Shaun the Sheep run as far as you can, but be careful! He''s holding an egg in the spoon! Collect as many stars as you can by throwing the egg into the air. The stars will reward you points. If the egg, or chicken, drops you will lose a life, if you lose all three lives you have to start over.

Instruções: Use the arrow keys to move ', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('WormRoyale.io', 'embed', 'https://img.gamemonetize.com/rw9ru99r2jp7z9h7p6s89yhpuv7rkzec/512x384.jpg', 'https://html5.gamemonetize.co/rw9ru99r2jp7z9h7p6s89yhpuv7rkzec/', 'WormRoyale.io Battle Royale game with worms!

Instruções: Mouse to move Click to boost', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('TRAIN GAME IO', 'embed', 'https://img.gamemonetize.com/54qetjdjbb7smppmwzkfhs2nwelan2gc/512x384.jpg', 'https://html5.gamemonetize.co/54qetjdjbb7smppmwzkfhs2nwelan2gc/', 'Trains Game is slithering train game in 3d world. Become the grand training game by eating others and grow longer. Collect screws and toolbox to grow faster. Good Luck

Instruções: Click to boost on desktop Double tap to boost on mobile ', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Impostor Royal Solo Kill', 'embed', 'https://img.gamemonetize.com/qr1mj6w9rfx15mlyvkjov4urrnvpzegj/512x384.jpg', 'https://html5.gamemonetize.co/qr1mj6w9rfx15mlyvkjov4urrnvpzegj/', 'Prepare for a breathtaking Impostor battle. You have to be fast and agile in order to be the last survivor in the game that takes place in the space shuttle. Challenge other Impostors by getting some bonuses and weapons with the drops falling on certain areas with the parachute. Fight to be the last man on the ship by killing your enemies with a sword, gun or chainsaw! Customize your character with 4 different levels, 12 different Impostors and 15 different hats. You can make these customizations with the points you earn from the levels. Meyagames.com wishes you good games.

Instruções: Use mouse or touch pad or W A S D arrow keys and space to play this game ', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Impostor Hook', 'embed', 'https://img.gamemonetize.com/69nlxcjdlhn3gtgovtp2vo5dbk7sk5vg/512x384.jpg', 'https://html5.gamemonetize.co/69nlxcjdlhn3gtgovtp2vo5dbk7sk5vg/', 'In Impostor Hook game, you must use the hook chain to pull the enemies on the opposite side to our side. After guiding your character, it will automatically throw the chain and if the chain falls on the Impostor, you will score. If the other side imprison you with their chain, you will be punished for 2 seconds. You can unlock 15 different Impostor characters with the points you earn in the game. You can play all impostor games for free at meyagames.com.

Instruções: Use mouse or touch pad to play this game ', 'Difícil', 100, '{"width": 900, "height": 506}', false, 'available'),
('Ball Runner 3D', 'embed', 'https://img.gamemonetize.com/n41xldprammlvb8ew2hx10f0xlplvw2o/512x384.jpg', 'https://html5.gamemonetize.co/n41xldprammlvb8ew2hx10f0xlplvw2o/', 'Ball Runner 3D - TOP Trending game. You have to tap to roll the ball Avoid Obstacles, Reach Reach Destination

Instruções: Ball Runner 3D', 'Fácil', 100, '{"width": 600, "height": 960}', false, 'available'),
('Tank.IO', 'embed', 'https://img.gamemonetize.com/v7ikkrmb4l82w8ajy54jecmc403mwqps/512x384.jpg', 'https://html5.gamemonetize.co/v7ikkrmb4l82w8ajy54jecmc403mwqps/', 'Tanko io is a massively multiplayer online game created especially for fans of tank battles. The events unfold during the Second World War. Choose a side between the Soviet Union and the Nazis and go to the battlefield. You will be opposed not only by real players, but also by computer-controlled tankers. The battles are large-scale and very spectacular. To win, you need to destroy as many enemy tanks as possible, and your team must score more points than the enemy team.

Instruções: you need to destroy as many enemy tanks as possible ', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Princess High School Dress up', 'embed', 'https://img.gamemonetize.com/f1s4oh09wd5ng20w7j4khg4w25jh7d62/512x384.jpg', 'https://html5.gamemonetize.co/f1s4oh09wd5ng20w7j4khg4w25jh7d62/', 'In our collection of princess games we have today a new game called Princess High School Dress up, where you must prepare your favorite princess for a new day at high school, as a fashion adviser. All princess dress up games have a lot of clothes, but this time the princess fashion dresses must be some elegant high school clothes.

Instruções: The shoes must be on the same color with the uniform so be careful what you will choose for your princess doll dress up The school bag cannot miss for the first high school day and there are many bags so you can find what you like In all princess fa', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('PRINCESS STYLE VLOG OMG WEDDING', 'embed', 'https://img.gamemonetize.com/aplqmu0alry22ika7n3vgillm05msbza/512x384.jpg', 'https://html5.gamemonetize.co/aplqmu0alry22ika7n3vgillm05msbza/', 'The bells sing, dingdong, dingdong! Come share the sweetness and witness the romance come alive with an epic royal wedding! Planning a wedding is not easy. The princess could use some help getting everything ready for her big day. Work with fantastic cosmetics to give her a stunning makeup look. Style with tons of gorgeous dresses and accessories, or even create a design yourself to add a touch of bibbidi-bobbidi-boo. Take photos for the new couple and share the joy of this special occasion.

Instruções: - Show your talent at the design studio If you don t want to follow the trend make it Create designs to show your sense of fashion - Slay with stunning dance moves Dance to kick the fun up a notch Tap the buttons on the screen as fast as possibl', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Jewel Quest - Magic Match', 'embed', 'https://img.gamemonetize.com/jalwxxffvwx746yh9ts2tj75orl3hxjm/512x384.jpg', 'https://html5.gamemonetize.co/jalwxxffvwx746yh9ts2tj75orl3hxjm/', 'An addictive and exciting adventure puzzle game filled with colorful jewels and satisfying effects! Unlock thousands of levels, train your brain and become a jewel master!

Instruções: How to play - Match 3 or more jewels in a line to crush them - Match 4 jewels to create special rocket jewels They will blast all the jewels in a row or column ', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Shopping Mall Girl - Dress Up & Style Game', 'embed', 'https://img.gamemonetize.com/skt6ug2lnh5ahd0a2ipidt7c3nm6pcnn/512x384.jpg', 'https://html5.gamemonetize.co/skt6ug2lnh5ahd0a2ipidt7c3nm6pcnn/', 'If you like dress up games, you’ll LOVE this one. Shop till you drop in the coolest fashion shopping mall in town! Show off your style, you gorgeous girl! Tons of real-life fashion shopping mall activities! Dress up in the coolest new outfits & accessories with your very own personal shopper! Compete in style contests & vote for your favorite look! Strut the catwalk like a model! Dress up games are oh so fun!

Instruções: Get ready for a shopping spree like no other Whether your fashion style is sporty classy or urban chic this 3D shopping mall game has just what you re looking for Dress up in trendy shops like ZAZA Surf N Style with tons of hot outfits to choose fr', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Royal Girls - Princess Salon', 'embed', 'https://img.gamemonetize.com/d3u84rcb1toph9mrm6q3yqspz2dooat1/512x384.jpg', 'https://html5.gamemonetize.co/d3u84rcb1toph9mrm6q3yqspz2dooat1/', 'Princess Irene is waiting for you at the castle, join her and discover all the girly things you can do in this stylish princess game. Makeup, hair, dress up, you can do anything you want, the only limit is your creativity! Irene has an entire makeup salon for herself. Apply the products and create a makeup look worthy of our princess. Use a soft eyeshadow, a sharp liner and finish everything off with mascara and lip gloss. Spend as much time as you wish at the princess makeup salon!

Instruções: Girls don t miss out on the fun at the castle with princess Irene and her royal BFFs Try one of the most fabulous princess games with makeup hair and dress up Discover new friends and make lots of memories Enjoy Royal Girls Princess Salon and feel li', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Among Impostors', 'embed', 'https://img.gamemonetize.com/mswpu9cuzxq2r9woprw13tvinj5kwjvj/512x384.jpg', 'https://html5.gamemonetize.co/mswpu9cuzxq2r9woprw13tvinj5kwjvj/', 'In Among Impostors, you have to expand your team by eating the foods found around. In order to be stronger against your enemies, you can get stronger by taking the bonuses on the surface. If the number of your enemies is more than you, your enemies will become stronger by eating you. You can use the protective shield, speed shoes and impostor group bonus to collect the most Impostor. With the points you will earn at the end of the game, you can have new impostors or strengthen your existing character. You can play other impostor games for free at meyagames.com.

Instruções: Use mouse or touch pad to play this game ', 'Médio', 100, '{"width": 900, "height": 506}', false, 'available'),
('Weld It', 'embed', 'https://img.gamemonetize.com/u0nolj2voug1g8cxwpcd1a105r4z8ozq/512x384.jpg', 'https://html5.gamemonetize.co/u0nolj2voug1g8cxwpcd1a105r4z8ozq/', 'Weld It - is a simple game to test your hand-eye coordination. The game brings you into the world of welders. enjoy the best welding simulation game

Instruções: Weld It simulation game ', 'Difícil', 100, '{"width": 600, "height": 960}', false, 'available'),
('Snake Vs City', 'embed', 'https://img.gamemonetize.com/ukue341s8laj4bvi25x7j08krar961re/512x384.jpg', 'https://html5.gamemonetize.co/ukue341s8laj4bvi25x7j08krar961re/', 'Compete with other players. Grab items and grow them. Increase your snake to swallow objects larger in size. This game will entertain you and let you feel the competition.

Instruções: Mouse Only', 'Fácil', 100, '{"width": 560, "height": 800}', false, 'available'),
('Sheep Run', 'embed', 'https://img.gamemonetize.com/4la6b0cvfjfcjnr45y3hv524nvoqt5v2/512x384.jpg', 'https://html5.gamemonetize.co/4la6b0cvfjfcjnr45y3hv524nvoqt5v2/', 'Sheep Run in the mysterious forest path endlessly Move your character to run avoid obstacles in and collected coins.

Instruções: Sheep Run in the mysterious forest path endlessly boys childer', 'Médio', 100, '{"width": 600, "height": 960}', false, 'available'),
('3D Breakfast Prapare', 'embed', 'https://img.gamemonetize.com/3vgmoz9qrm7rvzc7vn5kmwlwjocohg4q/512x384.jpg', 'https://html5.gamemonetize.co/3vgmoz9qrm7rvzc7vn5kmwlwjocohg4q/', '3D Breakfast - Prepare your breakfast by yourself and test your cooking skills

Instruções: cooking skills', 'Difícil', 100, '{"width": 600, "height": 960}', false, 'available'),
('Rabbids Volcano Panicp', 'embed', 'https://img.gamemonetize.com/stungmgpx3eyvtvpx0gxgzrj2nq2idva/512x384.jpg', 'https://html5.gamemonetize.co/stungmgpx3eyvtvpx0gxgzrj2nq2idva/', 'Stay safe as long as you can and make your way on the collapsing floor before the other panicking Rabbids take you down with them!

Instruções: Stay safe as long as you can', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Assassins Creed Freerunners', 'embed', 'https://img.gamemonetize.com/j32l2nvvt86uqniieh33alhxvdhcnjo7/512x384.jpg', 'https://html5.gamemonetize.co/j32l2nvvt86uqniieh33alhxvdhcnjo7/', 'Appoint your most trusted Assassin and enter the animus with 7 other players, surpass the dangers and get to the extraction point first! Climb on roofs, jump on walls, use the environment and take an epic leap of faith to increase your synchronization and summon legendary characters from the entire Assassin’s Creed series.

Instruções: Climb on roofs jump on walls ', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Knife Vs Sword.io', 'embed', 'https://img.gamemonetize.com/0o8uv94rzdwgyzplx8tgosumry1e2xi3/512x384.jpg', 'https://html5.gamemonetize.co/0o8uv94rzdwgyzplx8tgosumry1e2xi3/', 'Welcome to the Knife Vs Sword.io. In this game, you will be a knight, gradually level up, and eventually become the world''s best knight hero. Upgrade powerful knife and sword will be easy game.

Instruções: Follow The Game Description ', 'Difícil', 100, '{"width": 750, "height": 1334}', false, 'available'),
('Trains.io 3D', 'embed', 'https://img.gamemonetize.com/ldnbpv3gygz9zzu71xvziaio8h76o3na/512x384.jpg', 'https://html5.gamemonetize.co/ldnbpv3gygz9zzu71xvziaio8h76o3na/', 'Trains.io 3D is slithering train game in 3d world. Become the grand trainin game by eating others and grow longer. Collect screws and toolboks to grow faster. Good Luck

Instruções: Click to boost on desktop Double tap to boost on mobile ', 'Fácil', 100, '{"width": 540, "height": 960}', false, 'available'),
('Dash & Boat', 'embed', 'https://img.gamemonetize.com/o7dn9z3lftuadr514rmoste1ohwwnuab/512x384.jpg', 'https://html5.gamemonetize.co/o7dn9z3lftuadr514rmoste1ohwwnuab/', 'Dash & Boat is a simple game to play but hard to clear the higher levels. Control the running boat and smash the boxes, wheels, drums placed on the way. Avoid striking the rocks else you end your life.

Instruções: Control the running boat and smash the boxes wheels drums placed on the way Avoid striking the rocks else you end your life ', 'Médio', 100, '{"width": 600, "height": 960}', false, 'available'),
('Top Motorcycle Bike Racing Game', 'embed', 'https://img.gamemonetize.com/0u2ao7hfqi6ewe78ss84d4yr6k3jqyir/512x384.jpg', 'https://html5.gamemonetize.co/0u2ao7hfqi6ewe78ss84d4yr6k3jqyir/', 'Motorcycle Bike Racing

Instruções: Motorcycle Bike Racing ', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Gotia.io', 'embed', 'https://img.gamemonetize.com/8lt2g0nfzyedkpig1jp3b9vag9gvfo7n/512x384.jpg', 'https://html5.gamemonetize.co/8lt2g0nfzyedkpig1jp3b9vag9gvfo7n/', 'Multiplayer battle with swords, horses and shields! Grow bigger and knock other players!

Instruções: Mouse to move Click to attack', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Wormo.io', 'embed', 'https://img.gamemonetize.com/on57ewcv2740i24fbnohytevjs523pcr/512x384.jpg', 'https://html5.gamemonetize.co/on57ewcv2740i24fbnohytevjs523pcr/', 'Worm game with shooting worms! Eat gems to grow longer. Shoot at other worms to give them a push!

Instruções: Mouse to move Click mouse to shoot Hold mouse to boost', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('circles colors', 'embed', 'https://img.gamemonetize.com/rtm3tgkbpc10r6lig8grd569a5yrswxk/512x384.jpg', 'https://html5.gamemonetize.co/rtm3tgkbpc10r6lig8grd569a5yrswxk/', 'are you ready to play best classic game for kid and family play now with your friends this game she have great graphics and nice sound and very easy to play . are you ready ?

Instruções: are you ready to play best classic game for kid and family play now with your friends this game she have great graphics and nice sound and very easy to play are you ready ', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Halloween coloring books', 'embed', 'https://img.gamemonetize.com/uj5bkxd38kp4vobl6xqke78f3l9jq68l/512x384.jpg', 'https://html5.gamemonetize.co/uj5bkxd38kp4vobl6xqke78f3l9jq68l/', 'Halloween coloring books game has a lot of success review and player this MONTH that significantly improves overall game performance, especially on mobile phones. To play the game just touch the screen buttons if you use a mobile device.

Instruções: Touche screen Controls', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Dogod.io', 'embed', 'https://img.gamemonetize.com/c0j7e7kzlqzc5jiw4gb9wqeskjj61m3e/512x384.jpg', 'https://html5.gamemonetize.co/c0j7e7kzlqzc5jiw4gb9wqeskjj61m3e/', 'Dogod is a multiplayer action game based on the concept of weapon evolution. Become the god of the dogs in this massive deathmatch arena. A PVP multiplayer game where you can unlock dozens of weapons, kill opponents, collect food to win scores and collect chests that will give you money. Unlock more than 50 cosmetics, skins, hats and pets. HOW TO PLAY MOUSE - Move your character LEFT CLICK - Boost STRATEGY Kill your opponents in this dog fight arena. Level up to improve your weapons and reach new best scores. Collect food, gain coins and unlock skins, accessories and pets with your money to become the God of the Dogs

Instruções: MOUSE - Move your character LEFT CLICK - Boost', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Bugs Bunny Coloring Book', 'embed', 'https://img.gamemonetize.com/mrvtmdanhysc530emq732r9lyvnyaviw/512x384.jpg', 'https://html5.gamemonetize.co/mrvtmdanhysc530emq732r9lyvnyaviw/', 'Are you a big fan of Warner Bros cartoons and you never want to miss any movies? Do you love the pretty outlooks of various animal characters of Looney Tunes series and always want to decorate Bugs Bunny - an anthropomorphic gray and white rabbit or hare who is famous for his flippant, insouciant personality - with your own imagination? Well,if your answer is yes, this book is designed for you. Several pages of this book illustrate all original and amazing portraits of Bugs Bunny,which will inspire you as you color.

Instruções: Mouse or tap to play ', 'Difícil', 100, '{"width": 1440, "height": 960}', false, 'available'),
('outlive.ai', 'embed', 'https://img.gamemonetize.com/a5pmug7dqwivx7gwvzy89oi82t6hib4s/512x384.jpg', 'https://html5.gamemonetize.co/a5pmug7dqwivx7gwvzy89oi82t6hib4s/', 'Hold on to your life against increasingly challenging AI in this incredibly fast-paced game.

Instruções: Arrow keys to move 1-3 for power-ups ', 'Fácil', 100, '{"width": 1920, "height": 1080}', false, 'available'),
('Space Rocket Star ', 'embed', 'https://img.gamemonetize.com/q8lpjgkoutamqutd8z1iydv67gvtuhql/512x384.jpg', 'https://html5.gamemonetize.co/q8lpjgkoutamqutd8z1iydv67gvtuhql/', 'Have you ever imagined that join airforce and save the space galaxy? Space Rocket Star Simple gameplay with efficient and easy to learn controls.

Instruções: Use Mouse To Play and Follow introduction', 'Médio', 100, '{"width": 720, "height": 458}', false, 'available'),
('PRINCESS COLLEGE BEAUTY CONTEST', 'embed', 'https://img.gamemonetize.com/ahsrpqpzx05abp7qbkazmyvrw02wcwwm/512x384.jpg', 'https://html5.gamemonetize.co/ahsrpqpzx05abp7qbkazmyvrw02wcwwm/', 'Join Jasmine Belle and Rapunzel in the new fashion challenge Princess College starts a new Beauty Contest and three BFFs are rivals now Help them all get ready for this event by creating an outstanding look for each princess You can change not only shoes dresses and jewelry but the whole makeup too Lets see which princess gets the prize

Instruções: - Choose one country to represent them - Go to the gym and get the increased fitness level - Clean up the stage in the miss world game - Decorate and arrange things on judge table - Give refreshing spa treatments to the contestant - Execute beau', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Panda Supermarket Manager', 'embed', 'https://img.gamemonetize.com/49ac9u1fhldpaezof5t9y4poc37t797c/512x384.jpg', 'https://html5.gamemonetize.co/49ac9u1fhldpaezof5t9y4poc37t797c/', 'Who doesn''t love pandas? It''s hard to refuse such a cute animal and that is why in this new game you are about to be conquered by a whole family of them. It''s seems like the family business is actually having and managing a supermarket which is pretty cool when you think about it. There are so many tasks you should accomplish that is the reason you need to start working right away. As a chef manager you''ve got the biggest responsibilities on you and that could be fine if you are an organised person. In this animal game you are going through 4 phases in order to finish the game, but to be able to move from one to another you must complete entirely each one of them. Begin with the cleaning part and make sure the place looks like a proper store where all the animal world could buy from. Wash the floors, remove the spider web and throw away the trash. The purchase step is just when you make the inventory and see what kinds of products are missing or rotten, so you can replace them to have a full grocery. You are also assigned to help at the billing process where you are just recording the products in your supermarket database and charge the clients for the stuff they buy. Don''t forget the clothing phase because a nice dressed up manager might impress the customers and also could help you in the sales. Add nice items and dress the panda in any style you like, also try to enjoy every step of this game while you become a good store manager.

Instruções: You might wanna see what kind of surprises this game prepared for you in the features area - Easy and free to play - Cool experience with pandas - Learning how to take care of a store and how to administrate it - Clean maintain obtain and k', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Golf Masters! 3', 'embed', 'https://img.gamemonetize.com/rk062667am3z2q9gm8twe35ek1bsx3mo/512x384.jpg', 'https://html5.gamemonetize.co/rk062667am3z2q9gm8twe35ek1bsx3mo/', 'Pass Levels Using Golf Ball!

Instruções: Make the Golf Ball Move by Clicking Anywhere on the Screen', 'Médio', 100, '{"width": 640, "height": 360}', false, 'available'),
('Flappy Dunk Shoot', 'embed', 'https://img.gamemonetize.com/3bluguo5w49s3ybpsd1u7h4jk7xmrtjv/512x384.jpg', 'https://html5.gamemonetize.co/3bluguo5w49s3ybpsd1u7h4jk7xmrtjv/', 'Flappy Dunk Shoot is amazing game with classic and customise Balls. Tap the screen to shoot rings. No more dunk, only swishes! Pass all hoops and try new challenges. Try to dunk hoops to make the challenge completed. This is the remix of these types of hopping ball shooting and flappy shoot with dunking fun. One shot, one dunk Shoot hoops and dunk in this bouncy flappy ball shoot game. To be in the ranking, don''t forget to share your score!

Instruções: How To Play Tap on the screen to flap and do not let the ball fall Continuously touch the screen to direct the ball through the hoops ', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Among Arena', 'embed', 'https://img.gamemonetize.com/szy2u5o29vwi1oe6ce7407ik0ujte0i7/512x384.jpg', 'https://html5.gamemonetize.co/szy2u5o29vwi1oe6ce7407ik0ujte0i7/', 'Multiplayer arena game with among us characters! Collect wires and grow, avoid bigger players and hunt smaller players. Customize your character with many colors and hats!

Instruções: Move mouse to steer Hold mouse button to boost', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Dentist Games Inc: Dental Care Free Doctor Games', 'embed', 'https://img.gamemonetize.com/snh17nc629i8y954lwrqpb2flt5phyy9/512x384.jpg', 'https://html5.gamemonetize.co/snh17nc629i8y954lwrqpb2flt5phyy9/', 'Welcome to the virtual dentist hospital free doctor games ! The real dentist free games in market. Best doctor simulator dentist games you have a chance to help your dental surgery games patients to prove that you are a super dentist surgeon in dentist games, real virtual surgery simulator games and make them healthy again and put a smile back on their faces with this simulator games real offline games here. top Doctor games like dentist hospital surgery simulator games er emergency free dentist games.

Instruções: Best Dentist Hospital Game Features - Help your patients by performing realistic dentist surgeries - Clean the oral cavity for your patients for feel happy - Extract bad cavity teeth and fix with goods ones - Put on color and stamp o', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Golf Masters! 2', 'embed', 'https://img.gamemonetize.com/muk5seoqebmx91r4tza8j03nizgyq2uc/512x384.jpg', 'https://html5.gamemonetize.co/muk5seoqebmx91r4tza8j03nizgyq2uc/', 'Pass Levels Using Golf Ball!

Instruções: Make the Golf Ball Move by Clicking Anywhere on the Screen', 'Difícil', 100, '{"width": 640, "height": 360}', false, 'available'),
('IMPOSTOR RESCUE', 'embed', 'https://img.gamemonetize.com/dz3c2nfta6wqqr3uhh6fboeaiv1uo2a1/512x384.jpg', 'https://html5.gamemonetize.co/dz3c2nfta6wqqr3uhh6fboeaiv1uo2a1/', 'Impostor Rescue is a challenging puzzle game, where you need to collect all the treasures, rescue the hero and overcome impostors. In space, you are alone and helpless. You must use your wisdom to eliminate other crew members, get treasures, and survive! Easy and addictive gameplay; Many challenging puzzles and unique levels; Find out how to pull the pin; Use your brain to save the hero; Not time & life limited, enjoy yourself.

Instruções: you need to collect all the treasures rescue the hero and overcome impostors ', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('ONET FRUIT CLASSIC', 'embed', 'https://img.gamemonetize.com/1g1ah0hdd8se5mv99bovgwheby35tl7u/512x384.jpg', 'https://html5.gamemonetize.co/1g1ah0hdd8se5mv99bovgwheby35tl7u/', 'Onet Fruit Classic is a fun and relaxing pair puzzle solving game.

Instruções:  The goal of the game Onet Fruit Classic is to remove all tiles from the board by matching pairs of identical tiles Match tiles with the same fruit and they will disappear ', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('WATER FLOW', 'embed', 'https://img.gamemonetize.com/hhnbpg76uvlj0v25b7q8l9tlcrpnbfvt/512x384.jpg', 'https://html5.gamemonetize.co/hhnbpg76uvlj0v25b7q8l9tlcrpnbfvt/', 'Extremely easy to play yet not that easy to give up.Adjust pins by pulling or dragging them.Make your way trough pipes.If you''ve been looking for a pull the pin puzzle game for a long time, it''s time to explore it.

Instruções: Adjust pins by pulling or dragging them Make your way trough pipes ', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Draw Climbing Dash', 'embed', 'https://img.gamemonetize.com/dav0mou031wu2m4pld5w2qrbifnnnys0/512x384.jpg', 'https://html5.gamemonetize.co/dav0mou031wu2m4pld5w2qrbifnnnys0/', 'Draw anywhere on the screen, any size you want to create legs and run. Draw specific legs for each obstacle you find in the obstacle course. Draw unique shapes for each challenge you face in the race. Each set of legs you draw should be able to handle the obstacles.

Instruções: Draw your legs to win the race ', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Moto X3M Pool Party Game', 'embed', 'https://img.gamemonetize.com/slvjrof0k26tnd4q5vxuq3idik11tn8l/512x384.jpg', 'https://html5.gamemonetize.co/slvjrof0k26tnd4q5vxuq3idik11tn8l/', 'Moto XM is an ultimate online bike racing game which is very suitable for players who love extreme sports With the different levels in challenges the extremely dangerous but no less attractive high speed the game will blow you away with its exciting features It can help you to have interesting relax time Welcome to the special Pool Party version of this awesome bike stunt game Have fun with Moto XM Pool Party', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Social Media Snake', 'embed', 'https://img.gamemonetize.com/uyuen8pbknyxbmua88sg22pxe3zft2dn/512x384.jpg', 'https://html5.gamemonetize.co/uyuen8pbknyxbmua88sg22pxe3zft2dn/', 'Social Media Snake is a fun snake game with multiple customizations.

Instruções: Tap to play', 'Difícil', 100, '{"width": 960, "height": 600}', false, 'available'),
('Sunset Bike Racer - Motocross Game', 'embed', 'https://img.gamemonetize.com/u9hj2yjkvs8olk7vg4q8gthe98myv56p/512x384.jpg', 'https://html5.gamemonetize.co/u9hj2yjkvs8olk7vg4q8gthe98myv56p/', 'What better way to celebrate the holidays than with tons of death-defying stunts? Jump on this bike and get ready to dodge gigantic saw blades while you blast your way across a winter wonderland. Can you make it across each finish line without crashing into a dozen boxes of TNT or some other totally insane hazards? This crazy, wintertime racing game could keep you busy until spring or even beyond!', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Penalty Shootout EURO football', 'embed', 'https://img.gamemonetize.com/9rvd6jy9flhryta2la1uhd8zh5vrn6aw/512x384.jpg', 'https://html5.gamemonetize.co/9rvd6jy9flhryta2la1uhd8zh5vrn6aw/', 'This free penalty shootout game, from FlashFooty''s factory of fantasy football (and other sports) games, brings you the fever of the European championship. Choose your favorite football nation, grab that trophy and become the hero. The stadium is full and everybody''s eager to see who will win the dramatic penalty kicks show. In order to shoot, click anywhere to determine direction, height and strength of the shot. With combination of these, you can perform powerful kicks, but also gentle lob shots. In the role of goalkeeper, watch out for the target which will appear on your goal just before the opponent''s kick, and tap on it.

Instruções: The competition has two parts - group and knockout phase To qualify for the 1 8 finals you need to be either 1st or 2nd in your group After that no mistakes are allowed if you want to win the Euro cup You consider yourself football games fan Th', 'Médio', 100, '{"width": 900, "height": 500}', false, 'available'),
('Slither Rocket.io', 'embed', 'https://img.gamemonetize.com/zg48vg3fww7bfoc825g06scyozvwdp9d/512x384.jpg', 'https://html5.gamemonetize.co/zg48vg3fww7bfoc825g06scyozvwdp9d/', 'you have a chance to win even if you''re tiny. You can swerve in front of a much larger player to defeat them, no matter how big you are!

Instruções: start slithering Good luck ', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Stock Car Racing', 'embed', 'https://img.gamemonetize.com/1w6coppqgr7sdpn9esapoqrezqbcaizc/512x384.jpg', 'https://html5.gamemonetize.co/1w6coppqgr7sdpn9esapoqrezqbcaizc/', 'Drivers start your engines! Professional oval track racing that explodes with stock car racing action! RACE MODES : Multiplayer - Race head to head against other players in realtime. Regulation - Race and set the difficulty for higher prizes. Ladder - Race 10 laps against progressively faster opponents for increasing prizes. Endurance - Race the full 400 lap distance. Hot Lap - Set your fastest single lap on the leaderboard! Practice - Practice racing lines and setup your car for race trim.

Instruções: EXPERIENCE THE SPEED Feel your car on the absolute limit of adhesion around 1 to 4 mile banked oval tracks Earn in-game cash to buy upgrade repair and adjust your Stock Car Qualify to unlock new tracks for increasing prize money ', 'Fácil', 100, '{"width": 800, "height": 450}', false, 'available'),
('BattleDudes.io', 'embed', 'https://img.gamemonetize.com/qaf7ryh54m4k9j3e0jhf3z45rzuyugql/512x384.jpg', 'https://html5.gamemonetize.co/qaf7ryh54m4k9j3e0jhf3z45rzuyugql/', 'Battledudes.io is a real multiplayer 2d shooter game with a fully destructible map, where you fight other teams and players for the victory! The game has multiple distinct maps and multiple gamemodes for you to choose from, with many map and gamemode combinations. To aid you in fighting the enemies at your arsenal you have over 20 different weapons that you can unlock by playing the game and gaining XP points. Battledudes.io includes a leaderboard with daily, weekly and all time statistics. If you create an account to save your XP, progress you can also compete with other in the leaderboards. In the games show you can purchase new hats and emotes with either the coins currency or the gems currency. Coins are earned by playing the game and gaining XP. Gems can be purchased from the store. Each currency can buy a certain set of items.

Instruções: W A S D - move R - reload E - enter car Left mouse click - shoot Right mouse click - show emote Mouse wheel or 1 2 3 4 - switch weapons Controls can be changed in the settings menu ', 'Médio', 100, '{"width": 1920, "height": 1080}', false, 'available'),
('Tireur  - Sniper Shot', 'embed', 'https://img.gamemonetize.com/75g2u1gu8r0x7qhm3la2v661ahgxe22m/512x384.jpg', 'https://html5.gamemonetize.co/75g2u1gu8r0x7qhm3la2v661ahgxe22m/', 'Skeet shooting is a recreational and competitive activity where participants, using shotguns, attempt to break mechanically projected clay targets in the air from two fixed high-speed stations from various angles. Use your left finger to control shotguns to try to break clay targets. You must be a high-precision skeet shooter to eliminate all targets.

Instruções: Skeet shooting is a recreational and competitive activity where participants using shotguns attempt to break mechanically projected clay targets in the air from two fixed high-speed stations from various angles Use your left finger to control ', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available');

