INSERT INTO games (title, type, image_url, game_url, description, difficulty, xp_reward, config, is_active, status) VALUES
('Annoying Boss Game', 'embed', 'https://img.gamemonetize.com/rsdggmqp6nyh80aol8cjwy6kw3k7m9w7/512x384.jpg', 'https://html5.gamemonetize.co/rsdggmqp6nyh80aol8cjwy6kw3k7m9w7/', 'Step into the craziest office stress-relief adventure with Annoying Boss Punch Game! Smash, slap, punch, and kick your annoying boss in this hilarious web action game built for pure fun and endless entertainment. Tired of boring meetings, overtime pressure, and nonstop office lectures? Release your stress with crazy reactions, funny animations, and chaotic office destruction. Throw punches, launch flying chappals, smash eggs, use water balloons, and create total office madness. Enjoy smooth controls, addictive gameplay, and exciting power-ups that keep every level fun and fresh.

Instruções: Controls Mouse Controls bull Left Click to Punch bull Click Rapidly for Combo Attacks bull Drag Mouse to Aim Special Attacks Keyboard Controls bull Arrow Keys ndash Move Around bull Spacebar ndash Powerful Punch bull E Key ndash Use Sp', 'Fácil', 100, '{"width": 1920, "height": 1080}', false, 'available'),
('Castle Wars: Legacy', 'embed', 'https://img.gamemonetize.com/f6ung9e7lfninu1957spejeihzprdusb/512x384.jpg', 'https://html5.gamemonetize.co/f6ung9e7lfninu1957spejeihzprdusb/', 'Castle Wars: Legacy is a tactical multiplayer card game where you build your deck, defend your castle, and break through enemy walls. Stack resources, summon armies, cast spells, and outsmart your opponent in fast-paced strategic duels. Battle friends online, climb daily tournaments, conquer the campaign, or fight AI in quick matches. Collect dozens of unique cards, build custom decks, and unlock new castle skins. Easy to learn, deep to master.

Instruções: Click or tap', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Feather Dash', 'embed', 'https://img.gamemonetize.com/3c32sxuv2xg4x1t6rd9eft6j0z73uhku/512x384.jpg', 'https://html5.gamemonetize.co/3c32sxuv2xg4x1t6rd9eft6j0z73uhku/', 'Feather Dash - The ultimate bird-flying adventure! GAME MODES: Classic - Endless gameplay FEATURES: Smooth, responsive controls Colorful bird skins to unlock Earn coins and unlock cosmetics Mobile &amp; desktop optimized Atmospheric background music GAMEPLAY: Simple tap-to-jump mechanics with progressive difficulty. Avoid pipes, collect coins, and beat your personal best! Perfect for casual gaming sessions. No ads during gameplay!

Instruções: DESKTOP Click your mouse to jump MOBILE Tap the screen to jump KEYBOARD Press Spacebar to jump', 'Difícil', 100, '{"width": 1280, "height": 720}', false, 'available'),
('Idle Blocks Tycoon', 'embed', 'https://img.gamemonetize.com/tqjwr9k20es2xgcky9ct9m8t65qxdbj2/512x384.jpg', 'https://html5.gamemonetize.co/tqjwr9k20es2xgcky9ct9m8t65qxdbj2/', 'Idle Blocks Tycoon is a fun idle tycoon game where you upgrade your mine, mine more exciting ores and get rich in the process! Start with a humble character and a small patch of grass, then dig your way through layers of increasingly valuable ores. Upgrade your mining speed, unlock powerful auto-miners, and expand your operation from a tiny dig site into a massive empire.

Instruções: Desktop Scroll to zoom Right click to pan camera Click to unlock features Mobile Pinch to zoom and rotate', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Crazy Lumberjack: Cut Them All', 'embed', 'https://img.gamemonetize.com/3z3sbbpqn85ujl25j6d9i9meqz7ukpvv/512x384.jpg', 'https://html5.gamemonetize.co/3z3sbbpqn85ujl25j6d9i9meqz7ukpvv/', 'What could be better than starting your morning by cutting down a whole clearing of trees and sending them off for processing? Play as a lumberjack on a tractor, chopping down different kinds of trees one by one, from firs to palms. Advance through levels, upgrade your tractor&rsquo;s saws, trunk capacity, and speed, and compete against other players!

Instruções: Use your mouse or finger to control the tractor and cut down trees You can switch to collecting mode to gather firewood Sell the wood and upgrade your tractor as you go ', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Block Blast Puzzle', 'embed', 'https://img.gamemonetize.com/fx0o3r69oqzzat8ha5lvjmkdxjlmztxy/512x384.jpg', 'https://html5.gamemonetize.co/fx0o3r69oqzzat8ha5lvjmkdxjlmztxy/', 'Block Blast Puzzle is a fun and addictive puzzle game where you drag and drop colorful blocks onto a grid. Clear rows and columns by filling them completely to earn points. Plan your moves carefully &mdash; if theres no space left for the remaining blocks, the game is over!

Instruções: PC Controls Mouse Click Drag mdash Pick up a block and drag it onto the grid Mouse Release mdash Drop the block into position Mobile Controls Touch Drag mdash Press and hold a block then drag it onto the grid Release mdash Drop the block int', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('I Show Running 2D', 'embed', 'https://img.gamemonetize.com/mkw9z8qtebcmr2s5casktrd4gsodhqmg/512x384.jpg', 'https://html5.gamemonetize.co/mkw9z8qtebcmr2s5casktrd4gsodhqmg/', 'Run. Dodge. Go full speed. Welcome to IShow Running 2D, a fast-paced endless runner where reaction time is everything. Sprint down a high-energy running track, dodge insane obstacles, jump hurdles, slide under barriers, and keep moving as the speed keeps rising.

Instruções: Tap click or SPACE on Keyboard', 'Fácil', 100, '{"width": 1280, "height": 720}', false, 'available'),
('Quiz Runner.io', 'embed', 'https://img.gamemonetize.com/o265mdiouhnx82t87q3p0t5jgspwsdoy/512x384.jpg', 'https://html5.gamemonetize.co/o265mdiouhnx82t87q3p0t5jgspwsdoy/', 'Quiz Runner.io &ndash; Trivia &amp; Multiplayer Quiz Battle Think fast, play smart, and rule the leaderboard in Quiz Runner.io, the ultimate online quiz game! Enjoy solo quiz mode to improve knowledge, custom quizzes to test your favorite topics, or upload your notes and PDFs to play interactive learning games. Join real-time multiplayer quiz battles, friend duels, and tournaments to compete globally. Track progress with levels, achievements, and power-ups. With daily quiz challenges, fast-paced timed games, smooth addictive gameplay, and support for 12+ languages, Quiz Runner.io is perfect for students, teachers, and trivia lovers worldwide!

Instruções: W rarr Move Forward A rarr Move Left D rarr Move Right Double Left-Click Mouse rarr Move left or right', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Lifebuoy Planing', 'embed', 'https://img.gamemonetize.com/2pknxcw969p6jbs0ui0jm42dgr5mtd6x/512x384.jpg', 'https://html5.gamemonetize.co/2pknxcw969p6jbs0ui0jm42dgr5mtd6x/', 'Lifebuoy Planing is an arcade-style action game where you become a flying lifebuoy. You slide through fast, twisting slides, build speed, and launch into open water at the end. Momentum, angles, and timing decide how far and how well you fly across the waves. Perform daring launches, avoid obstacles, and master each slide&rsquo;s layout. Simple controls meet skill-based physics, creating satisfying runs that reward precision, speed, and perfect launches every time. Push limits, chase distance records, and refine every run.

Instruções: Mouse click or tap to play', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Trishift', 'embed', 'https://img.gamemonetize.com/pki5oeqfqj1sjufc9l2zz1rrwzlmwvve/512x384.jpg', 'https://html5.gamemonetize.co/pki5oeqfqj1sjufc9l2zz1rrwzlmwvve/', 'About the Game Shiftrix is a fast-paced action survival game where players switch between different shapes to survive enemy waves. Each shape has a unique ability, and choosing the right shape at the right time is the key to winning. The game focuses on reflexes, decision-making, and timing, making every fight intense and rewarding. Characters / Shapes You control one character that can shift into three forms: Circle (Speed Form) Square (Defense Form) Triangle (Damage Form) Game Modes Survival Mode &ndash; Endless waves with increasing difficulty Escape Mode &ndash; High-speed survival with time pressure and special abilities

Instruções:  Controls Keyboard PC W A S D Arrow Keys ndash Move Q ndash Circle Speed E ndash Square Defense R ndash Triangle Damage Space ndash Ultimate Ability Shift ndash Dash if unlocked Q ndash Shield if unlocked E Hold ndash Slow ', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Brainrot Evolution Arena', 'embed', 'https://img.gamemonetize.com/cumcmfbhvmb3yvzxrwygcayr5pjy0b52/512x384.jpg', 'https://html5.gamemonetize.co/cumcmfbhvmb3yvzxrwygcayr5pjy0b52/', 'Play an addictive evolution game where you control an Italian Brainrot creature in a fast-paced arena. Walk around, eat food to gain experience, and grow bigger with every level. As you evolve, your creature becomes stronger, faster, and more chaotic. Eat weaker Brainrot creatures instantly, avoid stronger enemies, and survive as long as possible. There are no complex attacks &mdash; victory depends on movement, positioning, and level advantage. Short sessions, simple mechanics, and constant action make this eat-and-grow Brainrot game highly replayable and perfect for quick fun.

Instruções: PC WSAD MOVE MOBILE JOYSTICK MOVE', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Tile Connect Pair Match Puzzle', 'embed', 'https://img.gamemonetize.com/t0o4lkpj4iehz9nu4r7bhx41y4mjq1d8/512x384.jpg', 'https://html5.gamemonetize.co/t0o4lkpj4iehz9nu4r7bhx41y4mjq1d8/', 'Match &amp; connect tiles of same color &amp; be the master of pair matching puzzle game. In this you have to find and match the same objects. There are different objects.

Instruções: Match The things to complete the game Click on same objects to match them ', 'Difícil', 100, '{"width": 960, "height": 600}', false, 'available'),
('Fish Super IO Eating', 'embed', 'https://img.gamemonetize.com/boeaw04eduubp8cjsl4umvc3yw4omaro/512x384.jpg', 'https://html5.gamemonetize.co/boeaw04eduubp8cjsl4umvc3yw4omaro/', 'Welcome to an exciting underwater world! In this 2D game, you begin your journey as a small fish, exploring the depths of the ocean and feeding on smaller fish to grow. With each level, your fish becomes bigger, unlocking new opportunities &mdash; hunt larger prey and dominate the underwater world. Enjoy unique levels, dynamic gameplay, and engaging mechanics. Play, grow, and become the true king of the ocean!

Instruções: PC Controls The fish moves relative to the mouse position from the center of the screen bull Space or Left Mouse Button LMB mdash boost speed up Mobile Controls The fish is controlled using a standard virtual joystick bull Tap the lightning i', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Dinosaur Evolution IO', 'embed', 'https://img.gamemonetize.com/ykl7foe8q8olus573dq1zubicm5rbbz2/512x384.jpg', 'https://html5.gamemonetize.co/ykl7foe8q8olus573dq1zubicm5rbbz2/', 'Grow your dragon and take it to the peak of evolution! Eat fruits, defeat other players, and become the most powerful creature in this world. Choose your playstyle &mdash; will you be a fast and aggressive hunter, or a careful strategist who defends their territory? Dive into an exciting growth and evolution journey, upgrade your dragon&rsquo;s abilities, and adapt to a constantly changing world. Explore new areas and become a true legend among dragons! Features: &bull; Eat, fight, and survive in fast-paced battles &bull; Evolve and reach new stages of evolution &bull; Unlock and explore new territories &bull; Become the strongest dragon in the game!

Instruções: On PC bull WASD mdash movement control On mobile bull Swipe on the screen mdash movement', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Snake 2048: Cube Merge', 'embed', 'https://img.gamemonetize.com/nkjtibnj0tezzvci3owaf2dtff3hvfvq/512x384.jpg', 'https://html5.gamemonetize.co/nkjtibnj0tezzvci3owaf2dtff3hvfvq/', 'This game is an exciting combination of the classic Snake mechanics and the popular 2048 puzzle. Your goal is to control the snake and absorb cubes with a smaller or equal value. Each absorbed cube increases your mass, making the snake longer and stronger. But be careful &mdash; colliding with a larger cube will result in defeat. The game offers a unique gameplay experience that blends fast-paced action with strategic thinking. You must plan your path carefully, avoid dangerous cubes, survive as long as possible, and score the highest number of points. The controls are simple and intuitive: on PC, the snake follows your cursor, while on mobile de

Instruções: Absorb cubes that are smaller than or equal to your current mass Colliding with a larger cube will result in defeat For PC The snake moves by following your mouse cursor For mobile devices Control the snake rsquo s direction using a virtual joystick ', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Brainrot World Hole io', 'embed', 'https://img.gamemonetize.com/qbsw3x9auxgjncitdcgnat16aptkq4ns/512x384.jpg', 'https://html5.gamemonetize.co/qbsw3x9auxgjncitdcgnat16aptkq4ns/', 'Brainrot World Hole.io is a hilarious casual hole game packed with chaotic brainrot energy and funny Italian meme vibes. Control a growing hole and dive into a crazy world where swallowing everything in sight is the key to victory. Move around the map and collect objects smaller than your hole.

Instruções: Mouse click or tap to play ', 'Fácil', 100, '{"width": 1334, "height": 750}', false, 'available'),
('Snake Fusion Arena', 'embed', 'https://img.gamemonetize.com/orj7l5d1ddgyh8oqkzqqzu7q6pan4kqo/512x384.jpg', 'https://html5.gamemonetize.co/orj7l5d1ddgyh8oqkzqqzu7q6pan4kqo/', 'Snake Fusion Arena is a fun arcade snake game with a unique fusion twist. Before you enter the arena, visit the home screen to buy new snakes, merge them, and choose between different game modes like Normal, Survival, and Dino Mode.

Instruções: Mouse click or tap to play', 'Médio', 100, '{"width": 720, "height": 1280}', false, 'available'),
('Flappy Witch Fly', 'embed', 'https://img.gamemonetize.com/06nfr1994zfoeu76fmoy2th2sifk1qf8/512x384.jpg', 'https://html5.gamemonetize.co/06nfr1994zfoeu76fmoy2th2sifk1qf8/', 'Flappy Witch Fly is a fun and challenging arcade game inspired by the classic Flappy Bird style, where you control a little witch flying on her magic broomstick. Tap or click the screen to keep her airborne and dodge obstacles as you fly through an enchanted world filled with trees and mountains. The pace is fast, the controls are simple, and every game tests your reflexes and precision. Perfect for short but addictive sessions, Flappy Witch Fly combines colorful graphics, smooth animations, and progressive difficulty that will have you trying again and again to beat your high score.

Instruções: Tap the screen to jump', 'Difícil', 100, '{"width": 460, "height": 270}', false, 'available'),
('Survivor.io Battle', 'embed', 'https://img.gamemonetize.com/g2yx03az6bsx6sekkut63069587y5ads/512x384.jpg', 'https://html5.gamemonetize.co/g2yx03az6bsx6sekkut63069587y5ads/', 'Dangerous zombies have overrun the city, pushing humanity to the brink of extinction! The streets are in chaos, and survival is the only option left. Awakened by fate, you step forward as a lone warrior with unlimited potential. In Survivor.io Battle, one player must face endless waves of ruthless zombies and fight for survival. Armed with powerful weapons, you must move smartly, attack strategically, and avoid being surrounded by the overwhelming horde. Collect mystery boxes scattered across the city to unlock upgrades, boost your abilities, and gain powerful weapons that turn the tide of battle.

Instruções: Up - - UP Arow Down - - Down Arrow Left - - Left Arrow Right - - Right Arrow', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Boss Office Life Simulator', 'embed', 'https://img.gamemonetize.com/931otwnbdhvoa4yojtp3y5g3ypfryfu2/512x384.jpg', 'https://html5.gamemonetize.co/931otwnbdhvoa4yojtp3y5g3ypfryfu2/', 'Welcome to our game and your first super cool day as a boss! Sometimes, work life is boring. But in our game, it is not! Because here, you are the only boss. Go to the office and enjoy life! There are multiple levels you can experience. Hire/Fire an employee, throw papers to your colleagues to wake them up, or investigate The company your father built is going bankrupt. As a boss, you have a chance to go back in time to save your company. Manage your office with an iron fist or let your employees slack off without consequence. How you manage your office will determine your companys success.

Instruções: Left mouse click to accept and refuse requests ', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('ICE DASH', 'embed', 'https://img.gamemonetize.com/k77rpabre5am7bilq0zsjld6fv8zussk/512x384.jpg', 'https://html5.gamemonetize.co/k77rpabre5am7bilq0zsjld6fv8zussk/', 'Ice Dash is a fun and frosty adventure where you draw icy lines to guide Santa through exciting levels. Help him slide across your custom paths, avoid icy traps, ride moving platforms, and collect yummy cookies along the way! Watch out for obstacles and keep your balance &ndash; the challenge gets harder as you go. Can you get every cookie and make Santa dash to victory?

Instruções: Controls Draw Ice Line Tap and drag Mobile Click and drag PC Move Santa Santa slides automatically on the lines you draw Pause Game Tap the pause button', 'Difícil', 100, '{"width": 800, "height": 450}', false, 'available'),
('Jungle Mart idle game', 'embed', 'https://img.gamemonetize.com/e8eah86fzgbb5rpni7i2zqk2huqks6nm/512x384.jpg', 'https://html5.gamemonetize.co/e8eah86fzgbb5rpni7i2zqk2huqks6nm/', 'Jungle Mart is a casual idle farming and market management game where youep workers awake to maintain smooth production. Hire helpers, upgrade efficiency, and expand your jungle market step by step. Easy to play yet strategic, Jungle Mart delivers a relaxing idle experience with constant progression and satisfying management gameplay.

Instruções: Mobile Use the on-screen joystick to move and interact PC Use W A S D keys to move around the jungle mart', 'Fácil', 100, '{"width": 1920, "height": 1080}', false, 'available'),
('Ants io', 'embed', 'https://img.gamemonetize.com/padkimfk900lo640e7v8dm70zuqacvpv/512x384.jpg', 'https://html5.gamemonetize.co/padkimfk900lo640e7v8dm70zuqacvpv/', 'Ants io is a fast-paced .io-style arena game where you control a battle-hardened ant fighting for the top spot in the jungle. Move around the map, hunt enemies, and use your unique special ability to outplay other ants. Each ant type comes with its own special skill and playstyle, and you can unlock many more in the in-game shop. Choose from four different game modes to test your skills, and pick from three random skills during the run to build powerful combos. Survive, grow stronger, and be the last ant standing to claim first place on the leaderboard.

Instruções: Mouse click or tap to play', 'Médio', 100, '{"width": 1600, "height": 720}', false, 'available'),
('Mega Escape Car Parking Puzzle', 'embed', 'https://img.gamemonetize.com/249wl1gt32c8pf51yveq11sxc61ob5ub/512x384.jpg', 'https://html5.gamemonetize.co/249wl1gt32c8pf51yveq11sxc61ob5ub/', 'A fun and compelling puzzle board game called Parking Jam. Its more than just parking; its an enjoyable driving adventure that will advance you. Parking lot traffic jams, difficult parking conditions, irate seniors, and more. Play one of the best parking board games, earn rewards and unlock skins, solve harder and harder puzzles, decide which car to move to find smooth departs without hitting anybody or anything, characteristics.

Instruções: Move the objects to solve the puzzle ', 'Difícil', 100, '{"width": 960, "height": 600}', false, 'available'),
('BrainrotIO', 'embed', 'https://img.gamemonetize.com/8n1q0ns6lcaebps64s94ash2twh5ehj0/512x384.jpg', 'https://html5.gamemonetize.co/8n1q0ns6lcaebps64s94ash2twh5ehj0/', 'Welcome to the world where crocodiles turn into airplanes, cows live on Saturn, and cappuccinos dance on stage in ballet tutus. Play as the strangest creatures born from Italian brainrot: Bombardiro Crocodilo Tralalero Tralala Lirili Larila Bobritto Bandito Cappuccino Assassino La Vaca Saturno Saturnita Ballerina Cappuccina Boneca Ambalabu Burbaloni Lulioli Chimpanzini Bananini Every new form is a surprise, a meme, and pure absurdity that makes the game even more fun!

Instruções:  Control your snake-plane and collect glossy dots Grow longer cut off opponents and grab their loot Climb the leaderboard and unlock all Italian brainrot skins Enjoy chaos memes and absurd humor ', 'Fácil', 100, '{"width": 1080, "height": 1920}', false, 'available'),
('Slither Mini Kingdom', 'embed', 'https://img.gamemonetize.com/21k6yq7qmr0c2807attftweykcvk8e3m/512x384.jpg', 'https://html5.gamemonetize.co/21k6yq7qmr0c2807attftweykcvk8e3m/', 'Control a glowing snake in a competitive arena, eating dots to grow longer while outmaneuvering other players. Avoid colliding with your rivals to survive, and trap them to turn them into food. Your goal is simple: become the longest snake and dominate the leaderboard.

Instruções: Mouse to control amp space button to boost in phone use joystick to move ', 'Médio', 100, '{"width": 1280, "height": 720}', false, 'available'),
('Goal.io', 'embed', 'https://img.gamemonetize.com/vjyl8p9lma7kpn58wh0syqkj6ph28clp/512x384.jpg', 'https://html5.gamemonetize.co/vjyl8p9lma7kpn58wh0syqkj6ph28clp/', 'Goal.io &ndash; Score Big in This Free Football IO Game Online Looking for a fast-paced soccer game you can play right in your browser? Meet Goal.io &mdash; the ultimate free football io game online where reflexes, timing, and sharp shooting decide who rules the leaderboard. No downloads. No sign-ups. Just you, the ball, and 3 minutes to score big.

Instruções: WADS to move', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Tec Tak Toe Pro', 'embed', 'https://img.gamemonetize.com/8rmp9fpj8vfuqnuc8xw30evhokiwu4cc/512x384.jpg', 'https://html5.gamemonetize.co/8rmp9fpj8vfuqnuc8xw30evhokiwu4cc/', 'Tec Tak Toe Pro &ndash; The Ultimate Tic Tac Toe Challenge! Step into the world of Tec Tak Toe Pro, where classic strategy meets modern excitement! Battle against a smart AI opponent in a vibrant, animated game board using stunning green, red, and violet colors. Play as X and outsmart the computer! Watch Rewarded Ads to unlock powerful perks &mdash; like removing your opponent&rsquo;s move! Victory Animations make each win feel legendary, while defeat animations add extra drama. Features: AI opponent for solo challenges Animated win/loss effects Colorful and modern design Rewarded ads for game-changing advantages Fully responsive

Instruções: Tap Click on a Cell Place your symbol X or O in the selected cell Rewarded Ad Button Watch an ad to remove the opponent rsquo s last move and get another chance to play in that spot This gives you a strategic advantage Reset Button Start a new gam', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('gem clicker pro', 'embed', 'https://img.gamemonetize.com/g57vca72wr68ebe46uz0t2hz5gdg7lem/512x384.jpg', 'https://html5.gamemonetize.co/g57vca72wr68ebe46uz0t2hz5gdg7lem/', 'Welcome to Gem Clicker Pro, the ultimate idle clicker experience that will keep you hooked for hours! Enter a mesmerizing world of sparkling diamonds and endless clicking fun. What Makes Gem Clicker Pro Special? Stunning Visual Effects: Watch as beautiful particles explode with every click, creating a satisfying visual feedback that makes each tap feel rewarding. Progressive Upgrade System: Start with simple clicks and evolve into a gem-collecting powerhouse with our comprehensive upgrade system. Rewarding Ad System: Every 50 clicks, watch a short advertisement to earn massive bonus rewards - up to 10x your current click power!

Instruções: Basic Controls Primary Action Left Click or Tap on the central diamond to collect gems Each click awards gems based on your current click power Watch for visual effects and particle explosions with each successful click Game Interface Stats Panel Top ', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Squid Game: Craft Runner', 'embed', 'https://img.gamemonetize.com/uue9ttbprz2ayg3q7qu0xm9ct4gpx93p/512x384.jpg', 'https://html5.gamemonetize.co/uue9ttbprz2ayg3q7qu0xm9ct4gpx93p/', 'Join the fun in Squid Game Subway Craft! Craft your way through obstacles and race along the railway tracks in a Minecraft-style world. Face exciting challenges, meet cool characters, and show your skills as you survive the ultimate test in this action-packed game inspired by Squid Game! Let me know if this works for you!se!

Instruções:  Right Right Arrow or D Left Left Arrow or Q Up Up Arrow or Z Down Down Arrow or S', 'Difícil', 100, '{"width": 1920, "height": 1080}', false, 'available'),
('Bitcoin.io', 'embed', 'https://img.gamemonetize.com/m6zjbir993y0jreqoja76d0gub0u8une/512x384.jpg', 'https://html5.gamemonetize.co/m6zjbir993y0jreqoja76d0gub0u8une/', '&lt;Chomp your way to the top in Bitcoin.io &ndash; the crypto-themed multiplayer madness! Munch coins and energy to grow bigger, dodge rivals, and dominate the leaderboard in this fast-paced online arena. It is free, frantic, and super fun. Are you ready to become the biggest Bitcoin in the blockchain?

Instruções: Mouse to play ', 'Fácil', 100, '{"width": 1920, "height": 1080}', false, 'available'),
('Tung Sahur IO', 'embed', 'https://img.gamemonetize.com/oddet3vf59i0den8dikuc3us81aby79z/512x384.jpg', 'https://html5.gamemonetize.co/oddet3vf59i0den8dikuc3us81aby79z/', 'Join up to 100 players in this hilarious viral meme-inspired multiplayer mayhem! Start as an innocent school kid, but watch out, the legendary Tung Sahur infection is spreading fast! Experience tiktoks most beloved bombardino crocodilo and tung tung tung sahur memes come to life in an epic infection game that will have you laughing and screaming at the same time along with your friends. Play as a school kid trying to survive the chaos, or get infected and join the Tung Sahur army to hunt down your former classmates.

Instruções: WASD Arrow keys Move your character LEFT MOUSE Action jump as a kid or attack as a Tung Sahur MOUSE Move camera Mobile DRAG with your LEFT FINGER to move around DRAG with your right finger to look around TAP the GREEN BUTTON to Action jum', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Snake War Multiplayer', 'embed', 'https://img.gamemonetize.com/qf4hzartah4bf6ewbpelfx4dmz1qql4a/512x384.jpg', 'https://html5.gamemonetize.co/qf4hzartah4bf6ewbpelfx4dmz1qql4a/', 'Enter the arena in Slither Battle: Snake War, the ultimate snake survival game! Start as a small slither and eat glowing orbs to grow larger. Outsmart other snakes, trap them, and collect everything they drop. But be careful, one wrong move and it&rsquo;s game over! Whether youre a casual player or competitive survivor, this addictive snake war will test your reflexes, strategy, and speed! Key Features: - Eat and grow to dominate &bull; Outsmart and trap enemy snakes &bull; Simple, smooth controls &bull; Fast-paced slither gameplay &bull; Offline mode and daily rewards &bull; No time limits &ndash; play your way!

Instruções: Mouse click or tap to play', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('snake eat food game ', 'embed', 'https://img.gamemonetize.com/bwpzprwsx24h3n2uanhr5kl7qxqz9m5n/512x384.jpg', 'https://html5.gamemonetize.co/bwpzprwsx24h3n2uanhr5kl7qxqz9m5n/', ': Classic Snake, Modern Fun! Guide the rainbow serpent, eat apples, and aim for the high score. Simple, addictive, and colorful! Relive the arcade classic! Eat, grow, and survive as the Rainbow Snake. How long can you last? The ultimate HTML5 Snake challenge! Smooth controls, vibrant visuals, and classic addictive gameplay. Get your high score!

Instruções: Mouse click or tap to play', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Twerk it! body Race 3D', 'embed', 'https://img.gamemonetize.com/q0g2r6rxhqmfnjxjrwxe6de2ercjotqi/512x384.jpg', 'https://html5.gamemonetize.co/q0g2r6rxhqmfnjxjrwxe6de2ercjotqi/', 'Welcome to the wildest racing game and a twerking simulator in one&mdash;Twerk Race 3D &mdash; fun run game! Get ready to shake your body in a twerk battle, dash across the racing track, and chomp your way through some fun racing challenges in the world of exciting 3d race games! Ready, set, go! &zwj;

Instruções: use joystick', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Territory.io', 'embed', 'https://img.gamemonetize.com/z1tr0vb7m6qx9thl63e91rxy07u1mklx/512x384.jpg', 'https://html5.gamemonetize.co/z1tr0vb7m6qx9thl63e91rxy07u1mklx/', 'Territory.io is an exciting territory capture game where players compete to control the largest area of the map. Features: &bull; Capture territory by creating loops with your trail &bull; Compete against AI opponents for dominance &bull; Collect power-ups for special abilities &bull; Simple controls: use WASD or arrow keys to move &bull; Real-time leaderboard shows whos winning &bull; Fast-paced gameplay with strategic elements Can you become the territory master? Play now and claim your space!

Instruções: Mouse click or tap to play', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Driver fast', 'embed', 'https://img.gamemonetize.com/1c3ko6qs3plggl0a3cy9abpj0hmlk8lw/512x384.jpg', 'https://html5.gamemonetize.co/1c3ko6qs3plggl0a3cy9abpj0hmlk8lw/', 'A car game, in development, for now it only has 1 car and a limited map, this will change on March 3, 2025, hugs!

Instruções: W - Accelerate S - Brake A - turn left D - Turn right Space - Handbrake E - Up shift Q - Down shift', 'Fácil', 100, '{"width": 1920, "height": 1080}', false, 'available'),
('Renovation!', 'embed', 'https://img.gamemonetize.com/zbu7imnkmtb90kevp0u92rwmgl2d1ap8/512x384.jpg', 'https://html5.gamemonetize.co/zbu7imnkmtb90kevp0u92rwmgl2d1ap8/', 'You need to control workers, first move furniture into messy houses, and then sell them for money. Use the money you earn to build a brand new house!

Instruções: Mouse click or tap to play', 'Médio', 100, '{"width": 750, "height": 1334}', false, 'available'),
('tinywar.io', 'embed', 'https://img.gamemonetize.com/fpegl6hk176yz1w1suj7fkw8g2ifi86o/512x384.jpg', 'https://html5.gamemonetize.co/fpegl6hk176yz1w1suj7fkw8g2ifi86o/', 'Tinywar.io throws you into a ruthless sword-fighting free-for-all where a single hit means defeat. Fight to unlock all 10 character evolutions and boost your speed with each upgrade. Can you dominate the leaderboard and survive the longest?

Instruções:  Move the mouse to guide your character Click left mouse button - Attack Hold right mouse button - Speed Boost', 'Difícil', 100, '{"width": 1920, "height": 1080}', false, 'available'),
('Survev.io', 'embed', 'https://img.gamemonetize.com/q9xrmuceu30pey8llzop5cr0p1p2fbx9/512x384.jpg', 'https://html5.gamemonetize.co/q9xrmuceu30pey8llzop5cr0p1p2fbx9/', 'Survev.io Battle Royale is a thrilling multiplayer game where you fight to be the last character standing on a shrinking island. Start with nothing but your fists, scavenge for weapons and supplies, and stay within the safe zone. Choose between solo, duo, or squad modes, and use strategy and skills to outlast up to 50 opponents.

Instruções: Movement W A S D Aim Mouse Melee Shoot Left-Click Change Weapons 1 through 4 or Scroll Wheel Stow Weapons Melee Mode 3 or E Swap to Previous Weapon Q Switch Gun Slots T or drag gun to other slot Reload R Scope Zoom Left-click on Zoo', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Battle Jitsu', 'embed', 'https://img.gamemonetize.com/cxu4dpr5uspgzim70lf6t4p6milazwr0/512x384.jpg', 'https://html5.gamemonetize.co/cxu4dpr5uspgzim70lf6t4p6milazwr0/', 'In Battle Jitsu, you enter intense multiplayer online battles where strategy is everything. Carefully choose your cards and play the right element to beat your opponent. Fire, water, and ice face each other in a fast and dynamic duel. Master the elements, predict your opponents movements and prove yourself to be the true master of Battle Jitsu!

Instruções: Use the mouse to select the cards fire beats snow snow beats water and water beats fire ', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Noobik Battlegrounds', 'embed', 'https://img.gamemonetize.com/5zf2l6ec0cef43uo7ftxbr0l386h0o6i/512x384.jpg', 'https://html5.gamemonetize.co/5zf2l6ec0cef43uo7ftxbr0l386h0o6i/', 'The tactical shooter Noobik Battlegrounds is waiting for you in its ranks, fighter. Online game in which you appear at a random point on the map, and then collect weapons and equipment, after which you kill the other players on map along the way. Game tasks: 1) Find weapons, equipment. 2) Gradually the zone will narrow to the center, you need to go to the center, otherwise you will be killed by zone that narrows. 3) There will be other survivors on your way, you will need to kill them all to win. 4) If you are killed, you can either watch other survivors or find a new session. 5) Winner is the one who remains the only one alive on map.

Instruções: Walking is W A S D and on a smartphone there is a joystick on screen Shooting and aiming is a mouse and on a smartphone there is a button on screen Exit the transport - F or a button on screen ', 'Difícil', 100, '{"width": 1280, "height": 720}', false, 'available'),
('Color Path IO', 'embed', 'https://img.gamemonetize.com/993brpbfu5u9o090ik0khqjsgf8t0kg6/512x384.jpg', 'https://html5.gamemonetize.co/993brpbfu5u9o090ik0khqjsgf8t0kg6/', 'Welcome to Color Path.io! Get ready to run and draw your color path to claim the biggest area. Strategize by drawing paths around your opponents to trap them and secure your victory. Can you outsmart and outmaneuver your rivals to become the ultimate champion?

Instruções: Mouse click or tap to play', 'Fácil', 100, '{"width": 350, "height": 600}', false, 'available'),
('FLOORLAND CREATOR', 'embed', 'https://img.gamemonetize.com/suba12vwfb7y6adfy4dbtxmef0sekzl2/512x384.jpg', 'https://html5.gamemonetize.co/suba12vwfb7y6adfy4dbtxmef0sekzl2/', 'The void is a game where you manage the cards of famous players, you can win prizes from the game, join now and play to win incredible rewards

Instruções: Analog mobile click button', 'Médio', 100, '{"width": 1020, "height": 1920}', false, 'available'),
('Hole Io 2', 'embed', 'https://img.gamemonetize.com/77h4sbaucufl8hc03nna7anwjem7mtop/512x384.jpg', 'https://html5.gamemonetize.co/77h4sbaucufl8hc03nna7anwjem7mtop/', 'Hole.io is a super addictive free arcade game. If you were to ask what game is the most popular these days? Then its the black hole devouring game that has exploded in popularity worldwide.

Instruções: Mouse click or tap to play', 'Difícil', 100, '{"width": 1080, "height": 1920}', false, 'available'),
('Zombie Royale Io', 'embed', 'https://img.gamemonetize.com/d3zex3l2rordlog1xeiq4id7521xskby/512x384.jpg', 'https://html5.gamemonetize.co/d3zex3l2rordlog1xeiq4id7521xskby/', 'Zombie Royale io is a collecting survival arcade IO game. With 3D cartoon survivors, you need to help them rescue more survivors and shoot down as many zombies as you can. As the time goes on, you will meet more and more strong zombies. They will come and chase the last survivors randomly. You can summon more soldiers and bombs in the game. After each round, you can use the gold coins to upgrade your survivors.

Instruções: Mouse click or tap to play ', 'Fácil', 100, '{"width": 720, "height": 1280}', false, 'available'),
('Bridge Fun Race', 'embed', 'https://img.gamemonetize.com/d55mz3ys0ne1682kzxj5v9maq8grsuy9/512x384.jpg', 'https://html5.gamemonetize.co/d55mz3ys0ne1682kzxj5v9maq8grsuy9/', 'Bridge Fun Race is an IO battle arcade game like Mr Bean series. With 3D cute roles, you can join different knockout battles with several AI opponents. Only the first 3 places players can win and join into the next battle. In Racing levels, you need to collect items and push the obstacles to the finish line. In Survival levels, you need to roll and launch snowballs to hit the other players onto the platform in a limited time.

Instruções: Mouse click or tap to play', 'Médio', 100, '{"width": 750, "height": 1334}', false, 'available'),
('Blockapolypse Zombie Shooter', 'embed', 'https://img.gamemonetize.com/1j0t5mfnpgw2ggvltucvoe5l1g0ny5ze/512x384.jpg', 'https://html5.gamemonetize.co/1j0t5mfnpgw2ggvltucvoe5l1g0ny5ze/', 'Blockapolypse: Zombie Shooter is a defense shooting simulation game with 3D pixel undead creatures. To defend this position, you need to use weapons to defend incoming zombies from 3 directions. After you kill all zombies, you still need to defeat a giant undead creature. As long as you lose all of your HP, you will lose the game. When you earn enough gold coins, you can buy better weapons in the gun shop. Good luck and survive!

Instruções: Mouse click or tap to play', 'Difícil', 100, '{"width": 1280, "height": 720}', false, 'available'),
('King of Crabs', 'embed', 'https://img.gamemonetize.com/7qd3n9dqksf5kv9melr3cx96oo8rmjws/512x384.jpg', 'https://html5.gamemonetize.co/7qd3n9dqksf5kv9melr3cx96oo8rmjws/', 'Easy to operate the krab,The Shell Gallery will show each roles armor, speed, skill, and pelt,The Equipment shop sells 5 Claws, 5 Bodies, and 5 Legs, Claim extra claw coins in the Sign and Spin,The Quick Match will make a fight with 24 players.The Ultimate Guide to Winning Tactics and Tips,Find a shell first. Collect and eat fish on the ground to grow up, Attack the weaker opponents.

Instruções: Mouse click or tap to play', 'Fácil', 100, '{"width": 1334, "height": 750}', false, 'available'),
('Shark Dominance io', 'embed', 'https://img.gamemonetize.com/ecmolbepwgsxn2fhmez6p0cx3mva1dap/512x384.jpg', 'https://html5.gamemonetize.co/ecmolbepwgsxn2fhmez6p0cx3mva1dap/', 'Survive as long as possible and collect the baits to rank high on the leaderboard. You can level up by eating rival worms to save your best score. Surround and hunt your opponents with sharp maneuvers. If the worms head touches another worms tail, you lose the game. Tap the screen to control the worm. Tap the screen with your second finger to speed up the worm. Developer: odgameinfo@gmail.com

Instruções: PC Movement mouse Speed D key Mobile Movement touch Speed second touch', 'Médio', 100, '{"width": 1080, "height": 1920}', false, 'available');



INSERT INTO games (title, type, image_url, game_url, description, difficulty, xp_reward, config, is_active, status) VALUES
('FruitBasket', 'embed', 'https://img.gamemonetize.com/qd13183e4tdr46d7a6gqdhpq5c7k60l5/512x384.jpg', 'https://html5.gamemonetize.co/qd13183e4tdr46d7a6gqdhpq5c7k60l5/', 'Fruit Catcher is a simple and engaging 2D game where players control a basket to catch falling fruits. The objective is to catch as many fruits as possible to increase the score. The game offers a fun challenge by requiring players to time their actions and navigate the basket efficiently to catch the fruits before they fall out of reach. Gameplay: Movement: Players can move the basket left and right using the arrow keys or A and D keys. Fruit Drop: Fruits move horizontally across the screen. Players must click the mouse to make the fruit fall. The goal is to catch the falling fruit with the basket. Scoring: Each time a fruit is success

Instruções: click or tap to shoot the fruit', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Block Team Deathmatch', 'embed', 'https://img.gamemonetize.com/6viikkt1bjfynvfk6u6hn4v16m5h3063/512x384.jpg', 'https://html5.gamemonetize.co/6viikkt1bjfynvfk6u6hn4v16m5h3063/', 'Block Team Deathmatch is a first-person shooting simulation game. All models are made of pixel blocks including scenes, characters, and weapons. We have 4v4 Team Mode, Individual Mode, and Sniper Mode for you to select. If I were you, I would play the Team Mode first for better equipment, then challenge the other 2 modes when the rank levels up. If you never played any shooting games, I recommend you buy an auto-rifle to fight at any distance. Keep calm and shoot first!

Instruções: Mouse click or tap to play', 'Fácil', 100, '{"width": 1624, "height": 750}', false, 'available'),
('Snake Train Zone', 'embed', 'https://img.gamemonetize.com/6aci346224wl1kjxyc4oo681k4wxylhl/512x384.jpg', 'https://html5.gamemonetize.co/6aci346224wl1kjxyc4oo681k4wxylhl/', 'Snake Train Zone is an exciting shooting combat game. If you are a big fan of the Snake series of games, then this game is for you! Your task is simple, enter the arena, collect colored balls and when the number bar is full you can add a soldier that follows you. Here you can not only experience the joy of shooting but also the fun of breaking through and upgrading! Are you ready for this combat?

Instruções: Mouse click or tap to play', 'Médio', 100, '{"width": 1280, "height": 720}', false, 'available'),
('Snake Color Race', 'embed', 'https://img.gamemonetize.com/3xse34phrgljynh51benwcuglaqf4v92/512x384.jpg', 'https://html5.gamemonetize.co/3xse34phrgljynh51benwcuglaqf4v92/', 'In Snake Race, navigate a vibrant arena as a colorful snake. Your mission: eat balls matching your snakes color to grow bigger. But growth is just the start &ndash; as you get larger, so do the challenges. Tackle the thrilling bridge challenge by using your collected balls to shoot and break through blocks. This requires not just growth, but strategy and precision. Compete against other players in real-time. The race isnt just about size, its about outsmarting and outmaneuvering your rivals. Can you become the most dominant snake in the arena? Simple to learn yet challenging to master, Snake Race offers an engaging experience for players of a

Instruções: Use the mouse to control the direction of your snake and collect the balls that are the same color as your snake ', 'Difícil', 100, '{"width": 600, "height": 960}', false, 'available'),
('Marble Match Origin', 'embed', 'https://img.gamemonetize.com/iipbsb2vnjuclzn4jf7fexz85c0d3ogl/512x384.jpg', 'https://html5.gamemonetize.co/iipbsb2vnjuclzn4jf7fexz85c0d3ogl/', 'Marble Match Origin is an exciting shooting game where you can experience unique challenges and surprises. The game features multiple difficulty levels , and players need to master the direction and speed of shooting balls to complete level objectives. As the game progresses, you will face more and more challenges and difficulties, and you need to constantly improve your skills and reaction speed to complete each level. Download Marble Match Origin now and start your adventure!

Instruções:  bull Game with different difficulty levels and levels bull Gorgeous graphics and animation effects bull Various props and rewards bull Various achievements and leaderboards bull Unique challenges and surprises bull Support offline games', 'Fácil', 100, '{"width": 1920, "height": 1080}', false, 'available'),
('Grind io', 'embed', 'https://img.gamemonetize.com/oilojh3yxoenhphbpt70udjdvkvis77w/512x384.jpg', 'https://html5.gamemonetize.co/oilojh3yxoenhphbpt70udjdvkvis77w/', 'Grind io offers a fun and challenging game where you must get power in order to climb in the global leaderboard! To do this you must mine ores and beat players for coins! Use these coins to get more power and health in order to be the strongest and most resistant player!

Instruções: WASD Arrow keys or joystick to move Tap Click to attack ', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('State Wars', 'embed', 'https://img.gamemonetize.com/ow2v99y6plh0nq6c7zsmrqahfq9avaam/512x384.jpg', 'https://html5.gamemonetize.co/ow2v99y6plh0nq6c7zsmrqahfq9avaam/', 'State io Wars is an online strategy game that involves directing your forces to expand your territory. The primary objective is to capture both neutral and enemy territories under your dominion.

Instruções: Left-Click drag Send Troops Touchscreen for Mobile Devices', 'Difícil', 100, '{"width": 960, "height": 600}', false, 'available'),
('Rolling Balls.io', 'embed', 'https://img.gamemonetize.com/yt9ftxxqnka7n959cc1qnmoqfrj4calv/512x384.jpg', 'https://html5.gamemonetize.co/yt9ftxxqnka7n959cc1qnmoqfrj4calv/', 'welcome to Rolling Balls io game! !use the joystick or mouse click to control you ball and start to crush everything in your sight! Dont forget to avoid huge balls because they can destroy you! How big it can get?

Instruções: Mouse click or tap to play', 'Fácil', 100, '{"width": 720, "height": 1280}', false, 'available'),
('Connect Fruits', 'embed', 'https://img.gamemonetize.com/dj1jwzufate2bey9osne9ikqvhxu40hd/512x384.jpg', 'https://html5.gamemonetize.co/dj1jwzufate2bey9osne9ikqvhxu40hd/', 'Juice Fresh - is a fruit connect game to where you have to connect fruits and make yourself a juice in limited moves. Get ready for a new Jurney. With more then 100 level.

Instruções: Connect same fruits ', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Swordbattle.io', 'embed', 'https://img.gamemonetize.com/m2yzvbmyf75dl11i5lrtzlykjkzrgb85/512x384.jpg', 'https://html5.gamemonetize.co/m2yzvbmyf75dl11i5lrtzlykjkzrgb85/', 'Swordbattle.io is a multiplayer game where players fight each other with different 2D swords, and try to gain coins. The more coins you have, the bigger and powerful you get! Try to become the biggest of them all. Upgrade your character, fight with friends, and rule the land!

Instruções: Keyboard mouse default - WASD or Arrow keys to move click and point mouse to swing and C to throw sword Mouse mode you can enable this in settings - click to swing right click to throw and move your mouse to move amp point Enter - chat with ot', 'Difícil', 100, '{"width": 1280, "height": 720}', false, 'available'),
('Bricks Breakers Infinity', 'embed', 'https://img.gamemonetize.com/mrw2d8le69jdofc3ngcskkp4x6zobmr4/512x384.jpg', 'https://html5.gamemonetize.co/mrw2d8le69jdofc3ngcskkp4x6zobmr4/', 'Relax your brain and play the best brick breaker game of the year. control the paddle and dont let the ball fall, break all the blocks to achieve a higher score

Instruções: shift the paddle', 'Fácil', 100, '{"width": 1280, "height": 1280}', false, 'available'),
('Cube Arena  2048  Merge Numbers', 'embed', 'https://img.gamemonetize.com/83up5y2u78nvd5ngywugy6j4g3im4lda/512x384.jpg', 'https://html5.gamemonetize.co/83up5y2u78nvd5ngywugy6j4g3im4lda/', 'Cubes 2048.io is an addictive online game that fuses Snake and 2048. Get a bigger number by collecting free cubes and eating other players with a smaller number than you. Your cubes with the same value that bump into one another will merge.

Instruções: Cubes 2048 turns 2048 into a 3D io game Slide around the arena picking up blocks to get bigger Picking up two of the same number will merge them into a single block as the total sum of both ', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('BINGO Real', 'embed', 'https://img.gamemonetize.com/w7w5gwfb43usxnt3v70zhmtynywxfsam/512x384.jpg', 'https://html5.gamemonetize.co/w7w5gwfb43usxnt3v70zhmtynywxfsam/', 'Bingo Real is a 75 ball game that could you make you play bingo with house card with different closing patterns as real one, the one who will close and click bingo first is the winner. Furthermore, there are 35 balls and 45 ball options which could make you play before 35 and 45 ball bounced up.

Instruções: Mouse click or tap to play', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Eat Small Fish', 'embed', 'https://img.gamemonetize.com/5h7odu5oyzgdzo77493utlamcoz43wlj/512x384.jpg', 'https://html5.gamemonetize.co/5h7odu5oyzgdzo77493utlamcoz43wlj/', 'Eat Small Fish is a game where you must eat small other fish to survive and become bigger. Eat Small Fish include all kinds of hungry fishes in the undersea water. They tanked and attacked smaller fish to become the ocean most powerful fish eater. Big fish eat small fish to be giant fish. Giant fish eat big fish and turn over the Mega fish. Mega fish eat giant fish and finally become fabulous fish in the underwater sea.

Instruções: Mouse click or tap to play', 'Fácil', 100, '{"width": 1280, "height": 720}', false, 'available'),
('Sumo Battle!', 'embed', 'https://img.gamemonetize.com/7mdskoub4xtdgvith418pqnpxjv1ewx3/512x384.jpg', 'https://html5.gamemonetize.co/7mdskoub4xtdgvith418pqnpxjv1ewx3/', 'Sumo wrestlers break all the canons of the sport; they do not look slender, muscular and fit; on the contrary, they are large fat men who are more round than slender. These are the rules and requirements for sumo wrestlers. To gain weight, athletes follow a special diet in the game Sumo Battle! You will help your character collect as many pieces of sushi as possible in order to become larger in size. And that means stronger. The goal is to throw your opponents off the podium by approaching them and pushing them into targets attached to their fat bellies. Please note that they will also try to push your hero.

Instruções: Desktop Use WASD or ZQSD to move Mobile Touch and move your finger to move ', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Skibidi Hero.IO', 'embed', 'https://img.gamemonetize.com/4ks356oenpbqv9qz7artzrsz828nlh2b/512x384.jpg', 'https://html5.gamemonetize.co/4ks356oenpbqv9qz7artzrsz828nlh2b/', 'Skidibi Hero: IO is an action game where you have to survive countless waves of monsters. Control your hero to move around, collecting all of the points from defeating enemies to leveling up. You will have 3 choices to upgrade your power so choose wisely to survive till the end of the game

Instruções: - Use you joystick in sence - Smooth Graphics - Awesome hero', 'Difícil', 100, '{"width": 1080, "height": 1920}', false, 'available'),
('Field of Dreams: Simulation Adventure', 'embed', 'https://img.gamemonetize.com/r459clg1msy6s04k8kfv1bdskk8gnql7/512x384.jpg', 'https://html5.gamemonetize.co/r459clg1msy6s04k8kfv1bdskk8gnql7/', 'Hello farmers! In the world of farm simulation games, its an amazing day for an incredible adventure simulation. Make use of your vacant land and turn it into a fertile, productive farm that everyone will want to visit! Gain farming experience and expand your borders to get more resources, create western style crops and raise cute animals for an amazing peaceful village life simulation! Its time to remove the chaff from the fields of the wild Wild West! Experience the serene charm of rural village life; A beautiful location with a view of the flowing river awaits you. Design your dream farm with lots of buildings and decorations.

Instruções: Mouse and Click', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Meteor.io', 'embed', 'https://img.gamemonetize.com/ou78d7yjy1fvg9ww5qd9228mjzyctdlh/512x384.jpg', 'https://html5.gamemonetize.co/ou78d7yjy1fvg9ww5qd9228mjzyctdlh/', 'Collect the shards, dodge the meteorite! A simple and addictive casual game that will test your reaction and agility. Become the best shard collector and show how far you can reach without getting hit by a barrage of meteorites!

Instruções: Control with joystick wasd spacebar Collect shards dodging meteorites flying at you Watch the time bar ', 'Médio', 100, '{"width": 1920, "height": 1080}', false, 'available'),
('Merge Room', 'embed', 'https://img.gamemonetize.com/ctu798dfdum75hgsv7l34gpc9ainsji4/512x384.jpg', 'https://html5.gamemonetize.co/ctu798dfdum75hgsv7l34gpc9ainsji4/', 'Merge Room is an addictive mobile game where players are tasked with filling a room with objects. The concept of the game is simple yet challenging, as players must merge objects together in order to make them grow and fill up the room. The game begins with a small, empty room and a few small objects scattered around. As players merge these objects together, they will grow in size and fill up more of the room. The larger the objects become, the more points the player will earn. Website Developer <a href=''https://www.gamesmunch.com/''>https://www.gamesmunch.com/</a>

Instruções: Overall Merge Room is a fun and addictive mobile game that is perfect for players of all ages With its simple yet challenging gameplay colorful graphics and catchy soundtrack it is sure to provide hours of entertainment and keep players coming back f', 'Difícil', 100, '{"width": 1080, "height": 1920}', false, 'available'),
('Sumo Smash!', 'embed', 'https://img.gamemonetize.com/zyjcvyrbjdb4400t324nzijc1in3hi5k/512x384.jpg', 'https://html5.gamemonetize.co/zyjcvyrbjdb4400t324nzijc1in3hi5k/', 'Step into the ring and embrace the ancient art of Sumo&mdash; with a twist! Welcome to Sumo Smash! an exhilarating game where youll wrestle for supremacy while indulging in a sushi feast to grow your sumo size. Features: Grow to Dominate. Push to Win. Treasure Chests &amp; Skins: Unlock treasure chests found within the arena to collect unique skins

Instruções: WASD or QZSD to move on desktop Touch to move on mobile ', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Monsters Dungeon Battle', 'embed', 'https://img.gamemonetize.com/cb4lyqk01r8nugfoqxnaps191l2xvq9f/512x384.jpg', 'https://html5.gamemonetize.co/cb4lyqk01r8nugfoqxnaps191l2xvq9f/', 'Fight against those monsters residing in the abandoned dungeon. Upgrade your stats, Collect classes, Wizard, Archer and more that can help you in your battle, and save the world by defeating them all!

Instruções: Left Mouse Button Touch Screen', 'Médio', 100, '{"width": 1080, "height": 720}', false, 'available'),
('Skibidi Online', 'embed', 'https://img.gamemonetize.com/zsp6q6syr025l3eaypqw6rxm9myjqn39/512x384.jpg', 'https://html5.gamemonetize.co/zsp6q6syr025l3eaypqw6rxm9myjqn39/', 'Skibidi Online is a multiplayer shooter game! Shoot attacking Skibidi Toilets in PvP or CO-OP mode. Fight on 10 different maps with melee and ranged weapons.

Instruções: Mouse click to attack WASD to move Space to jump E to equip weapon TAB to view stats', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Skibidi War   Toilets Attack', 'embed', 'https://img.gamemonetize.com/6nw0qptdh7pv9c6dv14rxserfbqqdoj5/512x384.jpg', 'https://html5.gamemonetize.co/6nw0qptdh7pv9c6dv14rxserfbqqdoj5/', 'Welcome to Skibidi War, a one-of-a-kind strategy shooter game set in the heart of Skibidi Toilet City. Here, the Skibidi Toilets face off against the innovative Camera Heads in a rousing war. Think youve experienced all shooter defense games? Skibidi war will redefine your expectations. Survive and defend your territory from a ceaseless attack of these dangerous rivals in a game that humorously mingles the epic with the everyday.

Instruções: You need to control the toilet to run continuously and defeat other toilets to win You can also pick up some weapons and use them to strengthen yourself ', 'Fácil', 100, '{"width": 720, "height": 1280}', false, 'available'),
('Clown Park Hide and Seek', 'embed', 'https://img.gamemonetize.com/x89je06j8zmspnm8azsllfiylp8ervox/512x384.jpg', 'https://html5.gamemonetize.co/x89je06j8zmspnm8azsllfiylp8ervox/', 'Clown Park - Hide And Seek is a camp against camp arcade game. It has beautiful graphic design and 3D space design. There are 3 modes: Survivor camp, and Chaser camp. Survivors need to collect enough keys to open the escape door within the time limit and escape successfully to win. On the contrary, the pursuer is to stop the survivors pace. Are you ready? Clown Park Hide and Seek: A Thrilling and Fun-Filled IOS Game In the world of mobile gaming, Clown Park Hide and Seek has emerged as a unique and captivating game that offers hours of entertainment to players of all ages. Developed for IOS platforms, this game has gained popularity due

Instruções: Mouse click or tap to play', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('SurvivalPixel.io', 'embed', 'https://img.gamemonetize.com/vbf4xpvfzbh03r17mnu662ifpwojhfvx/512x384.jpg', 'https://html5.gamemonetize.co/vbf4xpvfzbh03r17mnu662ifpwojhfvx/', 'We need you in a popular survival game. Help the Warrior survive and assist them in battling tougher monsters at each level. Be cautious, as monsters are coming from everywhere and you need to stay alive. Grab your sword, and eliminate all the monsters. The monsters you defeat will grant you health and power. Keep getting stronger and defeat the boss monsters.

Instruções:  Move back and forth with the WASD keys to play Mobile control buttons available ', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Skibidi Toilet.io', 'embed', 'https://img.gamemonetize.com/dffeouwj1z8gq8h73ad88wmdlcl7knp3/512x384.jpg', 'https://html5.gamemonetize.co/dffeouwj1z8gq8h73ad88wmdlcl7knp3/', 'This is Skibidi.io, the ultimate fusion of Skibidi and io gameplay that provides players with an adrenaline-filled experience! This game set in the heart of Skibidi Toilet City Here, you will control Skibidi Toilets and Cameramen in a rousing war.

Instruções: Your goal is to eat grow and evolve As you grow and evolve you will unlock special abilities and powers to help you in your quest for victory What you have to do is just to swipe to control it to make you stronger Until you are the Lord of the Skibid', 'Fácil', 100, '{"width": 750, "height": 1334}', false, 'available'),
('Stumble   Survival Guys ', 'embed', 'https://img.gamemonetize.com/ebzhf7uwcukpaeb1z4ma3yu0mm2g0hrm/512x384.jpg', 'https://html5.gamemonetize.co/ebzhf7uwcukpaeb1z4ma3yu0mm2g0hrm/', 'Stumble-Survival Guys is a very hot adventure elimination game. A variety of fun levels await your challenge, and the time has come to test your memory and dexterity! Run, sprint, and slide to overtake your opponents and dodge the obstacles that keep popping up. Can you survive to the end? Invite your friends to join you and kill them all! Stumble-Survival Guys: An Exciting Mobile Gaming Experience for iOS Users In the world of mobile gaming, Survival Guys has emerged as an exciting and addictive game that has captivated iOS users worldwide. Developed by a team of skilled game developers, Survival Guys offers a unique and challenging gaming

Instruções: Mouse click or tap to play', 'Médio', 100, '{"width": 854, "height": 480}', false, 'available'),
('Face Punch.io', 'embed', 'https://img.gamemonetize.com/akub1gx5xgvtbhp6ozi3adxmwmmm6ej2/512x384.jpg', 'https://html5.gamemonetize.co/akub1gx5xgvtbhp6ozi3adxmwmmm6ej2/', 'Step onto the ring to knock out all champions with your brutal punches for real boxing experience in io game universe! BECOME A CHALLENGER BOXER NOW! Attack with fierce face punches and combos to knock out others. Can you become the champion fighter of the boxing io game arena? EASY IO GAME CONTROLS! Smash everyone with your hits and make combos to knockout with only one button in the world of fighting! ULTIMATE FIGHTER SKILLS! Each hero has different special move to use in epic combat to knock out other fighting boxers.

Instruções: COLLECTIBLES Achieve objectives to unlock amazing heroes with skills and skins Step onto the classical fighting ring with your favorite hero to survive the longest make maximum combos or a great number of knockouts ', 'Difícil', 100, '{"width": 750, "height": 1334}', false, 'available'),
('Play In Mall', 'embed', 'https://img.gamemonetize.com/52g15pmd4ni6fcm12oit6r0rkcpj6niv/512x384.jpg', 'https://html5.gamemonetize.co/52g15pmd4ni6fcm12oit6r0rkcpj6niv/', 'Play an 3D first person water gun game with your friends! During a game break, you can buy items from Amazon (through verified Amazon Associates Program). No download needed, play it in your browser on any device!

Instruções: PC keyboard mouse move wasd or arrow keys rotate shoot select mouse Mobile tablet touchscreen move bottom left touch joystick rotate bottom right touch joystick shoot with move upper left touch joystick shoot with rotate upper right tou', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Skibidi Snake.io', 'embed', 'https://img.gamemonetize.com/88kisw889g91pa7fv6hwqzi0v3g2dbkw/512x384.jpg', 'https://html5.gamemonetize.co/88kisw889g91pa7fv6hwqzi0v3g2dbkw/', 'Skibidi Snake.io is a fast-paced, action-packed snake game that will test your reflexes and strategy skills. In this game, you control a snake that must eat as many Skibidi as possible to grow in size. The longer your snake gets, the more difficult it will be to control, but the more points you will score. Website Developer <a href=''https://naptechgames.com/''>https://naptechgames.com/</a>

Instruções: Desktop Use the Mouse left click button on the screen to Move Anywhere on the Screen Mobile Tap on the screen to Move Anywhere on the Screen ', 'Médio', 100, '{"width": 720, "height": 1280}', false, 'available'),
('Zomblox.io', 'embed', 'https://img.gamemonetize.com/rha2cyp1q8590dx3imb4gx8b7p74ilo3/512x384.jpg', 'https://html5.gamemonetize.co/rha2cyp1q8590dx3imb4gx8b7p74ilo3/', 'Multiplayer zombie survival game! Invite friends and defeat waves of zombies. Destroy loot boxes to get more powerful weapons. Play on 3 different maps or create your own maps using the level editor.

Instruções: Move - WASD ARROWS Attack - MOUSE CLICK Jump - SPACE Pickup Weapon - E Show Stats - TAB', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('PAC PAC RUN', 'embed', 'https://img.gamemonetize.com/ft4t61hdmqso9xy9nrt9728y3w1m2s3d/512x384.jpg', 'https://html5.gamemonetize.co/ft4t61hdmqso9xy9nrt9728y3w1m2s3d/', 'Hello, in this excellent endless running game you will forget the clocks and get lost in time, dont hit the creatures, all your points will go back and you will not like it at all. If you dont crash and you set the highest record, you will set the highest record in Pac Pac Run history.

Instruções: The controls are very simple you will not have any trouble if you are on mobile click anywhere on the screen if you say pc just click anywhere with the mouse ', 'Fácil', 100, '{"width": 849, "height": 400}', false, 'available'),
('Pixel Wars IO', 'embed', 'https://img.gamemonetize.com/cmb4ekw5gj5ljbl72ifbfw2dknlmy43l/512x384.jpg', 'https://html5.gamemonetize.co/cmb4ekw5gj5ljbl72ifbfw2dknlmy43l/', 'Collect pixels and draw beauty with them! The game has elements of hyper casual clicker and pixel art. Here you can not only collect pixels but also draw 2D images on the drawing arena with their help. This is a game for all ages and experience levels: clicker lovers, pixel art lovers and those who just want to draw will love it. Want to have more drawing pixels? Collect power-ups: slow down the movement of obstacles, doubling the won pixels, a magnet to attract bonuses and an extra life.

Instruções: - Left Arrow Right Arrow - Decrease increase pixel - Click with the mouse finger on an empty area of the screen on the game level - move the pixel resize', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('Game Station', 'embed', 'https://img.gamemonetize.com/7zpaf3bjzvw8h03hk3xzb8n1etedtzh5/512x384.jpg', 'https://html5.gamemonetize.co/7zpaf3bjzvw8h03hk3xzb8n1etedtzh5/', 'Mr. Robot has opened a new Game Station in city. Help him to grow the station. Different fun and interesting games to unlock. Fortnite, Forza Horizon, Mortal Kombat etc. Make money, buy waiters to help you, open new areas, find more games, be a millionare.

Instruções: MOUSE DRAG amp CONTROL TOUCH DRAG amp CONTROL WASD - ARROW KEYS', 'Difícil', 100, '{"width": 800, "height": 450}', false, 'available'),
('Horror Hide And Seek', 'embed', 'https://img.gamemonetize.com/1wb05eeb80ooxoas1qsxeuo2bqrxfqbl/512x384.jpg', 'https://html5.gamemonetize.co/1wb05eeb80ooxoas1qsxeuo2bqrxfqbl/', 'Horror Hide And Seek, Super exciting hide-and-seek game, Horror and thrilling hide-and-seek escape journey! The game takes hide-and-seek as the theme, and adds a variety of modes to choose from, including the classic hide-and-seek mode and the butcher mode where you can enjoy hunting.In addition, there are multiple modes such as single player, multiplayer, and transformed items to fight against the butcher. The game also adds some horror elements, whether it is from the screen or sound effects, it has a terrifying atmosphere. giving players a new hide-and-seek game experience!

Instruções: Follow the game tutorial ', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Rollem.io', 'embed', 'https://img.gamemonetize.com/8oqao5vefo041ymfs8wz9mqs3gudrj1k/512x384.jpg', 'https://html5.gamemonetize.co/8oqao5vefo041ymfs8wz9mqs3gudrj1k/', 'Rollem.io is a free IOGame. If you love animals, and especially these tiny ones that are like little loving balls of fur, called Hamsters, you''re going to love the protagonists of this online multiplayer io game. Cute hamsters, unique environment, and skill-based controls mix together to bring you the cutest of the io games out there. Prepare to embark in an adventure never seen before as you level up your hamster and unlock new stuff to make it unique and your very own! Rollem.io is the worldwide online multiplayer fast-paced hamster racing game, takes on races against people all over the world and try to beat the quickest records on each track! Noticed the golden coins over the level? Be sure to collect as much as you can, because in the game shop, you can unlock skins and trails which will make your hamster look unique, some skins & trails are also limited and exclusive, so be sure to keep an eye watching! Watch out for swinging hammers, as they will bump you out of your path so you fall and have to restart from the spawn area, and use fans and springs to get to higher places on the level, where there may be more golden coins to collect, or even the goal of the level. The levels for this online game are very tricky, so you have to always keep an eye where you''re moving, as there can be holes and other kind of obstacles to prevent you from completing the level, jump, dodge and go very fast as you make your way through while seeing other players falling from the sky, what a fun experience! You can also notice that each time a game ends you get your Worldwide Position, this means the game can also be competitive, and you can show up in the largest of the leaderboards found in the menu, if you''re good enough you could make your name last forever in this space, not only that; If you beat a time record on *any* level, you will get your name and time featured in the Leaderboards Panel in the spawn area, how cool is that? But keep on it, as other people will take it on and try to beat your times to kick you out of the board, how long will you last? It also comes with a level editor, so feel free to come up with your own tracks, and they will get added to the game automatically so other people will be able to race them. Rollem.io is playable on the browser, in a computer or in a mobile device, don''t forget to try it out or you might miss out on an awesome game experience! I won''t be keeping your attention for more, get in with your new cute hamster, race with him and other players online, and most importantly; Enjoy!

Instruções: Controls - W A S D to move - Mouse to look around and Jump The game supports gamepads So if you got an xbox360 PS4 or PS5 controller you can connect it to your device and start playing as if it was a console game', 'Médio', 100, '{"width": 800, "height": 600}', false, 'available'),
('FNF Music Battle', 'embed', 'https://img.gamemonetize.com/h93y4d3w0vomo32j381qvi5vgk7l76qr/512x384.jpg', 'https://html5.gamemonetize.co/h93y4d3w0vomo32j381qvi5vgk7l76qr/', 'Music Battle is a rhythm music game to test your musical knowledge and reflexes where you have to feel the rhythm of the music.

Instruções: Mouse click or tap to play', 'Difícil', 100, '{"width": 900, "height": 600}', false, 'available'),
('Staire Race', 'embed', 'https://img.gamemonetize.com/cvyynje4d6s1kgrh6vwiazccb3eyr2uh/512x384.jpg', 'https://html5.gamemonetize.co/cvyynje4d6s1kgrh6vwiazccb3eyr2uh/', 'Stair Race 3D Game Get ready for one of the most challenging games and build your stairs as fast as you can! You have to compete in a large arena who is the best at building stairs against a variety of difficult enemies In order to win, you have to pick up the staircase plans and use them to build the stairs and reach the next platform But watch out, enemies with more boards collected than you can easily crush you when you bump into them which will cause you to lose all your collected plans But of course it works in reverse too, so try to collect as many plans as you can and beat your enemies to get a big advantage Winning rounds will not only give you the pleasure of being the best player in the world It will also unlock cool new skins for your character and plans Are you ready to compete in the worlds biggest stair building challenge? Get ready for one of the most challenging games and build your stairs as fast as you can

Instruções: tap to run', 'Fácil', 100, '{"width": 960, "height": 600}', false, 'available'),
('NabNab Imposter', 'embed', 'https://img.gamemonetize.com/w1voyhhgd4z7kgx9e4aid2iwjsr0qjec/512x384.jpg', 'https://html5.gamemonetize.co/w1voyhhgd4z7kgx9e4aid2iwjsr0qjec/', 'NabNab Imposter - Fun io game is a super cool, easy and relaxing game. To win this, your mission is simple: Smash other crewmate by a huge hammer, Consume their power to become bigger and stronger, Be the only NabNab Imposter survival in the battlefield. However, be carefull and try to advoid bumping into other tricky impostors, otherwise, youll be smashed. You can choose among serveral roles to add more exciment: Hunter, Assasin, Captain, Trapper, Sword, Gunner... with unlimited skills and items. In this io game, where mutilplayer battle other to be the last one who survive, making yourseft a strong and smart one is crucial. Its super fun, check it out!

Instruções: - Hold and drag to move - Get closer to crewmates and smash them - Run fast and dont be hit', 'Médio', 100, '{"width": 600, "height": 960}', false, 'available'),
('Pifflo', 'embed', 'https://img.gamemonetize.com/4ylhli6ijr0lby3srncc3rremkalvfsz/512x384.jpg', 'https://html5.gamemonetize.co/4ylhli6ijr0lby3srncc3rremkalvfsz/', 'Discover Piffle a cute arcade puzzle game full of adorable characters and...cats! Put your cat onesie on, quest through colorful worlds, stop the nefarious Doc Block and craft adorable Piffle balls to collect.

Instruções: - Swipe or point with your finger to aim - Choose the best possible angle to shoot - Release to bounce around and break all the blocks', 'Difícil', 100, '{"width": 600, "height": 960}', false, 'available'),
('rider 2023', 'embed', 'https://img.gamemonetize.com/q9vlc7cdbzuaphuebcriv09cq2f7l2td/512x384.jpg', 'https://html5.gamemonetize.co/q9vlc7cdbzuaphuebcriv09cq2f7l2td/', 'Perform insane stunts while you cruise through the never-ending world of Rider 2! Grab your motorcycle and start flipping to get unlimited coins! Make insane jumps and challenge your opponents with the best scores. You can buy your own favorite motorcycle and become master rider in flipping your bike.', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Eat The Fish IO', 'embed', 'https://img.gamemonetize.com/lhqk8fcb4d4tne5l2ifg5q757nldxq4y/512x384.jpg', 'https://html5.gamemonetize.co/lhqk8fcb4d4tne5l2ifg5q757nldxq4y/', 'Game name is a free io game where you play as a deadly hungry fish with a sharp blade. Join a multiplayer arena of fish and hunt down your prey while avoidingthe sharp end of another player’s blade. Feed on other smaller fish head for boosts and grow big, dominate the sea and become the king of the the ocean.

Instruções: - Control your fish by one finger eliminate other fish by attacking from the side and behind with your blade - Press the Right side button for boosting speed and get advantage Feed on other fishes to recover mana Keep Speeding UP ', 'Médio', 100, '{"width": 1920, "height": 1080}', false, 'available'),
('Warrior Survival.io', 'embed', 'https://img.gamemonetize.com/eitm2ciil0yavsyfoiydtas8db1ly065/512x384.jpg', 'https://html5.gamemonetize.co/eitm2ciil0yavsyfoiydtas8db1ly065/', 'The magic soldiers fall from the sky, the bullets are like silver snakes, and the smoke of war is rolling in. This is a contest about the king of special forces. Hurry up and bring your guns to stand out in this competition. Remember that the dog will be the last victory!

Instruções: PC W A S D - Move click to shoot space - reload Phone Follow the game tutorial ', 'Difícil', 100, '{"width": 800, "height": 480}', false, 'available'),
('Bouncy Ball Garten', 'embed', 'https://img.gamemonetize.com/sbh8zar33xfqw4u58hohx2wiyl1y9rfp/512x384.jpg', 'https://html5.gamemonetize.co/sbh8zar33xfqw4u58hohx2wiyl1y9rfp/', 'Bouncy Ball Heroes is one of the most interesting bouncing ball games. With the simple control and challenging puzzle, the bouncy ball has been beautifully designed for players of all age groups. jump, and bounce the roller ball through a mechanical wasteland, the player needs to ensure that the jumping ball does not fall into shapes and Circles.

Instruções:  bull Tap screen amp jump with the ball bull Get higher number and challenge high score', 'Fácil', 100, '{"width": 600, "height": 960}', false, 'available'),
('Tall.io', 'embed', 'https://img.gamemonetize.com/3ref378qcywg2ksr0retgiaqcai1egfw/512x384.jpg', 'https://html5.gamemonetize.co/3ref378qcywg2ksr0retgiaqcai1egfw/', 'Help your stickman to become as tall as possible. Collect cubes of your color, run through gates, smash trees and other stickmen that are smaller than you, dodge obstacles. This is a simple and dynamic game.

Instruções: To make the stickman run hold down the mouse button and drag in the desired direction Collect bricks of your color and grow Green gates and balloons increase height red ones decrease yellow ones double ', 'Médio', 100, '{"width": 1080, "height": 1920}', false, 'available'),
('Save the Masters', 'embed', 'https://img.gamemonetize.com/6ccuk6fosd4jzx9h096uyzmfyea1dq5x/512x384.jpg', 'https://html5.gamemonetize.co/6ccuk6fosd4jzx9h096uyzmfyea1dq5x/', 'Chase the highest scores in a fun puzzle strategy action, that is based solely on your skill and logic! Aim carefully to rescue a wide variety of characters from a certain doom. Take your shot to cut down the rope - just aim and swipe in the right direction! What are you waiting for? Get out and save as many characters as possible! The game will be exciting for both kids and adults.', 'Difícil', 100, '{"width": 800, "height": 600}', false, 'available'),
('Bubble Shooter Pop: Fun Blast', 'embed', 'https://img.gamemonetize.com/znee39i0au1lz0430t0ewsfn2vz807ra/512x384.jpg', 'https://html5.gamemonetize.co/znee39i0au1lz0430t0ewsfn2vz807ra/', 'Shoot and pop bubbles and experience hours of fun in this classic bubble shooter game! Bubble Shooter 3 is a new and awesome bubble game, perfect for friends and family to play and enjoy. Play now and experience endless excitement with this highly addictive game!

Instruções: This fizzy game is addictive so watch out because the magic of the bubbles starts working once you shoot the balls ', 'Fácil', 100, '{"width": 800, "height": 600}', false, 'available'),
('ArcadeAgar.io', 'embed', 'https://img.gamemonetize.com/rxtsqrqi6coti3eu30g0b3o04ho4kvyv/512x384.jpg', 'https://html5.gamemonetize.co/rxtsqrqi6coti3eu30g0b3o04ho4kvyv/', 'Play online with players around the world as you try to become the biggest cell of them all! With new controls developed especially for touchscreens, agar.io offers the same fun gameplay that millions have already enjoyed on PC. Play online in free-for-all action and use splitting, shrinking and dodging tactics to catch other players - or avoid them! Use a variety of special secret skins with the right username!

Instruções: Control your tiny cell and eat other players to grow larger But watch out players bigger than you will be trying to make you their lunch Survive and eat long enough to become the biggest cell in the game ', 'Médio', 100, '{"width": 720, "height": 1280}', false, 'available'),
('GoTet.io', 'embed', 'https://img.gamemonetize.com/djcg61a4swys5wah0dxdi4c68i9hxc8f/512x384.jpg', 'https://html5.gamemonetize.co/djcg61a4swys5wah0dxdi4c68i9hxc8f/', 'GoTet.io is a tile matching growing game. You start with a 2x2 square and you move around the map, bumping into tiles and gluing them. The objective is to fill your square until the time is up. You have spells that help you and you can collect in-game coins to buy and equip charms that improve your game play. Can you get to the highest level?

Instruções: Move WASD arrow keys or mouse left click Grab SPACE bar or double click Drop M or right click N Rotate B Magnet arrange the tiles F Fire burn tiles in your path detonate X Speed temporary speed', 'Difícil', 100, '{"width": 1280, "height": 640}', false, 'available'),
('Bear Flight', 'embed', 'https://img.gamemonetize.com/ss3qe3zskhpf6lexakljn0hqc915dojq/512x384.jpg', 'https://html5.gamemonetize.co/ss3qe3zskhpf6lexakljn0hqc915dojq/', 'Fly through the Pillars without crashing! This extremely addictive arcade game spawned a worldwide Bear Flight craze.

Instruções: click Mouse Left to move up', 'Fácil', 100, '{"width": 900, "height": 600}', false, 'available');

