create table if not exists public.charades_cards (
    id uuid default gen_random_uuid() primary key,
    category text not null check (category in ('animals', 'people', 'objects', 'fruits')),
    text text not null,
    is_special boolean default false,
    special_action text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS
alter table public.charades_cards enable row level security;

-- Policies
create policy "Allow public read access on charades_cards"
    on public.charades_cards for select
    using (true);

create policy "Allow authenticated users to insert charades_cards"
    on public.charades_cards for insert
    with check (auth.role() = 'authenticated');

create policy "Allow authenticated users to update charades_cards"
    on public.charades_cards for update
    using (auth.role() = 'authenticated');

create policy "Allow authenticated users to delete charades_cards"
    on public.charades_cards for delete
    using (auth.role() = 'authenticated');

-- Indice para facilitar busca por categoria
create index if not exists charades_cards_category_idx on public.charades_cards(category);

-- Insert initial data
insert into public.charades_cards (category, text, is_special, special_action) values
-- Animals
('animals', 'Leão (Daniel)', false, null),
('animals', 'Baleia (Jonas)', false, null),
('animals', 'Ovelha (O Bom Pastor)', false, null),
('animals', 'Pomba (Noé)', false, null),
('animals', 'Burrinho (Jesus)', false, null),
('animals', 'Peixe (Pedro)', false, null),
('animals', 'Formiga (Sábia)', false, null),
('animals', 'Águia (Força)', false, null),
('animals', 'Camelo (Rico)', false, null),
('animals', 'Galo (Pedro)', false, null),
('animals', 'Serpente (No Éden)', false, null),
('animals', 'Cachorro', false, null),
('animals', 'Gato', false, null),
('animals', 'Macaco', false, null),
('animals', 'Coelho', false, null),
('animals', 'Tartaruga', false, null),
('animals', 'Elefante', false, null),
('animals', 'Girafa', false, null),
('animals', 'Pintinho', false, null),
('animals', 'Pato', false, null),
('animals', 'Vaca', false, null),
('animals', 'Porco', false, null),
('animals', 'Esquilo', false, null),
('animals', 'Jacaré', false, null),
('animals', 'Tubarão', false, null),
('animals', 'Urso', false, null),
('animals', 'Borboleta', false, null),
('animals', 'Coruja', false, null),
('animals', 'Canguru', false, null),
('animals', 'Zebra', false, null),
('animals', 'Hipopótamo', false, null),
('animals', 'Rinoceronte', false, null),
('animals', 'Tigre', false, null),
('animals', 'Lobo', false, null),
('animals', 'Aranha', false, null),
('animals', 'Abelha', false, null),
('animals', 'Cavalo', false, null),
('animals', 'Boi', false, null),
('animals', 'Grilo', false, null),
('animals', 'Pássaro', false, null),

-- People
('people', 'Davi (Estilingue)', false, null),
('people', 'Golias (Gigante)', false, null),
('people', 'Noé (Martelo)', false, null),
('people', 'Moisés (Cajado)', false, null),
('people', 'Sansão (Forte)', true, 'Dê um abraço bem forte!'),
('people', 'Rei Davi', false, null),
('people', 'Ester (Rainha)', false, null),
('people', 'Pastor de Ovelhas', false, null),
('people', 'Pescador (Rede)', false, null),
('people', 'Semeador (Sementes)', false, null),
('people', 'José (Túnica)', false, null),
('people', 'Maria (Bebê Jesus)', false, null),
('people', 'Anjo (Asas)', false, null),
('people', 'Daniel (Oração)', false, null),
('people', 'Jonas (Fugindo)', false, null),
('people', 'Zaqueu (No pé)', false, null),
('people', 'Cego Bartimeu', false, null),
('people', 'Bom Samaritano', false, null),
('people', 'João Batista', false, null),
('people', 'Paulo (Escrevendo)', false, null),
('people', 'Abraão (Estrelas)', false, null),
('people', 'Isaque (Caminhando)', false, null),
('people', 'Rebeca (Cântaro)', false, null),
('people', 'Rute (Colheita)', false, null),
('people', 'Samuel (Ouvindo)', false, null),
('people', 'Elias (Fogo)', false, null),
('people', 'Eliseu (Capa)', false, null),
('people', 'Gideão (Vaso)', false, null),
('people', 'Débora (Juíza)', false, null),
('people', 'Josué (Muralha)', false, null),
('people', 'Miriã (Pandeiro)', false, null),
('people', 'Sarah (Rindo)', false, null),
('people', 'Marta (Limpando)', false, null),
('people', 'Maria Madalena', false, null),
('people', 'Soldado Romano', false, null),
('people', 'Pedinte', false, null),
('people', 'Ladrão na Cruz', false, null),
('people', 'Dono da Estalagem', false, null),
('people', 'Sábio', false, null),
('people', 'Criança com Lanches', false, null),

-- Objects
('objects', 'Arca de Noé', false, null),
('objects', 'Cesta de Moisés', false, null),
('objects', 'Harpa de Davi', false, null),
('objects', 'Coroa de Ouro', false, null),
('objects', 'Cruz de Jesus', true, 'Diga "Jesus te ama"!'),
('objects', 'Bíblia', false, null),
('objects', 'Pão e Peixe', false, null),
('objects', 'Cajado de Pastor', false, null),
('objects', 'Estilingue', false, null),
('objects', 'Trombeta', false, null),
('objects', 'Barco de Pesca', false, null),
('objects', 'Rede de Sair', false, null),
('objects', 'Lamparina', false, null),
('objects', 'Tenda', false, null),
('objects', 'Altar', false, null),
('objects', 'Escada de Jacó', false, null),
('objects', 'Túnica Colorida', false, null),
('objects', 'Moedas de Prata', false, null),
('objects', 'Poço de Água', false, null),
('objects', 'Mesa de Jantar', false, null),
('objects', 'Cadeira', false, null),
('objects', 'Janela', false, null),
('objects', 'Porta', false, null),
('objects', 'Chave', false, null),
('objects', 'Martelo', false, null),
('objects', 'Serrote', false, null),
('objects', 'Vassoura', false, null),
('objects', 'Balde', false, null),
('objects', 'Espada de Brinquedo', false, null),
('objects', 'Escudo', false, null),
('objects', 'Capacete', false, null),
('objects', 'Sandália', false, null),
('objects', 'Anel', false, null),
('objects', 'Espelho', false, null),
('objects', 'Relógio', false, null),
('objects', 'Telefone', false, null),
('objects', 'Bola', false, null),
('objects', 'Boneca', false, null),
('objects', 'Carrinho', false, null),
('objects', 'Pipa', false, null),

-- Fruits
('fruits', 'Maçã', false, null),
('fruits', 'Uva', false, null),
('fruits', 'Figo', false, null),
('fruits', 'Banana', false, null),
('fruits', 'Melancia', false, null),
('fruits', 'Morango', false, null),
('fruits', 'Abacaxi', false, null),
('fruits', 'Laranja', false, null),
('fruits', 'Limão', false, null),
('fruits', 'Pera', false, null),
('fruits', 'Manga', false, null),
('fruits', 'Mamão', false, null),
('fruits', 'Melão', false, null),
('fruits', 'Kiwi', false, null),
('fruits', 'Cereja', false, null),
('fruits', 'Goiaba', false, null),
('fruits', 'Caju', false, null),
('fruits', 'Amora', false, null),
('fruits', 'Framboesa', false, null),
('fruits', 'Pitaya', false, null),
('fruits', 'Maracujá', false, null),
('fruits', 'Tangerina', false, null),
('fruits', 'Ameixa', false, null),
('fruits', 'Pêssego', false, null),
('fruits', 'Caqui', false, null),
('fruits', 'Carambola', false, null),
('fruits', 'Jabuticaba', false, null),
('fruits', 'Acerola', false, null),
('fruits', 'Coco', false, null),
('fruits', 'Graviola', false, null),
('fruits', 'Romã', false, null),
('fruits', 'Jaca', false, null),
('fruits', 'Abacate', false, null),
('fruits', 'Lichia', false, null),
('fruits', 'Tâmara', false, null),
('fruits', 'Damasco', false, null),
('fruits', 'Nozes', false, null),
('fruits', 'Castanha', false, null),
('fruits', 'Pistache', false, null);
